### ISSUE TITLE
HDR video go full black screen on video start and end

### ISSUE THREAD

**Issue by molitar** [Aleksoid1978/VideoRenderer#102]
How do I stop this annoying behavior no matter what video I play my entire monitor goes to full black than starts playing video and when I stop it does the same thing.

**Comment by Aleksoid1978** [comment]
It is completely unclear what is happening. Maybe your player switches the screen frequency, maybe something else.
Or Fullscreen is selected in the renderer, and when entering/exiting the full screen, reinitialization occurs.

**Comment by v0lt** [comment]
I would recommend changing the Swap effect to Discard.

**Comment by molitar** [comment]
It appears to be more of cutting display to monitor when it starts and stops rendering.  The entire goes pure black as if PC went to sleep or that.

**Comment by v0lt** [comment]
> It appears to be more of cutting display to monitor when it starts and stops rendering. The entire goes pure black as if PC went to sleep or that. My GPU is an AMD Radeon 5600XT

I think this is a driver bug.

**Comment by clsid2** [comment]
`Auto Display HDR on/off` setting! Disable that as see what happens.

**Comment by molitar** [comment]
> `Auto Display HDR on/off` setting! Disable that as see what happens.

Thanks you solved it!  That was the problem!

**Comment by clsid2** [comment]
More and more people have HDR mode enabled by default in Windows.

At default settings MPCVR will turn HDR off whenever a user plays a SDR video. My opinion is that it should never turn off HDR in Windows. It should only turn on HDR when needed (and then off again at end of playback).

I have a patch for it if you want to change the behavior.

**Comment by molitar** [comment]
> More and more people have HDR mode enabled by default in Windows.
> 
> At default settings MPCVR will turn HDR off whenever a user plays a SDR video. My opinion is that it should never turn off HDR in Windows. It should only turn on HDR when needed (and then off again at end of playback).
> 
> I have a patch for it if you want to change the behavior.

Sounds great

**Comment by Aleksoid1978** [comment]
Yeah - and then there will be questions when playing SDR video, why it looks somehow strange (the HDR mode was just turned on in the system).

**Comment by clsid2** [comment]
Are you assuming that or have you actually tested it?
I have not heard any complaints.

**Comment by Aleksoid1978** [comment]
SDR look's not "good" when HDR mode enabled

**Comment by clsid2** [comment]
Yet, there are many people who prefer that.
Why not just give an option to do "HDR on" only in addition to current "HDR on/off"?

**Comment by Aleksoid1978** [comment]
> Why not just give an option to do "HDR on"

Patch are welcome.

**Comment by clsid2** [comment]
Patch is on my ToDo list.
