### ISSUE TITLE
Subtitles only appear after re-entering fullscreen.

### ISSUE THREAD

**Issue by catamphetamine** [Aleksoid1978/VideoRenderer#103]
* Open any video file
* Go to fullscreen mode without enabling subtitles
* Enable subtitles while in fullscreen mode
* Subtitles don't show
* Exit fullscreen mode to windowed mode
* Subtitles are shown
* Enter fullscreen mode
* Subtitles are shown. Can watch the movie.

MPC 2.1.0
Latest `VideoRenderer` _installed_ yesterday — `MpcVideoRenderer-0.6.9.2117.zip`.

Is selected in Options → Output → DirectShow Video.

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/477167/7a890e91-f083-47d4-a8b9-2dfdd1d5a866)

Not a major issue since subtitles appear after re-entering fullscreen

**Comment by Aleksoid1978** [comment]
It's MPC-HC, ask it's developers.

**Comment by v0lt** [comment]
I don't confirm.
MPC 1.6.10.64 dev, MPC Video Renderer 0.7.0.2152.

**Comment by clsid2** [comment]
Can not reproduce with MPC-HC either.

**Comment by catamphetamine** [comment]
Hmm. Ok, maybe it's something in my setup then. Thx.
