### ISSUE TITLE
Nvidia RTX video super resolution is not working correctly when playing 10bit hevc video

### ISSUE THREAD

**Issue by magiclu** [Aleksoid1978/VideoRenderer#104]
Nvidia RTX video super resolution is not working correctly when playing hevc video
I upgrade all the related software to newest
Nvidia driver  546.01
MPC-BE.1.6.10
MPC Video Renderer 0.6.9.2117

GPU:RTX 3080ti

when playing h264 video my gpu can get to about 100-120w power draw on quality 4 and I can see video quality improvement
when playing 8bit hevc video my gpu can get to about 100-120w power draw on quality 4 and I can see video quality improvement
when playing 10bit hevc video my gpu can stay at about 32w power draw on quality 4 and I can not see video quality improvement

8bit hevc is rare.10bit hevc is common

windows 11.tried with OS HDR on and off. the same

Is this Nvidia's issue?

<img width="488" alt="image" src="https://github.com/Aleksoid1978/VideoRenderer/assets/3338197/2245af84-3385-4173-bb68-7b0d5ffe2f8b">
<img width="436" alt="image" src="https://github.com/Aleksoid1978/VideoRenderer/assets/3338197/e43f6eb3-f93f-43ad-af4c-58328046aa38">

**Comment by clsid2** [comment]
It does not support 10-bit.
Limitation of NVIDIA driver.

**Comment by magiclu** [comment]
I found a workaround .I changed texture format to 8bit from auto

Even if doing this may downgrade video quality. After VSR. It is still an upgrade

<img width="191" alt="image" src="https://github.com/Aleksoid1978/VideoRenderer/assets/3338197/f467cd74-a06f-4cb5-a95a-7e161d852781">
