### ISSUE TITLE
MPC VR - Disables Nvidia Reference Mode

### ISSUE THREAD

**Issue by Mind777** [Aleksoid1978/VideoRenderer#107]
I have a pc monitor and tv connected to pc. 

Since i use the windows night light feature, i enable reference mode in nvidia control panel for my tv so movie color displays correctly (reference mode disables night light color).

With MPC VR it seems to override reference mode and night light is active on my tv screen. I have to switch night light off manually.

Is there a fix for this?

**Comment by Mind777** [comment]
I'm not using exclusive full screen mode.

Just tested again. Night light comes on even with reference mode enabled in nvidia control panel.

I am using with MPC-HC beta - https://github.com/clsid2/mpc-hc/releases/

Perhaps this is why?

**Comment by v0lt** [comment]
Try disabling "Auto HDR display On/Off" in MPC Video Renderer settings.

Also disable automatic detection of "HDMI Content Type" in the driver settings.

**Comment by Mind777** [comment]
Disabling "Auto HDR display On/Off" doesn't play the video as HDR (no HDR popup notice on tv). Assuming this is being tonemapped now?

Disabling automatic detection of "HDMI Content Type" has no change.

So when i have MPC VR playing HDR passthrough, i still get night light on even though tv is set as reference mode in nvidia control panel.

Issue with night light doesn't occur with madvr.

**Comment by clsid2** [comment]
The problem is with NVIDIA. Player and renderer just use standard APIs and do nothing that actively disables night light.

**Comment by Mind777** [comment]
Strange thing is, night light stays disabled with madvr. Only using mpc vr it comes on?

**Comment by clsid2** [comment]
Disable the video processor in MPCVR. Then it uses just shaders like Madvr. Maybe that helps. Video processor behavior depends on the driver.

The "bug" in in Windows or NVIDIA driver. It is irrelevant that it doesn't happen with Madvr, because MPCVR doesn't do anything wrong here.

**Comment by Mind777** [comment]
ok, no problem.

Disabling video processor didn't help, so will just have to disable night light manually.

btw, will you be implementing a feature to match resolution/refresh rate of video?
