### ISSUE TITLE
HDR info not used when using external subtitle renderer

### ISSUE THREAD

**Issue by GameProgramer** [Aleksoid1978/VideoRenderer#109]
Specs:
Windows 10 22H2
Nvidia 1660Ti
Driver 536.23
MPC-BE 1.6.10 x32
MPC-VR 0.6.9.2117 x32

I'm a new user of MPC-BE and am unsure if this a known issue. I did search but couldn't find any pertinent info. 
I noticed that HDR info is lost when an external subtitle renderer (such as X-Y Subfilter) is used, by setting that option in MPC-BE. 

Plays correctly:
![MPC-BE-Subtitles-Internal](https://github.com/Aleksoid1978/VideoRenderer/assets/5203494/7968bb58-0960-44a2-a401-a1b43a5b7f96)
![MPC-VR-Stats-Correct](https://github.com/Aleksoid1978/VideoRenderer/assets/5203494/66b9c93d-4de6-4093-82a6-6c10cb06288d)

Plays incorrectly:
![MPC-BE-Subtitles-External](https://github.com/Aleksoid1978/VideoRenderer/assets/5203494/43c904da-1f94-4d9b-b2c5-9766c81615d1)
![MPC-VR-Stats-Incorrect](https://github.com/Aleksoid1978/VideoRenderer/assets/5203494/0887ec5e-ce50-4be4-b2cb-1415e9775372)

Media Info:
![Video-Details](https://github.com/Aleksoid1978/VideoRenderer/assets/5203494/34749850-5cfa-4d41-84c9-925aa37b911b)

**Comment by clsid2** [comment]
(xy-)VSFilter does forward HDR metadata from decoder to renderer.

You should not use it.

**Comment by v0lt** [comment]
Using (xy-)VSFilter is a bad idea.
If you are not satisfied with the built-in renderer of subtitles, then you can try to use **XySubFilter**.
https://github.com/Cyberbeing/xy-VSFilter/releases
https://github.com/pinterf/xy-VSFilter/releases
https://github.com/Masaiki/xy-VSFilter/releases
