### ISSUE TITLE
Inquiry About DV Support of Current Night Builds

### ISSUE THREAD

**Issue by bluecat1024** [Aleksoid1978/VideoRenderer#110]
Hi,

There are some uncertain discussions in forums about whether the render takes PRU into consideration against ordinary HDR10 display, when having both 'Dolby over PQ/HLG' and 'Passthrough' checked.
I wonder if during the mapping to HDR10 data, is the PRU tone mapping calculated like Windows Movies, or MPC simply passes the HDR10 layer to display? Is the case different for profile 5 and 8, for the current 0.7 night build?

Thanks so much!

**Comment by v0lt** [comment]
I don't have an HDR display.
"Prefer Dolby Vision over PQ and HLG" is used for Dolby Vision Profiles 8.1 and 8.4. These profiles are compatible with HDR10 and HLG. There is not much point in enabling this option.

> Is the case different for profile 5 and 8, for the current 0.7 night build?

https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt
_Added brightness and contrast adjustment for Dolby Vision._

**Comment by bluecat1024** [comment]
> I don't have an HDR display. "Prefer Dolby Vision over PQ and HLG" is used for Dolby Vision Profiles 8.1 and 8.4. These profiles are compatible with HDR10 and HLG. There is not much point in enabling this option.
> 
> > Is the case different for profile 5 and 8, for the current 0.7 night build?
> 
> https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt _Added brightness and contrast adjustment for Dolby Vision._

Thanks for pointing that out. I believe it is better to check this even for profile 8 because PRU is applied for adjustment over hdr10 compatible layer.

Could you help check whether 0.7 is applying dynamic Dolby Vision adjustments before passing  hdr10 or sdr content to the non-DV displays? Do I need to uncheck passthrough to make the adjustments work correctly? Thanks!

**Comment by Aleksoid1978** [comment]
DV is converted to HDR10, then, depending on whether HDR mode is enabled in the system or not, HDR metadata is passthrough or HDR -> SDR conversion is done.
Supported DV profiles 5 and 8.

**Comment by bluecat1024** [comment]
> DV is converted to HDR10, then, depending on whether HDR mode is enabled in the system or not, HDR metadata is passthrough or HDR -> SDR conversion is done.
> Supported DV profiles 5 and 8.

Is the passthrough hdr metadata the dynamic rpu info of the DV or some fixed static thing? DV should rely on dynamic metadata to get played correctly, so I wonder if the metadata is passed differently for each frame in DV?

**Comment by bluecat1024** [comment]
> DV is converted to HDR10, then, depending on whether HDR mode is enabled in the system or not, HDR metadata is passthrough or HDR -> SDR conversion is done. Supported DV profiles 5 and 8.

Sorry for some potential confusion; actually what matters is where the dynamic RPU info get handled (whether it's SDR or HDR10 display). Is that dynamic mapping calculation done at DV->HDR10 step or some later steps? Or is RPU layer discarded so far?

**Comment by Aleksoid1978** [comment]
DV metadata (rpu) is handled for each frame in DV. It's use to convert DV -> HDR10.
For HDR10 metadata (for passthrough) from DV use only min/max mastering luminance. Other is constant - "Display P3 primaries".
