### ISSUE TITLE
Auto convert HDR video to SDR not work with subtitle filter(DirectVobSub or XySubFilter)

### ISSUE THREAD

**Issue by CarefulDeveloper** [Aleksoid1978/VideoRenderer#111]
As my title said.
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/78646351/592d055b-0a80-412e-a2f0-3410acbf451e)

**Comment by v0lt** [comment]
Duplicate for #109.

This is not an MPC VR problem.
Don't use VSFilter (DirectVobSub).
Use the built-in subtitle renderer or you can try XySubFilter (there are 3 versions from different developers).

**Comment by CarefulDeveloper** [comment]
> Duplicate for #109.
> 
> This is not an MPC VR problem. Don't use VSFilter (DirectVobSub). Use the built-in subtitle renderer or you can try XySubFilter (there are 3 versions from different developers).

Oh, thank you!
