### ISSUE TITLE
GPU 3D usage is high

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#112]
Is there any scope of improvements?
MPC always uses two times more GPU (3D) than VLC or Windows Media Player. When I spent some time on this then I found that this is because of video renderer. EVR uses least amount of GPU, but it is still higher than VLC. MPC-VR uses more than EVR. Then it comes EVR-CP, which is the worst.
**GPU 3D usage rank from low to high: VLC<EVR<MPC-VR<EVR-CP**
On reddit someone wrote about this: https://www.reddit.com/r/MPCHC/comments/ra6pyw/mpchc_using_much_more_3d_gpu_than_other_players/?rdt=50039
![Screenshot (34)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/ac718a1b-1382-43e9-8130-967c5f1dbb2c)
![Screenshot (33)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/b184c3a6-57b2-44c7-8fef-5a310ed74b00)
![Screenshot (32)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/04b702d6-2539-410c-8e64-d147bb080caa)
Can you do something to reduce the GPU usage?

**Comment by Aleksoid1978** [comment]
And what - in our renderers there is a lot of post-processing, etc. If you are very interested, open the source code and study it.

**Comment by bibsp** [comment]
If you give option to turn off those extra post processing it will improve laptop battery life.

**Comment by v0lt** [comment]
> If you give option to turn off those extra post processing it will improve laptop battery life.

All features are implemented in the MPC Video Renderer settings. Just change them and see the result.
If this is not enough for you, then I will advise you to use EVR. This will be the most energy efficient solution for your integrated graphics card.

**Comment by bibsp** [comment]
Yes, but EVR lacks many features. The reason I created this issue was, I have seen MPC-VR consumes less GPU but still gives slightly better image than EVR-CP. So, I thought there maybe further scope of improvements. But anyway if this is not possible then it's okay. Thanks.
