### ISSUE TITLE
The VSR function of MPCVR seems to not work

### ISSUE THREAD

**Issue by RBHakureiReimu** [Aleksoid1978/VideoRenderer#113]
I am using MPCVR in MPC-BE, and I have enabled the VSR function. Although the video status shows that VSR is effective, the GPU usage does not increase significantly after turning on VSR, and the picture does not have any traces of being processed by VSR. My graphics card is RTX 2070. NVIDIA released VSR1.5 a while ago, which enables Turing architecture graphics cards to support VSR technology. And I can also use NVIDIA VSR normally in the browser. Here are screenshots of the interfaces. I hope the author can fix this problem.
![图片](https://github.com/Aleksoid1978/VideoRenderer/assets/45761551/6526d923-1fee-4ada-a5ff-975762a350c8)
![图片](https://github.com/Aleksoid1978/VideoRenderer/assets/45761551/e1fa9a13-256f-44c9-bd55-62e709145047)
![图片](https://github.com/Aleksoid1978/VideoRenderer/assets/45761551/b758cfb4-d780-45ab-bfb8-46f115b17d41)
![图片](https://github.com/Aleksoid1978/VideoRenderer/assets/45761551/3210c0f7-e767-4ec2-a9b3-e2a964a66c34)

**Comment by Aleksoid1978** [comment]
We do not control the operation (or not operation) of the VSR - the API only has a function to enable it, but there is no way to find out whether it is actually turned on and, if not, for what reason.

**Comment by Aleksoid1978** [comment]
Texture format - set to "Auto ...", must help.

**Comment by RBHakureiReimu** [comment]
> Texture format - set to "**Auto ...**", must help.

I followed your instructions and VSR did work. Thank you very much! But I have another question, that is, why can’t VSR work under "16bit …"?

**Comment by Aleksoid1978** [comment]
It's limitation of VSR.

**Comment by hooke007** [comment]
> why can’t VSR work under "16bit …"?

It can work. Set your driver's output 8 bit instead.
