### ISSUE TITLE
FSR 1.0 upscaler

### ISSUE THREAD

**Issue by BuyMyMojo** [Aleksoid1978/VideoRenderer#114]
I know issue #40 exists but I would also love to still see FSR 1 added into the renderer.

> For video scaling much better algorithms exist like FSRCNN.

That is a full super resolution method but FSR 1 is just a Edge-Adaptive Spatial Upsampling method and does not attempt to be Super Res. I would prefer to use it over Catmull-Rom or Lanczos.

> Developers don't have AMD video cards.

This is not needed! FSR 1.0 is just an upscaling filter and is not hardware specific. there is a GLSL implementation for MPV [here](https://gist.github.com/agyild/82219c545228d70c5604f865ce0b0ce5) for the reason that it can be a preferred scaler.

it is a very light weight method and for watching game content it is especially nice but I've also found it to be my preferred way to watch modern 1080p anime on my 4k monitor.

Current FSR1.1 repo: https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/main/docs/techniques/super-resolution-spatial.md

**Comment by Aleksoid1978** [comment]
DirectX 12 + HLSL.
We don't support DX12.

**Comment by BuyMyMojo** [comment]
[Magpie](https://github.com/Blinue/Magpie) got it working under [DX10](https://github.com/Blinue/Magpie/blob/e1f1eed22660050484a5c237ed096197dacf0c99/docs/Built-in%20effects.md?plain=1#L144) [hlsl](https://github.com/Blinue/Magpie/tree/dev/src/Effects/FSR)

**Comment by v0lt** [comment]
I don't understand what you need (I don't have an AMD card). But you can make the changes yourself and create a pull request so that we can take a look and other users can test your solution.

**Comment by butterw** [comment]
You don't need an amd card, it can run on integrated graphics, works pretty well as a sharp scaler in mpv,

**Comment by Aleksoid1978** [comment]
I'm not interest. If somebody create patch/pull request - ok.
