### ISSUE TITLE
Any plans to make the renderer compatible with the upcoming nvidia driver update with "RTX Video HDR"?

### ISSUE THREAD

**Issue by geahad** [Aleksoid1978/VideoRenderer#116]
The renderer already supports "requesting" VSR, and it functions splenditily! So, as Nvidia announced that with this months driver update (probably due on the 17th of this month) they'll introduce RTX Video HDR, something that, by the description of it, would function similarly like AutoHDR for games, essentially automatically inverse-tonemapping SDR video content to HDR. Link to nvidia blog (scroll down to relevant section): https://blogs.nvidia.com/blog/studio-rtx-hdr-video-twitch-obs-istock-getty-super-laptop-desktop/ 

By their description, this function will be enabled by a toggle in the driver that's sepparate from VSR itself.

I hope this will not be problematic to implement, as it sounds absolutely awesome.

Thank you for reading, and thank you for this renderer of yours -- it already provided much joy to my video collection!

**Comment by Aleksoid1978** [comment]
Developer don't have supported hardware (Nvidia >= 2xxx series).
If someone can provide/buy the appropriate equipment for developers, then yes, we will do it.

**Comment by geahad** [comment]
Thank you for your answer! I'll try aksing other devs if they can help.

**Comment by v0lt** [comment]
> (probably due on the 17th of this month)

I don’t see the point in planning support for something that doesn’t exist.

**Comment by maxsteep** [comment]
it exists now

**Comment by emoose** [comment]
Haven't been able to find any public docs about NV's VSR/HDR stuff, but like VSR the code to enable HDR is available in the chromium src.

https://github.com/chromium/chromium/commit/b2fae4c98404bec282f24cd7d8a63aced9070fda seems to be commit that added it, but they did change some things since then, latest code is here: https://github.com/chromium/chromium/blob/04fa180dc7aea16a905f79c715dc2ee5cc6f742b/ui/gl/swap_chain_presenter.cc#L358 (ToggleNvidiaVpTrueHDR func in case link doesn't go there directly)

Seems to be enabled the same way as VSR by passing a `kNvidiaTrueHDRInterfaceGUID` guid over to VideoProcessorSetStreamExtension, no telling if VideoRenderer can work with it as easily as VSR though.

**Comment by Aleksoid1978** [comment]
Developer don't have supported hardware (Nvidia >= 2xxx series).

**Comment by BreakPoints** [comment]
@clsid2 
Doesn't seem to trigger for me. Also did a side by side with another renderer and both had identical brightness/colours.

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/11966090/b02b8599-b744-4424-b56e-036489cee0cf)

**Comment by geahad** [comment]
Can also confirm that it does not trigger. Had the recommended settings for VSR still set:

- using your latest MPC build, x64
- inside LAV video settings: DXVA2 (copy back) + automatic, P010 and P016 boxes unchecked
- inside video renderer settings: Auto 8/10-bit integer selected, and specifically P010/P016 box unchecked
- tried checking and unchecking the boxes for prefer dolby vision and passthrough hdr, no dice...

Btw. I REALLY appreciate that you're trying to get this to work!

**Comment by geahad** [comment]
Appologies, I didn't list that I had all that enabled too. It triggers fine in chrome for me. Under the same conditions, it does not trigger with the test renderer.

**Comment by BreakPoints** [comment]
@clsid2 Yes, I have all of the following as can be seen in my screenshot.

**Comment by geahad** [comment]
For me, under the same conditions as before, both _test2 and _test3 versions do not trigger the desired HDR functionality.

**Comment by MarcG2** [comment]
I confirmed as well test2 and test3 didn't trigger HDR.  It works for me in Chrome without issue.

**Comment by Aleksoid1978** [comment]
Give me a video card and I will do everything that you are suffering here. And I won’t write code at random, much less upload it to the project.

**Comment by MarcG2** [comment]
> Give me a video card and I will do everything that you are suffering here. And I won’t write code at random, much less upload it to the project.

I don't suppose you can set up an Amazon wish list?  Are you located in Russia?

**Comment by emoose** [comment]
> I give up. Someone with RTX card should try to make it work. Here is WIP patch.

Thanks, tried testing with this, seems we get S_INVALIDARG from the VideoProcessorSetStreamExtension call when we call it early on, but moving the `SetRtxHdrNvidia` call to after we've ran `VideoProcessorSetOutputTargetRect` (as chrome seems to) gets it to return S_OK.

There was some weirdness with the colorspaces too, had to remove a SourceIsHDR check inside `InitSwapChain()` so that bHdrOutput would be set to true, and remove the `bVPUseAutoHDR` bool since it's too early for NV to give us the right result.

With those changed NVCP shows HDR is active for me & changing the setting there seems to dim the image a bit, not really sure if it's having the complete effect or not though.

If anyone wants to try: 
[RTXVideoHDR-wip2.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14058892/RTXVideoHDR-wip2.zip)

Would guess this might break stuff with non-hdr displays though, so not really recommended for general use.

**Comment by Noz0mizore** [comment]
> > 나는 포기한다. RTX 카드를 가진 사람이 이를 작동시키도록 노력해야 합니다. 다음은 WIP 패치입니다.
> 
> 감사합니다. 이것으로 테스트해 보니 VideoProcessorSetStreamExtension 호출을 초기에 호출할 때 S_INVALIDARG를 얻는 것 같습니다. 그러나 호출을 `SetRtxHdrNvidia`실행한 후로 이동하면 `VideoProcessorSetOutputTargetRect`(크롬에서 보이는 것처럼) S_OK를 반환하게 됩니다.
> 
> 색상 공간에도 문제가 있었고, `InitSwapChain()`bHdrOutput이 true로 설정되도록 내부에서 SourceIsHDR 검사를 제거해야 했으며, `bVPUseAutoHDR`NV가 올바른 결과를 제공하기에는 너무 이르기 때문에 부울을 제거해야 했습니다.
> 
> 변경된 NVCP를 사용하면 HDR이 활성화되어 있고 설정을 변경하면 이미지가 약간 어두워지는 것처럼 보이지만 완전한 효과가 있는지 여부는 확실하지 않습니다.
> 
> 누구든지 시도하고 싶다면: [RTXVideoHDR-wip2.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14058892/RTXVideoHDR-wip2.zip)
> 
> (이렇게 하면 HDR이 아닌 디스플레이의 문제가 발생할 수 있으므로 일반적인 사용에는 권장되지 않습니다.)
> 
> E: 효과가 없으면 내부 필터 -> 비디오 디코더 -> 하드웨어 디코더를 D3D11로 변경하고 하드웨어 장치도 선택해야 할 수 있습니다. 자동으로 놔두면 활성화되지 않는 것 같습니다.

I did what you said and it works. I'll have to see if there's something different about how it works in chrome.

**Comment by Noz0mizore** [comment]
![Chrome-HDR](https://github.com/Aleksoid1978/VideoRenderer/assets/132704033/4bd80547-ffb8-402f-ae04-dcca84fe97b5)
**chrome (HDR->SDR tone mapping)**
![MPC-HC-HDR](https://github.com/Aleksoid1978/VideoRenderer/assets/132704033/e369c07f-5b55-4369-8f2d-9f4b986296ad)
**MPC-BE (HDR->SDR tone mapping)**

**Comment by Aleksoid1978** [comment]
> > Give me a video card and I will do everything that you are suffering here. And I won’t write code at random, much less upload it to the project.
> 
> I don't suppose you can set up an Amazon wish list? Are you located in Russia?

AliExpress.

**Comment by terrainer** [comment]
> > I give up. Someone with RTX card should try to make it work. Here is WIP patch.
> 
> Thanks, tried testing with this, seems we get S_INVALIDARG from the VideoProcessorSetStreamExtension call when we call it early on, but moving the `SetRtxHdrNvidia` call to after we've ran `VideoProcessorSetOutputTargetRect` (as chrome seems to) gets it to return S_OK.
> 
> There was something up with the colorspaces too, had to remove a SourceIsHDR check inside `InitSwapChain()` so that bHdrOutput would be set to true, and remove the `bVPUseAutoHDR` bool since it was too early for NV to give us the right result.
> 
> With those changed NVCP shows HDR is active for me & changing the setting there seems to dim the image a bit, not really sure if it's having the complete effect or not though.
> 
> If anyone wants to try: [RTXVideoHDR-wip2.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14058892/RTXVideoHDR-wip2.zip)
> 
> (would guess this might break stuff with non-hdr displays though, so not really recommended for general use)
> 
> E: if there's no effect you may need to change internal filters -> video decoder -> hardware decoder to D3D11 and select a hardware device for it too, doesn't seem to activate if it's left on automatic.

This is working for me too. Using a 3080.

**Comment by Mv-sk** [comment]
> > I give up. Someone with RTX card should try to make it work. Here is WIP patch.
> 
> Thanks, tried testing with this, seems we get S_INVALIDARG from the VideoProcessorSetStreamExtension call when we call it early on, but moving the `SetRtxHdrNvidia` call to after we've ran `VideoProcessorSetOutputTargetRect` (as chrome seems to) gets it to return S_OK.
> 
> There was something up with the colorspaces too, had to remove a SourceIsHDR check inside `InitSwapChain()` so that bHdrOutput would be set to true, and remove the `bVPUseAutoHDR` bool since it was too early for NV to give us the right result.
> 
> With those changed NVCP shows HDR is active for me & changing the setting there seems to dim the image a bit, not really sure if it's having the complete effect or not though.
> 
> If anyone wants to try: [RTXVideoHDR-wip2.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14058892/RTXVideoHDR-wip2.zip)
> 
> (would guess this might break stuff with non-hdr displays though, so not really recommended for general use)
> 
> E: if there's no effect you may need to change internal filters -> video decoder -> hardware decoder to D3D11 and select a hardware device for it too, doesn't seem to activate if it's left on automatic.

It's working for me so far. The only problem I'm having is moving the player to a monitor without HDR doesn't turn off the HDR in the player. It just becomes blown out. My browser automatically turns it off and on when going between monitors.

**Comment by emoose** [comment]
> `SetRtxHdrNvidia` function can be split into two parts. One to check for availability of the extension, and one to activate it. Call the availability function before init of videoprocessor. Store result in bool, and use that later for `bHdrPassthrough` and `bHdrOutput`.

Hm, seems both `GetStreamExtension` & `SetStreamExtension` are returning S_INVALIDARG when calling them early, guess it maybe needs `ID3D11VideoProcessor` to be created before it gives valid results (really a shame NV aren't releasing any docs for these ;_;)

>Does it work with NONE and DXVA2 Copyback?

For me it's working with None and both DXVA2 Copyback & DXVA2 Native, but D3D11 Native makes it stop having any effect.
