### ISSUE TITLE
Mouse cursor does not always disappear

### ISSUE THREAD

**Issue by roberto-sartori-gl** [Aleksoid1978/VideoRenderer#117]
Hi!

Issue: in certain conditions, using more than one display, the mouse cursor does not disappear over the video.

Steps to replicate:
- Enable 'Reinitialize D3D device when changing display'
- Open a video on the primary display and wait for it to start playing
- Move the MPC window from the primary display to a secondary display
- Put the video full screen on the secondary display
- From this moment, the mouse cursor will not disappear over the video anymore, even if the video is not full screen. The only way to restore the 'stock behaviour' is to restart MPC.

The issue does not appear:
- With the 'Reinitialize D3D device when changing display' option disabled
- Not using MPC VideoRenderer.

**Comment by Aleksoid1978** [comment]
I can't check it - don't have secondary display.

**Comment by Aleksoid1978** [comment]
Although - what does MPC VideoRenderer have to do with it, everything related to the mouse is controlled in the player.
Have you checked in MPC-BE?

**Comment by Aleksoid1978** [comment]
> Although - what does MPC VideoRenderer have to do with it, everything related to the mouse is controlled in the player. Have you checked in MPC-BE?

If there is no answer, I will close the issue.

**Comment by adipose** [comment]
> Does not seem to happen in BE fullscreen. Did notice BE never hides pointer in windowed, even without reinit.
> 
> @adipose Do you perhaps have any idea what might be wrong?

Guess is the mouse leave code is losing the parent window or something.  I can test later to see if I can repro it.

**Comment by Aleksoid1978** [comment]
This does not apply to the renderer.
