### ISSUE TITLE
Integreating Video Renderer with Zoom Player

### ISSUE THREAD

**Issue by bLightZP** [Aleksoid1978/VideoRenderer#119]
Hi,
I would like to better integrate the video renderer with Zoom Player, especially xySubFilter support and extended controls such as image rotation.

Is there a specific documentation of the extended capabilities I can look at?

**Comment by v0lt** [comment]
You can look at [MPCVRAllocatorPresenter.h](https://github.com/Aleksoid1978/MPC-BE/blob/master/src/filters/renderer/VideoRenderers/MPCVRAllocatorPresenter.h).
