### ISSUE TITLE
Rotation "bug"

### ISSUE THREAD

**Issue by adipose** [Aleksoid1978/VideoRenderer#12]
In madVR, when changing rotation, it seems to redraw automatically.  If MPCVR, it does not seem to.  mpc-be code calls "MoveVideoWindow()" after for all renderers except madVR (states it is for EVRcp and Sync).  In my testing, this was also required for MPCVR.

This is not a problem, but I wondered if it was intentional, or a "regression" compared to madVR.

Thanks!

**Comment by Aleksoid1978** [comment]
call MoveVideoWindow() is need for MPCVR.

**Comment by adipose** [comment]
Again, thanks!
