### ISSUE TITLE
Video Looks shaky, Scaling issue?

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#120]
My laptop has 2 GPUs. AMD integrated and NVIDIA RTX 3050 mobile GPU. Normally Video player uses integrated one by default. I changed windows graphics setting to force MPC to use my RTX card. Now the problem comes. Everything looks shakey if I use RTX card. Turing off HW acceleration doesn't fix it. Latest  driver. EVR-CP is fine. So it can't be driver bug. I don't use VLC, madVR. But I tried them. All are fine with NVIDIA. Only MPC-VR has this problem. I don't know the issue is only with downscaling or both scaling. I have not tested much.

See the screenshot of RTX one and zoom it.
![Screenshot (254)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/7e86b907-be03-4a27-ade5-621ae47773da)
![Screenshot (255)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/d1f67edd-6c61-4814-a6c8-dafb2de20157)
![Screenshot (256)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/31c7dede-dc4f-4c46-869f-e62a99fabff5)

**Comment by v0lt** [comment]
The problem is in the implementation of the frame reduction algorithm in the Nvidia driver.
Disable the "DXVA2 and D3D11 Video Processor > **Use for resizing**" setting.

**Comment by bibsp** [comment]
I already tried. It is fine if I disable it.

How EVR-CP is clear?

**Comment by Aleksoid1978** [comment]
EVR-CP use D3D9, maybe bug in D3D11 implementation.

**Comment by v0lt** [comment]
> How is EVR-CP clear?

EVR-CP by default uses the correct frame reduction shader in MPC-BE.

You can compare with EVR, which uses driver capabilities.

**Comment by bibsp** [comment]
> You can compare with EVR, which uses driver capabilities.

@v0lt You are right. EVR also has this issue.
Can anyone report this to Nvidia please.

**Comment by bibsp** [comment]
![Screenshot (267)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/9f1ab145-09dd-41a6-8a35-866a13e24031)
![Screenshot (268)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/2131ec22-9817-42b3-acef-2716b12c0ce1)

I just found that, for SDR video the scaling is perfect. Does scaling depend on input format? NV12 is fine, P010 is buggy.

**Comment by Aleksoid1978** [comment]
Using VP - all questions to the driver.
Use shaders - and everything will be fine.

**Comment by v0lt** [comment]
> I just found that, for SDR video the scaling is perfect. Does scaling depend on input format? NV12 is fine, P010 is buggy.

Compare with the system Enhanced Video Renderer, it will be the same, because this implementation is in the driver.

**Comment by bibsp** [comment]
EVR is same.

This is a big issue, please someone report this to Nvidia, else they will not fix it anytime soon. I don't know where and how to report. A technical guy can properly explain.
I really want to use super resolution feature. But, because of this bug I can't use it.

**Comment by v0lt** [comment]
This is not Super Resolution, it is a defect or simplification of the image reduction algorithm for P010.
This problem can also occur when playing videos in the browser.

For questions to Nvidia, start with this page: https://www.nvidia.com/en-us/support/consumer/

**Comment by bibsp** [comment]
> This is not Super Resolution

Yes I know. Problem is I can't use Nvidia CPU only for upscaling, and shader for downscaling. This is not possible. To get proper scaling I have to use my AMD GPU which doesn't support super resolution. Anyway, thanks...

**Comment by bibsp** [comment]
I confirm this issue is fixed in latest Nvidia driver.
