### ISSUE TITLE
Do you have any plans to support RTX Video HDR?

### ISSUE THREAD

**Issue by Noz0mizore** [Aleksoid1978/VideoRenderer#121]
https://nvidia.custhelp.com/app/answers/detail/a_id/5448

Nvidia's recent VSR update added status indicators and RTX Video HDR, which converts SDR footage to HDR. Will you be adding these?

RTX Video HDR might take a while, but I don't think it's that hard to apply status indicators.

**Comment by Aleksoid1978** [comment]
https://github.com/Aleksoid1978/VideoRenderer/issues/116
