### ISSUE TITLE
Poor downscaling quality, lots of aliasing.

### ISSUE THREAD

**Issue by Yakumounr** [Aleksoid1978/VideoRenderer#122]
Small windowed views have very poor image quality when downscaling footage no matter which options are tried in the Shader Video Processor section of the settings, this is compared to the Enhanced Video Renderer included with MPC-HC. Badly aliased curved lines are particularly noticeable on any drawn animation.

**Comment by Yakumounr** [comment]
Unfortunately that means my problem is perhaps unsolvable, I had hoped to use the emoose RTX fork to use VSR if upscaling >= FullHD, but not be left with aliasing when in a reduced window, without having to change settings in between of course. I had guessed incorrectly that this was down to a problem from the original project after seeing the same aliasing switching to the original Aleksoid1978 release.
Thank you for your time, and apologies for my mistake.

**Comment by Yakumounr** [comment]
I was simply not expecting it to be a significant downgrade in small windows from the Enhanced Video Renderer (custom presenter) default.

**Comment by v0lt** [comment]
Duplicate for #120.

**Comment by Aleksoid1978** [comment]
There’s no need to do this, it will complicate the code too much, which is not simple anyway

**Comment by Yakumounr** [comment]
This does looks to be resolved now with the 560.70 driver.
MPC-Video Renderer retains smooth fine lines as you reduce the size of the window, in fact it's now better than Enhanced Video Renderer (custom presenter).
