### ISSUE TITLE
How do I use the MPC Video Renderer with xySubFilter

### ISSUE THREAD

**Issue by bLightZP** [Aleksoid1978/VideoRenderer#124]
Hi Team,
I am trying to integrate the MPC video renderer into Zoom Player, I was able to create the graph and everything is playing, but no subtitles are showing.

MadVR automatically connects with xySubFilter without requiring special code, is there a specific function I should call to enable the connection between xySubFilter and MPC-VR?

**Comment by v0lt** [comment]
You can also look at the [CXySubPicProvider](https://github.com/Aleksoid1978/MPC-BE/blob/master/src/SubPic/XySubPicProvider.h) and [CXySubPicQueueNoThread](CXySubPicQueueNoThread) classes. But I don't remember their purpose.

**Comment by bLightZP** [comment]
Any chance that MPC-VR can be modified to act as a complete standalone component like MadVR?
I don't have enough low-level experience to implement this interface.

**Comment by Aleksoid1978** [comment]
> Any chance that MPC-VR can be modified to act as a complete standalone component like MadVR? I don't have enough low-level experience to implement this interface.

Сочувствую))

**Comment by v0lt** [comment]
> Any chance that MPC-VR can be modified to act as a complete standalone component like MadVR?

There are no such plans.
What does "complete standalone component" even mean for a video renderer?

**Comment by bLightZP** [comment]
It means that it can be used without having to write special code on the player side (like MadVR). My expertise is in UI/UX, I would gladly give you lifetime licenses to Zoom Player (not related to the video renderer integration), I would love to get your feedback in general.

**Comment by v0lt** [comment]
> It means that it can be used without having to write special code on the player side (like MadVR).

You can also use MPC Video Renderer without an additional special code using only the interfaces that Microsoft developed. But you cannot use the D3D11 decoder. You cannot correctly convert colors for DolbyVision. You can’t connect the shaders. Part of the functionality is implemented in a decoder or in the player.
The subtitles about the same situation. If you think that you can do better, then we will see your patch. But I warn you right away, we will not mix D3D9 and D3D11.

**Comment by Aleksoid1978** [comment]
> It means that it can be used without having to write special code on the player side (like MadVR). My expertise is in UI/UX, I would gladly give you lifetime licenses to Zoom Player (not related to the video renderer integration), I would love to get your feedback in general.

We will be happy to receive a license for your product - it will be interesting to see what the “competitors” have :)

**Comment by v0lt** [comment]
mpc-be%mail.ru

**Comment by bLightZP** [comment]
v0lt:
I mailed you an activation serial, I'll be happy to read your opinion.

**Comment by v0lt** [comment]
Thank you. The letter has arrived, I will check the activation serial when I have free time.

**Comment by Chetan-Ullal** [comment]
I've made progress on this request: [https://github.com/Aleksoid1978/MPC-BE/pull/437](url)

**Comment by v0lt** [comment]
Test builds of [MPC Video Renderer (subpic)](https://disk.yandex.ru/d/c143r1VbCz1ILQ).

[Topic on Russian forum](https://mpc-be.org/forum/index.php?topic=774).
