### ISSUE TITLE
Unable to play mpeg-4 video type

### ISSUE THREAD

**Issue by molitar** [Aleksoid1978/VideoRenderer#125]
This video will not play at all in fact it skips the video completely as if it does not exist.

Complete name                            : Countdown Conjoined (2)\Yuuwaku Countdown - 1 [akuryou].mkv
Format                                   : Matroska
Format version                           : Version 1
File size                                : 313 MiB
Duration                                 : 30 min 23 s
Overall bit rate                         : 1 440 kb/s
Frame rate                               : 23.976 FPS
Encoded date                             : 2005-03-06 22:15:41 UTC
Writing application                      : mkvmerge v1.4.0 ('Cornflake Girl') built on Feb 26 2005 14:33:38
Writing library                          : libebml v0.7.3 + libmatroska v0.7.5
Attachments                              : Elected Office.ttf / KNIGHT.TTF / SAMBD___.TTF / tt0843m_.TTF / CARLETON.TTF / dorcla__.ttf / ARENAC.TTF / bajsmask.ttf / KRONEB.TTF

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L1
Format settings                          : BVOP1
Format settings, BVOP                    : 1
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : V_MS/VFW/FOURCC / XVID
Codec ID/Hint                            : XviD
Duration                                 : 30 min 23 s
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Writing library                          : FFmpeg0.4.9-pre1b4738
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format version                           : Version 4
Format settings                          : Explicit
Codec ID                                 : A_AAC/MPEG4/LC/SBR
Duration                                 : 30 min 23 s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Title                                    : Japanese (AAC)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Title                                    : English (ASS)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : English (SRT)
Language                                 : English
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 5
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Title                                    : Slovenian (ASS)
Language                                 : Slovenian
Default                                  : No
Forced                                   : No

**Comment by Aleksoid1978** [comment]
Upload file.

**Comment by Aleksoid1978** [comment]
This is not a question for the renderer, but for the player.
