### ISSUE TITLE
1280X720-->1280X720, super resolution status: also active

### ISSUE THREAD

**Issue by starmonker** [Aleksoid1978/VideoRenderer#126]
When the film has the same resolution and the image is not scaled, the super resolution is also active.

For example: 1280X720-->1280X720, 1920X1080-->1920X1080 super resolution status: active
MPC Video Renderer 0.7.2.2177 (git-2024.01.13-2bb0868) x64
551.23-desktop-win10-win11-64bit-international-dch-whql

**Comment by Aleksoid1978** [comment]
SuperRes always activated if selected in options.

**Comment by starmonker** [comment]
3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.

**Comment by v0lt** [comment]
> 3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.

Ask Nvidia why this happens on your video card.

**Comment by starmonker** [comment]
> > 3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.
> 
> Ask Nvidia why this happens on your video card.

POTPLAYER 1280x720->1280x720, 3840x1080->1920x1080，super resolution status: inactive

**Comment by starmonker** [comment]
> As mentioned in the NVIDIA RTX Video FAQ:
> 
> ```
> Q: What’s new with the RTX Video Super Resolution 1.5 update (Oct 2023)?
> - De-artifacts video played at native resolution (e.g. output resolution matches video source)
> ```

Almost zero improvement

**Comment by starmonker** [comment]
Add features: output resolution matches video source , Super Resolution disable?

**Comment by Aleksoid1978** [comment]
> > > 3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.
> > 
> > 
> > Ask Nvidia why this happens on your video card.
> 
> POTPLAYER 1280x720->1280x720, 3840x1080->1920x1080，super resolution status: inactive

Use Pot if it good for you :)

**Comment by starmonker** [comment]
> > > > 3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.
> > > 
> > > 
> > > Ask Nvidia why this happens on your video card.
> > 
> > 
> > POTPLAYER 1280x720->1280x720, 3840x1080->1920x1080，super resolution status: inactive
> 
> Use Pot if it good for you :)

1080i 30fps+double the frame rate when deinterlacing +super resolution lv4 +dxva ->1080 60fps@3840x1080 =GPU：>90%
4070ti

**Comment by Aleksoid1978** [comment]
> > > > > 3840x1080 monitor plays 1920x1080 videos without any improvement in image quality and also increases GPU consumption.
> > > > 
> > > > 
> > > > Ask Nvidia why this happens on your video card.
> > > 
> > > 
> > > POTPLAYER 1280x720->1280x720, 3840x1080->1920x1080，super resolution status: inactive
> > 
> > 
> > Use Pot if it good for you :)
> 
> 1080i 30fps+double the frame rate when deinterlacing +super resolution lv4 +dxva ->1080 60fps@3840x1080 =GPU：>90% 4070ti

???

**Comment by v0lt** [comment]
> Add features: output resolution matches video source , Super Resolution disable?

I remember a request that asked for the opposite. :-D
Therefore, we will not rush and wait. Perhaps Nvidia itself will add the functionality users need.

**Comment by Aleksoid1978** [comment]
There’s no need to do this, it will complicate the code too much, which is not simple anyway.
