### ISSUE TITLE
I don't see clip parameters such as Matrix coef.

### ISSUE THREAD

**Issue by radpopl** [Aleksoid1978/VideoRenderer#129]
I don't see clip parameters such as Matrix, etc. in the OSD menu.
Has anything changed in the new version?
I can't see it in both MPC-BE and MPC-HC.

**Comment by JTGaming** [comment]
working on my end. Show a screenshot of how your debug menu looks like.

**Comment by radpopl** [comment]
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/11005341/b1051eac-467a-4a8f-a74f-09d5ff1ad8bb)

**Comment by radpopl** [comment]
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/11005341/e78edc88-ff29-435d-9aaf-16a2412ae350)

**Comment by JTGaming** [comment]
does it work for other videos?

**Comment by radpopl** [comment]
Thanks for the info.

I switched to D3D11 and it actually shows everything correctly.
However, I use DXVA2 (native) because it is the only one that does not drop frames when bitrate spikes on my PC.

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/11005341/8cae1e5d-4262-4ada-a551-4483f7b2b9ae)
