### ISSUE TITLE
Feature Request - Add an "Always turn on" option to Windows HDR

### ISSUE THREAD

**Issue by Fr0stX76** [Aleksoid1978/VideoRenderer#131]
Hi, I started using the dev build added 2 days ago to the nightly channel, and got RTX Video HDR working, alongside Super Res.

Very nice.

The thing is, in order to have RTX video HDR to trigger (unless I missed something and  if I did, please explain how this can be simplified), I need to:

1- Have a file format that is supported.
2- turn HDR on in Windows.
3- Change the Windows HDR option of MPC-VR to "do not change" or else it will turn Windows HDR off as the file is detected as SDR.

Again, maybe there is a better way, but from what I understand, step 1 is unavoidable, but if step 2 could happen in the background, by adding an option to step 3, it would be a lot simpler to use this feature.

So here is my request:

Would it be possible to add an "always turn on" option to the Windows HDR of the renderer? 

Or even better, having it to turn on for SDR files, but only the ones supported by RTX video HDR... I doubt this can be easily implemented, so having the "always turn on" option would be a good start.

Thanks!

**Comment by Aleksoid1978** [comment]
No.

**Comment by Fr0stX76** [comment]
> The current option already allows it to only turn on HDR when needed. That way it will never turn off HDR when enabled in Windows settings.
> 
> But if RTX HDR is enabled, then it should not switch to SDR. That could be a bug?

It doesn’t turn windows HDR on for SDR content even if the RTX video option is on when using "allow turn on/off". You have to manually turn windows HDR on in the display settings before opening the file which is extra steps for anyone that leave Windows HDR off when not using HDR content (as in my opinion it looks like crap on desktop).

And yes, if you use "allow turn on/off" it turns off windows HDR display option even with RTX video HDR option on in the renderer when it detects an SDR file.

Maybe I`m just misunderstanding the Windows HDR options of the renderer. I cannot find any combination that will allow me to --Use RTX video HDR on SDR files
-Passthrough HDR 
-Have HDR turn on and off as needed without leaving HDR on in display settings.

Anyway, no big deal, I thought I would ask.

**Comment by Fr0stX76** [comment]
"allow turn on" does indeed work, but damn, Windows desktop in HDR, even calibrated looks pretty awfull. More like half crap. So no thanks.

Oh well, ill settle for turning it on manually for whatever I really want it. It looks great when activated the way!

Topic closed.

**Comment by Aleksoid1978** [comment]
> The renderer should be able to turn it on for RTX HDR as well. So maybe that something that the devs can improve.
No you shouldn't. If you need HDR for SDR, turn it on manually in the system.
This is my attitude to this functionality, period.
