### ISSUE TITLE
Unable to speed up x5 the 4k VP9 video

### ISSUE THREAD

**Issue by Telezhka-the-First** [Aleksoid1978/VideoRenderer#133]
I noticed that if I use this video renderer in MPC-BE, any video with codec _vp09_ seems impossible to speed up: while time and audio successfully increase in speed, video plays as if it was at x1 speed, so audio outruns video. This doesn't happen with _h264_ and _h265_: they speed up as intended.

**Comment by Aleksoid1978** [comment]
What player use ?

The video renderer has nothing to do with changing the playback speed.
I checked in MPC-BE - everything is fine.

**Comment by v0lt** [comment]
This is a problem with your hardware that you didn't mention.

Also, if you press Ctrl+J, you will get additional information.

**Comment by Telezhka-the-First** [comment]
> What player use ?
> 
> The video renderer has nothing to do with changing the playback speed. I checked in MPC-BE - everything is fine.

Not sure what do you mean by player. I use MPC-BE with MPC Video Renderer & MPC Audio Renderer.

**Comment by Telezhka-the-First** [comment]
> Hardware decoder maybe too slow?

Maybe. VLC speeds up vp09 fine though. Maybe some option breaks vp09 in MPC-BE.

**Comment by Telezhka-the-First** [comment]
> This is a problem with your hardware that you didn't mention.
> 
> Also, if you press Ctrl+J, you will get additional information.

Thanks, that's test with x5 speed:
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/90337398/2d9b211d-6b74-4804-9fbc-8d3ffb6ddfa1)

**Comment by Aleksoid1978** [comment]
Frame rate 120, working.

**Comment by Telezhka-the-First** [comment]
It's not x5, i took this speed just to illustrate the problem. Usually this starts happening at about x1.7. What happens is that after some speed Sync offset is no longer dropping towards zero, but increases, increasing difference between audio and video. This means that this program reaches it's maximum framerate (bitrate?) for the video and can't process it any faster, while audio doesn't care and speeds up to any number.

**Comment by Telezhka-the-First** [comment]
Is it the only solution: to upgrade hardware? Can anything be done via program part?

**Comment by v0lt** [comment]
The hardware decoder has a decoding speed limit. This limit is different on different decoders. Also, part of the power is taken by the output to the screen.

In my measurements on an Intel UHD 750, the HEVC 8-bit decoder is faster than the VP9 8-bit decoder.
For fast operation of integrated graphics, fast RAM operating in dual-channel mode is required.

**Comment by Telezhka-the-First** [comment]
It would be better though, that if vp09 video can't reach desired speed it would lag and stutter rather than running video slower than needed. This way desync would be immediately noticable.
