### ISSUE TITLE
HDR-to-SDR conversion doesn't work with DmitriRender [DmitriRender bug]

### ISSUE THREAD

**Issue by Toff-kun** [Aleksoid1978/VideoRenderer#135]
Enabling DmitriRender makes MPCVR's HDR-to-SDR conversion stop working for some reason.

DmitriRender disabled:

![DmitriRender disabled](https://github.com/Aleksoid1978/VideoRenderer/assets/10385850/0e933ae8-265a-43f0-96d3-b258edd066a0)

DmitriRender enabled:

![DmitriRender enabled](https://github.com/Aleksoid1978/VideoRenderer/assets/10385850/5fe5d282-db98-4bd2-88d4-8be755a89da7)

 Is it possible to make it compatible somehow?
MadVR doesn't have this issue, so I assume it is MPCVR-related.

**Comment by v0lt** [comment]
Your DmitriRender corrupts the properties of the video frame.
See Matrix, Primaries, Functions.

> Is it possible to make it compatible somehow?

Contact DmitriRender support.

**Comment by Toff-kun** [comment]
Why doesn't it break HDR-to-SDR on MadVR then?

**Comment by v0lt** [comment]
> Why doesn't it break HDR-to-SDR on MadVR then?

I don't know. Perhaps madVR is doing something to bypass DmitriRender's incorrect behavior.
But this is a wrong position that encourages others to do wrong things. We won't do that.

**Comment by Toff-kun** [comment]
Forgive me if my question sounds ignorant, but could it be that MPCVR simply doesn't have any profile for the "D3D11_P010" input format and defaults to the generic SDR processing as a result? Maybe all that's needed is to apply the same profile / processing to D3D11_P010 as to the regular P010?

**Comment by v0lt** [comment]
> Forgive me if my question sounds ignorant, but could it be that MPCVR simply doesn't have any profile for the "D3D11_P010" input format and defaults to the generic SDR processing as a result?

You are not right. Open HEVC 10-bit with hardware decoding D3D11 (native) and you will see D3D11_P010.
