### ISSUE TITLE
Dithering and RTX HDR cannot work correctly on HEVC 10-bit file

### ISSUE THREAD

**Issue by raven02** [Aleksoid1978/VideoRenderer#136]
@v0lt dithering and RTX HDR cannot work correctly on HEVC 10-bit file (HEVC 8 bit file is ok) with 0.7.3.2210 or 0.8.0.2215

**Comment by Aleksoid1978** [comment]
RTX HDR work only for 8-bit video.

**Comment by raven02** [comment]
@Aleksoid1978 Would it be able to support in the future?

**Comment by Aleksoid1978** [comment]
> @Aleksoid1978 much appreciated if can support in the future.

Not planned, maybe in feature.
