### ISSUE TITLE
CLI to transcode SDR to RTX HDR?

### ISSUE THREAD

**Issue by alexandergunnarson** [Aleksoid1978/VideoRenderer#138]
Hey! This repo of yours is pretty much the only place I’ve seen the RTX HDR driver API being used directly. (At least I think it’s being used here, per [this commit](https://github.com/Aleksoid1978/VideoRenderer/commit/b9f82f315b30c5e30a0fd47f2ef7b1e0d65ad3f2).) I’m looking for a CLI tool that takes an SDR video and outputs a video upmapped to HDR via RTX HDR. Is such a CLI tool available in this repo? If not, is there some C++ API in your repo that I can hook into? I’m trying to automate the upmapping on a cloud instance.

Note that there’s a [related discussion](https://github.com/libvips/libvips/discussions/3907) on on the Vips repo about this.

Thanks so much! This kind of thing would be incredibly useful for a large subset of people I think.

**Comment by v0lt** [comment]
To understand how this works, see commit 6f0329a.
You can also look at [the implementation in Chromium](https://chromium.googlesource.com/chromium/src/+/master/ui/gl/swap_chain_presenter.cc).

There will be no console utility here.

**Comment by alexandergunnarson** [comment]
Thanks for your fast feedback!
