### ISSUE TITLE
MPC Video Renderer 0.8.0.2218 

### ISSUE THREAD

**Issue by starmonker** [Aleksoid1978/VideoRenderer#139]
MPC Video Renderer 0.8.0.2218 potplayer cannot be used。
pot:240315(1.7.22129)

**Comment by Aleksoid1978** [comment]
Well, write to the author of Pot - let him look at his code, what and where does not work for him.
Everything works fine in MPC-BE and MPC-HC.

**Comment by v0lt** [comment]
Use [official release builds](https://github.com/Aleksoid1978/VideoRenderer/releases) that suit you.

You can also read the [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt).
