### ISSUE TITLE
HDR material overbright on SDR monitor

### ISSUE THREAD

**Issue by raven02** [Aleksoid1978/VideoRenderer#142]
@v0lt Tested with HDR material (2160p with PQ) on SDR minitor, it rendered to be overbright with passthrough display ON . 

Picture 2 should the correct rendering . Wonder if I have wrong setting leading to this.

With  passthrough to display ON

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/3000282/397719cf-7d5a-4ba4-8293-5674ae4703f2)

With passthrough to display OFF

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/3000282/e0f01cac-5dcc-4823-b11c-d2afc8bcebe4)

Setting 

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/3000282/93960083-7628-4278-b027-d17a2af73a17)

**Comment by v0lt** [comment]
> Tested with HDR material (2160p with PQ) on SDR minitor, it rendered to be overbright with passthrough display ON .

It shouldn't be like this. It makes no sense to do an HDR passthrough for an SDR display.

**Comment by raven02** [comment]
Since I want to use RTX HDR for non-HDR material so I always set passthrough display ON. Is it possible to have passthroug to display off automatically when detect HDR material and convert to SDR .

**Comment by v0lt** [comment]
You write some incomprehensible things. No, it is Immpossible.
