### ISSUE TITLE
There is no option to enable Super Resolution for all video resolutions in 0.7.3.2210

### ISSUE THREAD

**Issue by neverabyss** [Aleksoid1978/VideoRenderer#144]
Version 0.7.3.2210 only allows super resolution for video ≤FullHD, but Nvdia VSR supports at least QHD to QHD and QHD to UHD. This works for QHD video in 0.7.1.2172 but does't work in 0.7.3.2210 due to the lack of an option to enable Super Resolution for all video resolutions or a least for ≤QHD.

**Comment by v0lt** [comment]
Have you seen the positive effects of upscaling 1440p to 2160p yourself?

**Comment by NBruderman** [comment]
> Have you seen the positive effects of upscaling 1440p to 2160p yourself?

I mean, if Nvidia supports it, why not leaving the decision to the user whether to use it or not?

**Comment by v0lt** [comment]
Firstly, you can’t believe everything on the Internet (there have already been precedents). And we won’t make a feature that doesn’t work, because the next “Issue” will be “the new feature doesn’t work.”
Secondly, this makes no sense. I doubt there will be any improvement when upping 1440p to 2160p.

**Comment by neverabyss** [comment]
> Have you seen the positive effects of upscaling 1440p to 2160p yourself?

Yes, I see a positive effect from this scaling, it suppresses compression artifacts and the edges become smoother and sharper. Here are some examples:

2560x1440 -> 3840x2160 
<img width="1920" alt="frame1" src="https://github.com/Aleksoid1978/VideoRenderer/assets/166257797/0467c7fa-c48e-4100-9aa2-25f60961edba">

2560x1440 -> 3840x2160 + Super Resolution
<img width="1920" alt="frame1+vsr" src="https://github.com/Aleksoid1978/VideoRenderer/assets/166257797/7c405fd7-f671-4363-94ef-6e0b15b0bd31">

2560x1080 (QHD width) -> 3840x1620
<img width="1920" alt="frame2" src="https://github.com/Aleksoid1978/VideoRenderer/assets/166257797/cf7d43ac-43bb-401c-8fa4-cff3635a7bd9">

2560x1080 (QHD width) -> 3840x1620 + Super Resolution
<img width="1920" alt="frame2+vsr" src="https://github.com/Aleksoid1978/VideoRenderer/assets/166257797/c56316cb-4095-4437-95b8-c7697c4372d4">

**Comment by v0lt** [comment]
Super Resolution support for 1440p has been added in commit a9fadf9.

**Comment by neverabyss** [comment]
> Super Resolution support for 1440p has been added in commit [a9fadf9](https://github.com/Aleksoid1978/VideoRenderer/commit/a9fadf9500201ef5c27a11edb1bc69c6d747c6b3).

Thank you.
