### ISSUE TITLE
rtx super resolution causes washed out video

### ISSUE THREAD

**Issue by RichardLuo0** [Aleksoid1978/VideoRenderer#146]
It looks like a grayscale filter. sry I can't take screenshot because once I pause the video or move mouse to the slider, the filter like effect is gone. 
The only solution is to turn off rtx vsr in settings.

Some info you may be interested:
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/22096448/e2bc19d1-6e74-49f2-b82c-306e0f78c291)

**Comment by v0lt** [comment]
Check it out in the Chrome browser.

**Comment by RichardLuo0** [comment]
> Check it out in the Chrome browser.

In Chrome browser, it looks perfect, no washed out or anything. If I check the nvidia panel, the super resolution and rtx hdr is working.
And it seems its not only vsr. If I enable rtx hdr only, the same problem occurs. But if I have both of them disabled or disable all options under "use for", the problem is gone. 

I finally got a picture of the problem:
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/22096448/6ab32ccc-3f64-4a3e-8be6-604ce0a303d9)
washed out
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/22096448/3f5140c0-f666-489f-b386-5b4ee12b36f5)
normal

**Comment by RichardLuo0** [comment]
> Check it out in the Chrome browser.

I think I figured it out. It was nvidia app. I shouldn't turn on rtx hdr there. It seems that option will do a second processing which conflicts with the renderer.

**Comment by RichardLuo0** [comment]
hi, it happens again. As long as I set the window to maximum or fullscreen, the washed-out effect will appear. And now it doesn't matter if I pause the video or move mouse to the slider, it is just there.

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/22096448/4474103b-9098-4511-a746-b966e80e1f69)

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/22096448/311dc21b-8e0c-49ef-b748-236c33d8b82a)

If I play in chrome as mp4 format, its looks fine.

**Comment by Aleksoid1978** [comment]
1 - On your screen - HDR Passthrough is not working.
2 - You use old version MPC VR.

**Comment by RichardLuo0** [comment]
1. ok but why its not working? It worked before (see my first screenshot, btw its a different video)
2. What do you mean by its old version? The latest release on GitHub is 0.7.3.2210

And none of them answers my question: why is there a washed-out effect with vsr?

**Comment by Aleksoid1978** [comment]
https://github.com/qwerttvv/Player/releases

**Comment by Aleksoid1978** [comment]
Washed-out - because it's convert to hdr but not pass through to display.
But - i can't reproduce, for me all working.

**Comment by RichardLuo0** [comment]
> https://github.com/qwerttvv/Player/releases

Should I use nightly builds?

**Comment by RichardLuo0** [comment]
> Washed-out - because it's convert to hdr but not pass through to display. But - i can't reproduce, for me all working.

I don't think it's related to hdr. Even if I turn off the RTX hdr, still same problem. It is fine if I make the mpc window smaller than the video, but the problem appears once it exceeds the size of the video.

**Comment by RichardLuo0** [comment]
> https://github.com/qwerttvv/Player/releases

Change the mpc-be version doesn't matter

**Comment by RichardLuo0** [comment]
I tried some other videos and it works fine, which is wired, Can you try https://thepiratebay.org/description.php?id=36632388 S03E01?

**Comment by Aleksoid1978** [comment]
As i see - it's working.
![изображение](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/36dcef76-a0f9-452c-8369-b983366f5b98)

**Comment by RichardLuo0** [comment]
It seems the issue has been fixed in 0.8. You should release it as soon as possible (Your latest release on github is 0.7.3.2210 in case you forget).
Btw, I am using a monitor with 0-255, do I need to enable 16-255 to 0-255 shader for this movie? But this shader makes the movie look way too dark.

**Comment by v0lt** [comment]
> You should release it as soon as possible

https://github.com/Aleksoid1978/VideoRenderer/wiki/Nightly-builds
use the builds from the link

**Comment by RichardLuo0** [comment]
With Windows Snipping Tool and any other screenshot tool, the screenshot looks oversaturated. With Xbox game bar, they look identical whether washed out or not.
After some digging, I found this: https://codecs.forumotion.net/t3979-hdr-not-rendered-correctly-at-fullscreen

<blockquote>
Windowed mode

- Normally when you toggle to full screen mode, you are seeing an incorrect map of luminance values from your source HDR material (with different peak values between source and destination device), which is manifesting as "washed out" in full screen mode

- In windowed mode, Windows 10 is doing an approximate map of the peak nits values, aligned to your HDR device's peak nit value. However, in the case of an HDR1000 mastered movie (or higher) mapped to an HDR400 monitor, you'll notice the "bright" areas of the video are almost too bright, and it is clipping at the upper end of the luminance range.
- In full screen mode, madVR is passing the HDR info directly to your screen, including the meta data, without tone mapping of the luminance. In this example, HDR1000 content going to a HDR400 monitor, it causes it to look washed out, and not have proper peak luminance values.

- By using "tone map HDR using pixel shaders", you are fixing the issue in windowed and full screen mode by properly mapping the HDR1000 content luminance values to a narrower HDR400 luminance range (but still aligning peak values properly). Changing between "windowed full screen" vs "full screen" will now yield the correct result.
</blockquote>

Assuming he is correct, is there a similar thing as "tone map HDR using pixel shaders" in mpc-vr?

**Comment by RichardLuo0** [comment]
I think he means tone map HDR 1000 content to HDR 400 monitor, not HDR to SDR. And I forgot to mention that this also happens to native HDR videos.

**Comment by RichardLuo0** [comment]
I downloaded mad VR. If I choose passing through in mad VR, with a native HDR video, it has the same problem as mpc VR (except in mad VR colors become bright when resizing, and washed out a little at any other times). If I choose "tone map HDR using pixel shaders" with peak brightness 400, it is even more washed out! Though the color doesn't change anymore.

**Comment by RichardLuo0** [comment]
Basically mpc vr pass-through looks identical to madVR pass-through. And "tone map HDR using pixel shaders" is actually more washed out.
I guess it is because of monitor has its own tone mapping and pass-through leaves the work to the monitor (If not, then oversaturated).

**Comment by RichardLuo0** [comment]
But there is one thing that mad VR does better. It will keep passing through no matter what is over the video. However, in mpc vr simply pausing the video will cause color changing

**Comment by Yakumounr** [comment]
I have this issue with the latest MPC nightly (2.3.5.27) and the MPC-VR it bundles (0.8.6.2287).
If HDR display is enabled, as soon as the video is large enough for Nvidia VSR to kick in the colour gets very washed out, the only way to fix it seems to be either -

- Disable Nvidia VSR. Either in MPC-VR or the NV Control panel as both will disable it while playing back footage with MPC-VR. 
- Enable Nvidia RTX Video HDR. This can be done just in the in the MPC-VR settings if you wish,  the Nvidia Video HDR setting seems to override the NV control panel setting, unlike for VSR.

The latter quick 'fix' results in the AI processed Nvidia Video HDR colouring though, which may not be desirable for many.
I do not know if this is something MPC-VR could resolve or if it is an Nvidia VSR specific issue.
