### ISSUE TITLE
Green video with Direct3D11

### ISSUE THREAD

**Issue by Alhaitham** [Aleksoid1978/VideoRenderer#149]
Continued from here https://github.com/clsid2/mpc-hc/issues/2737#issuecomment-2054204275

Sample video

https://files.catbox.moe/faq3h5.avi
Or
https://mega.nz/file/hVpSDSRT#J2dKoOJCM-xrzTUGkI8Jw1wlALJQWr2sLpyPmSULi2E

With Direct3D11:

![Clipboard_04-13-2024_03](https://github.com/clsid2/mpc-hc/assets/7531458/9eeffae0-f301-453c-852b-68a8e7f9ff77)

Without Direct3D11:

![Clipboard_04-13-2024_04](https://github.com/clsid2/mpc-hc/assets/7531458/6cca8b7d-39c1-4469-a977-cfcd563a4f3c)

**Comment by Alhaitham** [comment]
Unfortunately not

**Comment by Aleksoid1978** [comment]
I can't reproduce - for all is good on D3D11, with VP or Shaders.

**Comment by Aleksoid1978** [comment]
And - i don't have **old Intel HD Graphics** for check/debug.

**Comment by Aleksoid1978** [comment]
Old graphic - use Direct3D9.

**Comment by Alhaitham** [comment]
If there is a way to provide you with debug info, will gladly provide it

If not then you can close it as it is not really a major issue because it only happens with capture videos

**Comment by v0lt** [comment]
Intel UHD 750 (i5-11500) has no problems with this video.
I remember there were no problems on the old Intel HD 4000 (i5-3570k) either.

Please take a screenshot of the first [GPU-Z](https://www.techpowerup.com/gpuz/) tab for your graphics adapter.

**Comment by v0lt** [comment]
> So it does not support shaders when using VP. Perhaps always check for this capability and if unavailable disable the D3D11 option?

In D3D11 mode, D3D_FEATURE_LEVEL_10_0 or later is supported. This is usually enough for MPC VR to work.

> Edit: And with VP disabled it shows this:
> CMpcVideoRenderer::CalcImageSize() buffer size changed from 640x480 to 1280x480
> That is wrong?

It depends on what texture format is used.

**Comment by Aleksoid1978** [comment]
> Why does size depend in texture format?

For fast copy GPU -> CPU. When destination pitch = source pitch - we have 1 call of memcpy(), see as example
https://github.com/Aleksoid1978/VideoRenderer/blob/master/Source/Helper.cpp#L367-L381

**Comment by Aleksoid1978** [comment]
Looks like D3D11 supported in driver is buggy.

**Comment by Aleksoid1978** [comment]
It's very strange, for 640 alignment size is 1280, but for 1280 - alignment size is 2560.
Check in debugger **CDX11VideoProcessor::GetAlignmentSize()**.

**Comment by Aleksoid1978** [comment]
> m_pInputPin->GetConnected()->QueryAccept(&mtNew)

If **m_pInputPin->GetConnected()->QueryAccept(&mtNew)** does not work, it’s okay, it means the higher-level filter did not accept the new media type and we will continue to work with the current one, there is no need to add anything here.

**Comment by Aleksoid1978** [comment]
Let's do it this way - the issue is closed, the developers don't have such old Intel.
Therefore, we stop writing here - if someone can find the reason, fix it, etc. - either a patch or a pull request.
The end :)

**Comment by v0lt** [comment]
> If there is a way to provide you with debug info, will gladly provide it

https://github.com/Aleksoid1978/VideoRenderer/releases
There you can find the Debug version.
Use [DebugView](https://learn.microsoft.com/ru-ru/sysinternals/downloads/debugview) to view the debug log.

**Comment by Alhaitham** [comment]
[mpc-hc64_capture_2024-04-13_14-33-40.LOG](https://github.com/Aleksoid1978/VideoRenderer/files/15005392/mpc-hc64_capture_2024-04-13_14-33-40.LOG)
