### ISSUE TITLE
wrong color when use d3d11 video processor in 10bit video

### ISSUE THREAD

**Issue by narcissussic** [Aleksoid1978/VideoRenderer#15]
![2020 06 23-16 30](https://user-images.githubusercontent.com/61244668/85390760-dbb68c00-b57b-11ea-8da8-d57011bad6d2.jpg)
![2020 06 23-16 31](https://user-images.githubusercontent.com/61244668/85390787-e3763080-b57b-11ea-97e8-d129936a3b52.jpg)
gpu: amd rx5700
player: MPC-BE.1.5.5.5350

**Comment by Aleksoid1978** [comment]
Don't have AMD, can't test. Maybe it's a video driver issue. It's happened on DX9 ?

**Comment by narcissussic** [comment]
> Don't have AMD, can't test. Maybe it's a video driver issue. It's happened on DX9 ?


![2020 06 23-19 52](https://user-images.githubusercontent.com/61244668/85400891-b6317e80-b58b-11ea-9b2f-09bbba598f46.jpg)
dx9 just output 8bit ？

**Comment by narcissussic** [comment]
> Don't have AMD, can't test. Maybe it's a video driver issue. It's happened on DX9 ?

update the driver and color get normal

**Comment by v0lt** [comment]
> update the driver and color get normal

What driver did you have and which one did you install?

**Comment by narcissussic** [comment]
> > update the driver and color get normal
> 
> What driver did you have and which one did you install?
> I have the same problem with driver 19.10.30.14. 

what I use before is 20.4.2 whql
only latest driver fix the problem, like Adrenalin 2020 Edition 20.5.1 Optional and Radeon™ Pro Software 20.Q2.1

**Comment by hooke007** [comment]
The similar problems.
Nvidia 2070s (460.89) 
strange colors when using D3d11
![madvr](https://user-images.githubusercontent.com/41094733/103099814-e517d280-464a-11eb-80a8-6c7fc5b26c13.jpg)
![mpcvr d3d9](https://user-images.githubusercontent.com/41094733/103099816-e812c300-464a-11eb-8584-64aec998278f.jpg)
![mpcvr d3d11](https://user-images.githubusercontent.com/41094733/103099818-e9dc8680-464a-11eb-9e08-49709885fe04.jpg)

**Comment by Aleksoid1978** [comment]
Try this settings:
![VR](https://user-images.githubusercontent.com/11625603/103116429-37400e80-46b2-11eb-9ac2-799c1346680e.png)

**Comment by hooke007** [comment]
> Try this settings:

Thank you for your suggestion, I just cancelled these options and the color seems to be recovered.
![Snipaste_2020-12-25_15-59-25](https://user-images.githubusercontent.com/41094733/103126860-a590cb00-46ca-11eb-8f65-55b90c1b7b92.jpg)

**Comment by Aleksoid1978** [comment]
Look like D3D11 VP issue.
