### ISSUE TITLE
Dolby Vision output improvement on HDR monitor

### ISSUE THREAD

**Issue by hebeguess** [Aleksoid1978/VideoRenderer#150]
Scenario: Dolby Vision Profile 5 video output to HDR monitor with always on HDR on Windows 11.

For example 'Convert to SDR' appears to be fine.
![Screenshot 2024-04-16 182251](https://github.com/Aleksoid1978/VideoRenderer/assets/5338670/f652f106-f0bb-4d88-aa49-c56dcfb7b227)

When activating 'Passthrough to display', contrast and brightness improved like it should with HDR.
I noticed the color primaries being convert for output is BT.709, wouldn't it be better if using BT.2020 in the case?

(I knew these two screenshots will result in same output scenario, it did. Decided to include both to avoid confusion.)
![Screenshot 2024-04-16 182458](https://github.com/Aleksoid1978/VideoRenderer/assets/5338670/059a03b0-d74c-43b0-9529-049d164d6aee) ![Screenshot 2024-04-16 182550](https://github.com/Aleksoid1978/VideoRenderer/assets/5338670/e87d1b9b-477a-4dcd-879a-789b33c17b8d)

Additionally, the 'Subtitle and OSD brightness' slider is not functioning in the specific case (DV profile 5 + passthrough to display).
It is OSD and subtitle is even brighter than playing both HDR and SDR content, adjusting it wouldn't do anything.

**Comment by Aleksoid1978** [comment]
**I noticed the color primaries being convert for output is BT.709, wouldn't it be better if using BT.2020 in the case?** - you are wrong. it's just info from input media type.

**Comment by hebeguess** [comment]
From my observation 'passthrough' DV video to HDR monitor has consistently result in noticeably lesser peak brightness and contrast in different type of scenes compared with HDR with static metadata. Guess this is the limitation of applying tone mapping  algorithm in such case as they all designed to squeeze color space from wide to narrow? DV to HDR doesn't need such a big squeeze.

When I play a profile 8.1 (DV+HDR) video with 'Prefer DV over PQ or HLG' to pass DV metadata to my monitor, the output closely match the result of DV profile 5 passthrough. In such case, having utilize DV metadata will not actually improving static HDR video instead just make it duller. Felt a little underwhelming.

**Comment by Aleksoid1978** [comment]
Мой Английский не на столько хорош, не понимаю :)

**Comment by Aleksoid1978** [comment]
Renderer use DV metadata for convert image to PQ. Metadata use or from original HDR, or standards.

Of course, you won’t be able to get the same bright and rich picture as when viewed on a TV with DV support.

This is mainly done to view profile 5 on windows.

**Comment by Aleksoid1978** [comment]
**Subtitle and OSD brightness slider** now working for DV too.
