### ISSUE TITLE
Cracking Noise, Audio stutter

### ISSUE THREAD

**Issue by h3llsp4wn88** [Aleksoid1978/VideoRenderer#151]
Hi there,

since 0.7.3.2210 I have cracking noise with HDR/DV playback. I'm on Windows 10, all drivers up to date. Currently reverted back to 1.6.11 as this comes with version 0.7.1 which is not causing any issues related to audio playback. I tried all kind of things ending up with the discovery that the renderer seems to be the issue. Using MadVR with MPC BE I don't have these kind of issues.

I have tried different combinations and ended up with reverting to 0.7.1. Tried already the 0.8. version and so on - all have the same issue.

Output is HDMI from an ATI RX 6400.

If you need more details or someone to do some testing I'm available. The renderer ist really first class work!

**Comment by Aleksoid1978** [comment]
Don't confirm, for me all good.
Enable statistics, ctrl + j and make screenshot.

**Comment by Aleksoid1978** [comment]
Show filters list in player.

**Comment by Aleksoid1978** [comment]
Show CPU/GPU load.

**Comment by h3llsp4wn88** [comment]
Thank you for pointing me into the right direction. I've swapped CPU for a faster one - issue resolved. Although CPU load was low I guess it somehow was related to the number of cores and processing.

Cheers,

h3ll
