### ISSUE TITLE
Can't get RTX Super Resolution to activate or work?

### ISSUE THREAD

**Issue by Usulyre** [Aleksoid1978/VideoRenderer#152]
Hi, I have a desktop RTX 3060m gpu and I am unable to get rtx super resolution to work with MPC Video Renderer 0.7.3.2210
in MPC-BE latest version 1.7.0 or the previous version.

Using portable versions I am of mpc-be x64

I have nvidia driver 552.22 DCH

Monitor is Acer XFA240 resolution is DSR 2560x1440 on hdmi at 120hz

RTX Super Resolution is checked and set at auto but not working and INACTIVE

No HDR 10 display available

I tried to use combinations of lav filters and ffdshow but not working ffdshow is outputting NV12.

I have tried various types of video files and they are sd or hd various sizes. I can't even get microsoft edge browser youtube videos to work either.

Please see screenshots to see if I need to enable or disable anything thanks in advance.

![2024-05-02 11_14_23-New Issue · emoose_VideoRenderer - Profile 1 - Microsoft​ Edge](https://github.com/Aleksoid1978/VideoRenderer/assets/16013427/10aaa15f-e74c-4dec-9d69-c7c13ce18e06)
![2024-05-02 11_16_21-New Issue · emoose_VideoRenderer - Profile 1 - Microsoft​ Edge](https://github.com/Aleksoid1978/VideoRenderer/assets/16013427/9e4952c3-177f-4781-aad1-4c87a265f757)
![2024-05-02 11_16_39-New Issue · emoose_VideoRenderer - Profile 1 - Microsoft​ Edge](https://github.com/Aleksoid1978/VideoRenderer/assets/16013427/09976002-174d-415b-bf4c-a45316939a0f)

**Comment by Aleksoid1978** [comment]
Activate in driver ?

**Comment by Usulyre** [comment]
it is i think

**Comment by Usulyre** [comment]
![2024-05-02 14_12_16-Can't get RTX Super Resolution to activate or work_ · Issue #152 · Aleksoid1978_](https://github.com/Aleksoid1978/VideoRenderer/assets/16013427/42868da4-9818-4012-a58e-ffff8a92fd27)

**Comment by Usulyre** [comment]
> Update the renderer. Disable RTX HDR. Uncheck AYUV.

Don't i have the latest version?

**Comment by NBruderman** [comment]
> > Update the renderer. Disable RTX HDR. Uncheck AYUV.
> 
> Don't i have the latest version?

No, the latest nightly is 0.8.0.2229,
You can find it  [here](https://github.com/qwerttvv/Player/releases)

**Comment by Aleksoid1978** [comment]
All fine is working:
![изображение](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/fe9ff116-32c0-4433-a154-55695295f708)

I can’t say anything about how it works or doesn't work in conjunction with ffdshow (this is already a very outdated filter, I don’t even want to check it).

**Comment by Usulyre** [comment]
Doesn't work for me even if I disable ffdshow as well. Tried the nightly build, not working for me either.

**Comment by Usulyre** [comment]
> All fine is working: ![изображение](https://private-user-images.githubusercontent.com/11625603/327607342-fe9ff116-32c0-4433-a154-55695295f708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTI0MjIsIm5iZiI6MTcxNDY5MjEyMiwicGF0aCI6Ii8xMTYyNTYwMy8zMjc2MDczNDItZmU5ZmYxMTYtMzJjMC00NDMzLWExNTQtNTU2OTUyOTVmNzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDIzMjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNjIyNTdmYjBmMjZiMTI0YmRmODQxYjMyODU5NjQ3YjAyM2ZhZGExOWE2ODRmNjRkMGVjYzA3ZDQ2YzA2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujhe7XygAFcQqeyPJ3cQ1ZgWeXfN73Rlg5XmDJ6HPws)
> 
> I can’t say anything about how it works or doesn't work in conjunction with ffdshow (this is already a very outdated filter, I don’t even want to check it).

Doesn't work for me even if I disable ffdshow as well. Tried the nightly build, not working for me either.

**Comment by Aleksoid1978** [comment]
It works for me and others (screenshot with proof above), so I can't help anyway.

**Comment by Aleksoid1978** [comment]
Set "Texture format" to "Auto ...".
Why set to 10-bit ?

**Comment by Usulyre** [comment]
Yes I switched it to auto but has made no difference

**Comment by Aleksoid1978** [comment]
Well, I don't know how to help, it works for me and other users.

**Comment by Aleksoid1978** [comment]
If you say that it's also don't working in Edge browser - it's something with you system/video/drivers ...

**Comment by Usulyre** [comment]
> If you say that it's also don't working in Edge browser - it's something with you system/video/drivers ...
> 
> P.S. Maybe it's don't work on mobile device.

I don't know about others, but if you have nvidia dsr on and using one of those resolutions, rtx super resolution doesn't work. 

I had to use the standard resolution of my monitor.

also, I had to switch my setting of video frame from "normal" to touch window from inside" in order for mpc-be to resize it.

Is that normal?

**Comment by Usulyre** [comment]
> You should never ever use DSR for anything other than games. Do NOT use it for media player and browsers.
> 
> "touch window from inside" is the default and correct setting. Anything else is for special use cases, which you should not use.

I have dsr on to get a 2560x1440 resolution on my 1080p monitor to see more on the desktop.

I used "normal" setting so that the videos are displayed at their actual resolution.
