### ISSUE TITLE
Deinterlace Picture Quality is not good (AMD Radeon 760M)

### ISSUE THREAD

**Issue by vdrfan** [Aleksoid1978/VideoRenderer#153]
hi, 
how can we see which Deinterlace Method is used.
Properties Screen show only all available: DeinterlaceTech.: Bob, Adaptive, Motion Compensation, Inverse Telecine 
is it posible to force a method?
thanks, onur

**Comment by v0lt** [comment]
> how can we see which Deinterlace Method is used.

There is no such possibility.

> Properties Screen show only all available: DeinterlaceTech.: Bob, Adaptive, Motion Compensation, Inverse Telecine
is it posible to force a method?

There is no such possibility. This is just a list of what the selected video processor can do.

**Comment by vdrfan** [comment]
i get much better result with software deint. (LAV + Yadif) - but i would prefer MPC Decoder + MPCVR + HW Deinterl.
is there a option in AMD Driver Settings to Force a better Deinterlacing Method.

**Comment by Klaus1189** [comment]
What GPU do you use?

**Comment by v0lt** [comment]
https://github.com/Aleksoid1978/VideoRenderer/wiki/Known-Issues

>     Deinterlacing does not work correctly on some AMD graphics adapters.
> 
> Reason: Some AMD graphics adapters require Future Frames for the D3D11 video processor. Currently MPC Video Renderer does not support Future Frames.

**Comment by vdrfan** [comment]
i use IGPU AMD Ryzen 5 8600G - Radeon 760M, 
old Vega IGPU(3400G) is working better.
is there a plan to supprt Future Frames.

**Comment by Aleksoid1978** [comment]
Can you check in other D3D11 video renderers, like in system media player Movies & TV or Kodi, mpv ?

**Comment by vdrfan** [comment]
@Aleksoid1978 - mvp is terrible even with intel. vlc is ok, MPC-BR with MAD is ok.

i have found following problem:
Video Decoder(LAV and MPC tested) cannot use Hardware Accelaration(DXVA2 or D3D11) on AMD(Radeon 760M tested) with certain SD MPEG2 Videos.
MPC Video Decoder shows: output format: NV12 - should show D3D11
on Intel System everything is working: output format: D3D11
whit MADVR Picture Quality is OK(AMD and Intel) (?? maybe MAD uses Internal SW Deint. when DXVA2 is not active ??)

testfile: .ts with 50MB
https://drive.google.com/file/d/1F_16sZUQodwP8IZAY_nPonYt37J0TJt9/view?usp=drive_link

**Comment by vdrfan** [comment]
comparison  amd - intel
![intel](https://github.com/Aleksoid1978/VideoRenderer/assets/13224045/ff72ac47-8566-4972-aaba-b86953ed7dc2)

![AMD](https://github.com/Aleksoid1978/VideoRenderer/assets/13224045/888c2d98-2e36-42a8-89ae-7ed39b7b02c7)

**Comment by vdrfan** [comment]
@clsid2, yes i know - that was a reason for me to switch to MPC-VR, but Madvr and LAV can play the video optical perfect.

**Comment by vdrfan** [comment]
@clsid2 
i think deinterlace is working but it looks bad (regardless d3d9 or d3d11).
i think - main problem is that video decoder is not useing hwaccel on some SD mpeg2 videos.
can somebody can check testvideo with AMD rdna graphics.

**Comment by v0lt** [comment]
https://disk.yandex.ru/d/LKPmtavOINaE6w
These are test builds for testing. In this form, changes are not included in official releases, because video frames in these builds are output 1-2 frames late.

No one has been able to implement a correct solution for MPC VR. Therefore, there are no plans for any specific time.

**Comment by vdrfan** [comment]
thanks V0lt, this build is working. Picture Quaity is much better.
is there source code available of this build. 
master branch from Aleksoid1978 does not have that changes - for Future Frames.
1-2 frames lateness is no problem for me.

**Comment by v0lt** [comment]
> master branch from Aleksoid1978 does not have that changes - for Future Frames.

4.5 years [it's been there.](https://github.com/Aleksoid1978/VideoRenderer/commit/a3fa3ddf82fd30fb61b3aee59b919313b7f74404)

**Comment by v0lt** [comment]
> Since it is currently disabled, is there a known problem with it?

It was always disabled. And in this state there were no problems. The problem was recently discovered on some modern AMD graphics adapters.
If we enable future frame support incorrectly, we will end up with a 1-2 frame delay (and some problems at the beginning of playback) on all graphics adapters.

> A possible optimization could be to use past/future frames only for interlaced content. Or are past frames needed for normal progressive content?

Most videos are marked as "possibly interlaced". Frame type marking for each frame occurs in the video decoder. Therefore, in most cases, we create a video processor that supports deinterlacing technologies, even for progressive video.

**Comment by vdrfan** [comment]
my suggestion
make a interface where the decoder or player can activate Future Frames.

**Comment by Aleksoid1978** [comment]
No.

**Comment by v0lt** [comment]
> You know when video is interlaced based on mediatype flags. You can only activate it in that case.

As I said, MPC Video Decoder and Microsoft DTV-DVD Video Decoder create an interlaced media type for most video (including progressive).

> Also, future frames can probably be maximized to 1 frame.

This value varies from 0 to 2 for different graphics adapters. I don't have an AMD graphics adapter with this problem to check the different values. On my Nvidia, AMD and Intel graphics cards, deinterlacing works well without future frames.

**Comment by vdrfan** [comment]
whith active Future Frames - do we need to delay Audio to be sync?

**Comment by Aleksoid1978** [comment]
If you want improvements in this direction, provide the developers with the appropriate equipment. After this there may be some changes.
For now, stop writing here, topic is closed.

**Comment by v0lt** [comment]
[MpcVideoRenderer 0.9.10.2417+](https://github.com/Aleksoid1978/VideoRenderer/wiki/Nightly-builds)
Added "Deinterlacing" setting.
Set the value to "HACK future frames" and check the result.

**Comment by vdrfan** [comment]
thanks, for that.
