### ISSUE TITLE
HDR passthrough issues on Windows 11

### ISSUE THREAD

**Issue by fkoemep** [Aleksoid1978/VideoRenderer#154]
I have a Samsung Galaxy Book 3 that is able to passthrough HDR metadata to its screen, but so far I've been able to do it well with Windows Media Player. Whenever I try to play the same videos with MPC-BE using MPC Video Renderer, the colors look wrong, like with too much brightness.

Windows 11 reports the setting "HDR video streaming" as "Supported", but "Use HDR" is reported as "Not Supported" if it helps.

**Comment by Aleksoid1978** [comment]
Can you enable HDR on the system? If not, then your screen does not support HDR and MPC VR will convert it to SDR.
Enable statistics (Ctrl + J) in MPC VR and take a screenshot.

**Comment by fkoemep** [comment]
I am unable to enable HDR on the system, but like I said before my laptop supports HDR video streaming so this should be supported. Maybe it's a special Windows API that the renderer is not using but Windows Media Player does so I get HDR there?

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/1898ea62-fd1d-4559-a719-a8b21e08f0b9)

I don't have the laptop with me right now but I'm going to try to get a screenshot for you next week.

**Comment by fkoemep** [comment]
I see, I couldn't find any docs regarding the streaming HDR content. 

The "convert to SDR" option is enabled but it still shows a picture that's way too bright, unfortunately I can't share any screenshots or any more useful information until next week.

**Comment by fkoemep** [comment]
Finally got the time to test again on that laptop. Turns out the passthrough is actually working, this happens even if I disable the HDR video streaming setting on Windows.

I've also tried playing with the HDR calibration but the image doesn't seem to be affected at all, the only thing that "works" is disabling "Passthrough to display" in MPC Video Renderer.

Any idea how this could be fixed?

![Sin título](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/9a19e57d-7f15-48b8-a6a3-0af140d623b8)
![Video2](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/37c629bc-a7f0-449a-b171-0d319ddbb71f)

**Comment by fkoemep** [comment]
@Aleksoid1978 @clsid2 any idea about what may be going on?

**Comment by fkoemep** [comment]
Both files look perfectly fine when played from Windows Media Player (https://apps.microsoft.com/detail/9wzdncrfj3pt?hl=en-us&gl=US) and also when I play them on a fully compatible HDR TV with my personal laptop.

The first file is from https://mega.nz/file/aOIj3RgY#9YSI8ik27dsdUv0xE0eZ-GvVnemJ3cgzbDVd7ga_vjc
The last file is from https://drive.google.com/file/d/1Ic9DZXMSo07EJMqCFaQRKSSrSw6y1mYv/view

Both files were taken from Kodi's samples https://kodi.wiki/view/Samples

**Comment by Aleksoid1978** [comment]
Windows Media Player can do HDR passthrough ?

**Comment by fkoemep** [comment]
The video looks super good, so I'm assuming it does

This weekend I'm going to try uploading some screenshots comparing Windows Media Player vs MPC-BE with passthrough dissabled!

**Comment by Aleksoid1978** [comment]
Your monitor is 8 bit and possible HDR is bad - off HDR in windows, off HDR passthrough in MPC VR.

**Comment by Aleksoid1978** [comment]
Yes i know about this sample. But - parameters is not 0.
I don't know how validate it :)

**Comment by Aleksoid1978** [comment]
Add simple HDR metadata validate.

**Comment by Aleksoid1978** [comment]
> The check you just added only checks if values are non-zero. The mediainfo example above passes that check.
Check first and then write :)

**Comment by fkoemep** [comment]
Back again with some new tests, hope it helps.

---
# Camp by Sony (from Kodi's samples I mentioned before):

## MPC-BE, HDR passthrough disabled
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/a8d6fd7a-8537-4288-abbe-788394eb12ee)

## MPC-BE, HDR passthrough enabled
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/e9692187-6579-4bfe-8d46-49b42df7d13a)

## Windows Media Player
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/92f485b1-6074-4183-8cc7-082e2de71a3e)

---
# Samsung HDR Wonderland (from https://4kmedia.org/ultra-hd-hdr-samsung-4k-demo-wonderland/)
## MPC-BE, HDR passthrough disabled
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/f0d6552b-6204-499a-b36c-e8f1aeb84314)

## MPC-BE, HDR passthrough enabled
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/ee600a51-a558-41be-a408-4ffd91bed0e2)

## Windows Media Player
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/32828909/8a27617c-9769-44f8-b7ea-ad7e7f1d4d64)

**Comment by Aleksoid1978** [comment]
On you monitor HDR passthrough is broken, don't use it.
Windows Media Player just output in SDR.

**Comment by Aleksoid1978** [comment]
I don't know why your monitor "say" that it's support HDR:)

**Comment by Aleksoid1978** [comment]
For HDR work - must be 10-bit output selected in graphics driver. On 8-bit - HDR mode is not enabled, you can check it in Windows settings.

**Comment by Aleksoid1978** [comment]
Show HDR settings in Windows. Try enabled HDR mode and then check in player again with HDR passthrough.

**Comment by fkoemep** [comment]
Like I said on this comment https://github.com/Aleksoid1978/VideoRenderer/issues/154#issuecomment-2106371450, HDR is only enabled for video streaming and should work fine for videos AFAIK.

One weird thing I noticed is that when I disabled HDR passthrough on MPC Video Renderer, the screen flashed and went black for a second after starting the video and after closing the player.

Another weird thing is that the areas under the OSD seem to look ok when HDR passthough is enabled 🤔

**Comment by Aleksoid1978** [comment]
Issue is closed, stop write here.
