### ISSUE TITLE
Cannot use it Potplayer after 0.8.1.2230 update

### ISSUE THREAD

**Issue by peter0612** [Aleksoid1978/VideoRenderer#157]
Hi, I cannot use it in potplayer after 0.8.1.2230 update, I was doing fine for 0.7.3.2210 version.

1. I replaced 0.8.1.2230 files, then cannot use it in potplayer, potplayer changed to use build-in dx9 render automatically
2. I replaced back 0.7.3.2210 and can use it

What is the problems?

**Comment by Aleksoid1978** [comment]
Ask the author of Pot - how can I know.

**Comment by rampageX** [comment]
You must update Potplayer to 1.7.22163 (240418), then MPCVR 0.8.1.2230 work fine.
