### ISSUE TITLE
Unexpected channel shifting 

### ISSUE THREAD

**Issue by atrukhin** [Aleksoid1978/VideoRenderer#158]
Hi devs, seeing the following issue with some movies

Sample: https://disk.yandex.ru/i/jtBikjNjLEG27w

It looks fine with web player
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/69a07201-9ba6-4d86-bc84-caaea1fd2ff1)

But in mpc-be with mpcvr it looks like some channel(s) are shifted (with vertical flip?) resulting in corrupted colors at the top
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/d37b26b0-afdf-4043-9bd1-2926e0f19c58)

Using all latest mpc-be 1.7.1 and mpc-vr 0.8.1.2230 with SW decoding

Settings are:
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/9ab1732c-e39d-44d4-9bd5-26539c9cf175)

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/96f3c078-e0b4-4d48-ae21-64f0c64421d6)

**Comment by Aleksoid1978** [comment]
All is good for me.
![изображение](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/3f23acb4-43c1-4c09-9b05-49937e7d53e5)

**Comment by Aleksoid1978** [comment]
Input format is different, it's strange.
Must be as on my screenshot.

**Comment by v0lt** [comment]
Try turning off Request Super Resolution.
Try turning off RXT Video HDR.
Try turning off NV12.

**Comment by atrukhin** [comment]
after digging more into this issue it turns out to be MPC video decoder issue not renderer:

- disabled NV12 but shifting still happens and even more noticable

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/e8690073-5e87-4147-bfc3-9847666537fb)

- then disabled YV12 as well and it disappears

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/1423651a-0ccb-455f-b357-e2be9d5235ba)

so if you still want to investigate/fix it i can reopen it in respective repo

**Comment by v0lt** [comment]
I didn't write anything about video decoder settings.
We are discussing MPC Video Renderer. Right?
![mpcvr_options](https://github.com/Aleksoid1978/VideoRenderer/assets/2035946/2d39a92c-ea1c-4d17-ade0-813086999f4d)

**Comment by atrukhin** [comment]
unfortunately tweaking renderer settings do not help
i only could resolve it by disabling NV12/YV12 in decoder settings

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/73a1361a-4d4a-4921-bb69-29af5756b713)

**Comment by v0lt** [comment]
The difference is in the "Input Format" line. No frame cropping to 464x348.
The external filter may be interfering.

Here is the list of my external filters (Play > Filters > Copy filter list to clipboard):
```
MPC-BE x64 1.7.1.2 dev
Filters currently loaded:
  - MPC Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - MPC Video Decoder
  - MPC Audio Decoder
  - MPC FLV Source
```

**Comment by atrukhin** [comment]
mine are:

MPC-BE x64 1.7.1
Filters currently loaded:
  - MPC Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - VapourSynth Filter
  - MPC Audio Decoder
  - MPC Video Decoder
  - MPC FLV Source

I disabled VapourSynth Filter and it helped without any other settings tuned (enabled back everything disabled before in rendered/decoder)

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/9236192e-ce50-4b33-adc2-e559de45c780)

so if it looks like VapourSynth Filter issue and nothing to investigate/fix in mpc decoder/renderer please close this one

and i will submit it to their repo

**Comment by v0lt** [comment]
MPC FLV Source reports that the frame is 464x352, which needs to be cropped to 464x348. Your VapourSynth Filter loses its cropping information and ends up with a color band.

LAV Splitter Source immediately reports that the frame is 464x348. Why there is such a difference in source filters is still unclear to me.

**Comment by atrukhin** [comment]
i replaced MPC FLV Source with LAV Splitter source and it also helps - i could keep VapourSynth enabled and no banding seen

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/139537778/fd4dbd3b-4f83-4c5f-9a73-0ddb655bcdee)
