### ISSUE TITLE
 green line appears when use d3d11 Decoder

### ISSUE THREAD

**Issue by narcissussic** [Aleksoid1978/VideoRenderer#16]
same as https://github.com/Aleksoid1978/VideoRenderer/issues/7
![2020 07 04-08 35](https://user-images.githubusercontent.com/61244668/86502366-fdfaa600-bdd4-11ea-9218-b057799e3bcc.jpg)
![2020 07 04-08 37](https://user-images.githubusercontent.com/61244668/86502370-0357f080-bdd5-11ea-9b3b-ca7c7448e369.jpg)
mediainfo of these videos
[mediainfo.txt](https://github.com/Aleksoid1978/VideoRenderer/files/4871947/mediainfo.txt)
gpu：rx5700
driver：20.5.1
video player：mpc be+lav+mpcvr
it seems like a amd only bug， normal test with intel igpu

**Comment by Aleksoid1978** [comment]
Developers don’t have such device and can’t test.

**Comment by Klaus1189** [comment]
I had same issue with older version, but devs fixed it here:
https://github.com/Aleksoid1978/VideoRenderer/commit/fd7b6248d9d37e37b1c62245922c9af45c3becf8

Can you please upload sample file, I have RX 5700 XT

I tested with many files, but I can not reproduce.

**Comment by v0lt** [comment]
@**narcissussic**
Please upload a small sample for your video.

**Comment by narcissussic** [comment]
> @**narcissussic**
> Please upload a small sample for your video.

[Seven.Samurai.1954.zip](https://github.com/Aleksoid1978/VideoRenderer/files/4903117/Seven.Samurai.1954.zip)

**Comment by narcissussic** [comment]
> I had same issue with older version, but devs fixed it here:
> [fd7b624](https://github.com/Aleksoid1978/VideoRenderer/commit/fd7b6248d9d37e37b1c62245922c9af45c3becf8)
> 
> Can you please upload sample file, I have RX 5700 XT
> 
> I tested with many files, but I can not reproduce.

upload the file

**Comment by Klaus1189** [comment]
I downloaded the file and can confirm that there is a vertical green line at the right when using MPC-BE 1.5.5 build 5383 with MPC-VR 0.4.8.1419 and LAV Filters 0.74.1.64 using D3D11 Video Processor in LAV Video Configuration.

What is quite rare is that the file is 4:3 and also HEVC in combination

**Comment by Aleksoid1978** [comment]
What's about madVR ?

**Comment by Aleksoid1978** [comment]
Try this - https://yadi.sk/d/XAeWvqxQro_vpw

**Comment by narcissussic** [comment]
> Try this - https://yadi.sk/d/XAeWvqxQro_vpw

work well,no green line anymore

**Comment by Klaus1189** [comment]
I can also confirm that the testbuild fixed the issue :)
