### ISSUE TITLE
How can i play Bluray with DolbyVsion 

### ISSUE THREAD

**Issue by kenny53** [Aleksoid1978/VideoRenderer#160]
Thanks for your work,the render can play dolbyvision even p8 with REMUX file.
But M2TS can not,i clicked prefer dv over pq.

> PLAYLIST REPORT:
> 
> Name:                  00800.MPLS
> Length:                2:04:08.440 (h:m:s.ms)
> Size:                  80,673,687,552 bytes
> Total Bitrate:          86.65 Mbps
> 
> (*) Indicates included stream hidden by this playlist.
> 
> VIDEO:
> 
> Codec                  Bitrate            Description   
> -----                  -------            -----------   
> MPEG-H HEVC Video      62468 kbps          2160p / 23.976 fps / 16:9 / Main 10 @ Level 5.1 @ High / 10 bits / HDR10 / BT.2020
> MPEG-H HEVC Video    2101 kbps          1080p / 23.976 fps / 16:9 / Main 10 @ Level 5.1 @ High / 10 bits / Dolby Vision / BT.2020

**Comment by v0lt** [comment]
1. You didn't provide a sample, so there's nothing to talk about.
2. In any case, the video renderer does not play files, it displays frames in the player window. The video renderer does not know what format your video file is in (mkv or m2ts). The video renderer receives the decoded frames and all additional information from the decoder.
3. Dolby Vision Profile 8.1 is HDR10 compatible, so should work with default settings (as it does when playing your MKVs).

**Comment by kenny53** [comment]
Understood
