### ISSUE TITLE
RTX HDR problem after k-lite 18.3.0

### ISSUE THREAD

**Issue by djsolidsnake86** [Aleksoid1978/VideoRenderer#161]
18.3.0 was last version where rtx hdr work good (colors are natural)
after this version the colors in some video files are oversaturated, and there is no way to fix this (only by disabling rtx hdr)
this is a example
https://postimg.cc/mt7FNgRT
General
Unique ID                      : 218957066969626823468132216382211449443 (0xA4B998E0DDFE38093B4403AA70636263)
Complete name                  
Format                         : Matroska
Format version                 : Version 2
File size                      : 12.5 GiB
Duration                       : 2 h 36 min
Overall bit rate               : 11.4 Mb/s
Frame rate                     : 23.976 FPS
Encoded date                   : 2019-11-26 10:41:15 UTC
Writing application            : mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
Writing library                : libebml v1.3.9 + libmatroska v1.5.2

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 2 h 36 min
Bit rate                       : 9 269 kb/s
Width                          : 1 920 pixels
Height                         : 802 pixels
Display aspect ratio           : 2.39:1
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.251
Stream size                    : 10.1 GiB (81%)
Title                          : Alì
Writing library                : x264 core 158 r2988 7817004
Encoding settings              : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=0 / crf=20.2 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=50000 / vbv_bufsize=50000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / pb_ratio=1.30 / aq=3:0.85
Language                       : Italian
Default                        : Yes
Forced                         : No

Audio #1
ID                             : 2
Format                         : DTS
Format/Info                    : Digital Theater Systems
Codec ID                       : A_DTS
Duration                       : 2 h 36 min
Bit rate mode                  : Constant
Bit rate                       : 1 509 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 24 bits
Compression mode               : Lossy
Stream size                    : 1.65 GiB (13%)
Title                          : DTS 5.1
Language                       : Italian
Default                        : Yes
Forced                         : No

Audio #2
ID                             : 3
Format                         : AC-3
Format/Info                    : Audio Coding 3
Commercial name                : Dolby Digital
Codec ID                       : A_AC3
Duration                       : 2 h 36 min
Bit rate mode                  : Constant
Bit rate                       : 640 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Compression mode               : Lossy
Stream size                    : 717 MiB (6%)
Title                          : AC3 5.1
Language                       : English
Service kind                   : Complete Main
Default                        : No
Forced                         : No
AC3_metadata cmixlev           : -3.0 dB
surmixlev                     : -3 dB

Text #1
ID                             : 4
Format                         : UTF-8
Codec ID                       : S_TEXT/UTF8
Codec ID/Info                  : UTF-8 Plain Text
Duration                       : 2 h 30 min
Bit rate                       : 0 b/s
Frame rate                     : 0.001 FPS
Count of elements              : 12
Stream size                    : 521 Bytes (0%)
Title                          : Italiano forced
Language                       : Italian
Default                        : Yes
Forced                         : Yes

Text #2
ID                             : 5
Format                         : VobSub
Codec ID                       : S_VOBSUB
Codec ID/Info                  : Picture based subtitle format used on DVDs
Duration                       : 2 h 30 min
Bit rate                       : 5 708 b/s
Frame rate                     : 0.134 FPS
Count of elements              : 1209
Stream size                    : 6.16 MiB (0%)
Title                          : Italiano
Language                       : Italian
Default                        : No
Forced                         : No

Text #3
ID                             : 6
Format                         : PGS
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 2 h 30 min
Bit rate                       : 24.0 kb/s
Frame rate                     : 0.267 FPS
Count of elements              : 2420
Stream size                    : 25.9 MiB (0%)
Title                          : Italiano
Language                       : Italian
Default                        : No
Forced                         : No

Menu
00:00:00.000                   : it:Capitolo 1
00:13:31.769                   : it:Capitolo 2
00:26:22.790                   : it:Capitolo 3
00:39:46.342                   : it:Capitolo 4
00:52:03.245                   : it:Capitolo 5
01:05:19.124                   : it:Capitolo 6
01:19:42.027                   : it:Capitolo 7
01:31:27.399                   : it:Capitolo 8
01:45:19.438                   : it:Capitolo 9
01:58:14.004                   : it:Capitolo 10
02:11:25.419                   : it:Capitolo 11

**Comment by Aleksoid1978** [comment]
Don't use k-lite.
Perfect work in MPC-BE + MPC-VR.

**Comment by djsolidsnake86** [comment]
> Don't use k-lite. Perfect work in MPC-BE + MPC-VR.

what i must use?? i don't use mpc be

**Comment by Aleksoid1978** [comment]
K-lite is a garbage dump.

**Comment by djsolidsnake86** [comment]
> K-lite is a garbage dump.

I tried mpc be ei klite 18.3.5, same problem
only klite 18.3.0 give the right colors with rtx hdr (the problem only occurs in some videos)

**Comment by Aleksoid1978** [comment]
Upload problem files or short samples.

**Comment by djsolidsnake86** [comment]
> Upload problem files or short samples.

https://file.io/OkM1FMf1g1Fn

**Comment by djsolidsnake86** [comment]
i found this:
https://github.com/clsid2/MPCVideoRenderer/releases
installing this version of mpc video renderer on 18.3.5 give right colors
so the problem is the video renderer

**Comment by djsolidsnake86** [comment]
> https://github.com/qwerttvv/Player/releases/download/2024.05.26-1222/MpcVideoRenderer-0.8.2.2244_git2024.05.23-7775461.zip https://github.com/qwerttvv/Player/releases/download/2024.05.23-1025/MpcVideoRenderer-0.8.2.2243_git2024.05.23-67d4c9f.zip https://github.com/qwerttvv/Player/releases/download/2024.05.19-0442/MpcVideoRenderer-0.8.2.2240_git2024.05.18-7397ad2.zip https://github.com/qwerttvv/Player/releases/download/2024.05.18-1845/MpcVideoRenderer-0.8.2.2238_git2024.05.18-265b9b5.zip
> 
> This should help narrow down.

2443 is good, problem happen in 2244

**Comment by djsolidsnake86** [comment]
> Try this one: [MpcVideoRenderer64_rtxfix.zip](https://github.com/user-attachments/files/15539466/MpcVideoRenderer64_rtxfix.zip)
> 
> Changed [7775461](https://github.com/Aleksoid1978/VideoRenderer/commit/7775461cedc48e3855de91fc4f4bb977d36dbc0d) to skip VP resize for normal HDR only: `m_bHdrPassthroughSupport && m_bHdrPassthrough && !m_bVPUseRTXVideoHDR`

this is to use with last nightly?

**Comment by djsolidsnake86** [comment]
> Just overwrite it. This is 2251 plus potential fix.

it solve the problem!

**Comment by djsolidsnake86** [comment]
> Does 2244 work if you disable SuperResolution?

nope, oversatured colors

**Comment by Aleksoid1978** [comment]
Sample is unavailable.
I test on my videos - all is good in MPC-BE and MPC-HC.

**Comment by Aleksoid1978** [comment]
Try this build.
[MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip](https://github.com/user-attachments/files/15540762/MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip)

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip](https://github.com/user-attachments/files/15545902/MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip)

**Comment by Aleksoid1978** [comment]
And upload sample.

**Comment by djsolidsnake86** [comment]
> [MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip](https://github.com/user-attachments/files/15545902/MpcVideoRenderer-0.8.2.2252_git2024.06.04-8b2c5ed.zip)

this is good

**Comment by djsolidsnake86** [comment]
https://drive.google.com/file/d/1dGnO5QXhXiOOOXz8H4GRzVWbvBus02X8/view?usp=sharing

**Comment by djsolidsnake86** [comment]
> Since it is just a standard 8-bit sample, perhaps behavior difference on your guys systems might be due to different driver version?
> 
> And given that my workaround/fix also worked, the issue is likely related to resizing. @djsolidsnake86 Does the problem also occur on the broken versions when video is viewed at 100% size (so no resizing)?

yes
