### ISSUE TITLE
Serious issue: Breaks my graphics card. Gets disabled with code 43.

### ISSUE THREAD

**Issue by mzso** [Aleksoid1978/VideoRenderer#163]
Hi!

So I tried upgrading the renderer to the newews two days ago (0.8.1.2230). It immediately broke my graphics card (Asus DUAL-RX580-O4G). It got disabled by windows with code 43. And no matter what I did I couldn't get it to work again. I had to refresh Windows from ISO to get the graphics card working again.
Then I tried 0.8.3.2255, which came out in the meanwhile. It also instantly broke the graphics card. At least this time I created a system restore point.

I can't imagine why it happens, but it's appalling. Never had an issue like this with any directshow filter or such.
I can play videos happily with madVR.

PS:
I have been using 0.7.0.2126 before. (Probably, that's the package I have from before 0.8.1.2230) I had no problems with this.

**Comment by v0lt** [comment]
[HEVC 4k HDR 10-bit 60 fps](https://drive.google.com/file/d/171DMXGt_MC0YftXf_e5vePJHM-MPmtJq/view)

MPC Video Renderer 0.8.3.2255
[MPC-BE x64 1.7.1.60 dev](https://github.com/qwerttvv/Player/releases/tag/2024.06.05-2347)
Windows 10 22H2

Nvidia GTX 950 - OK
Intel UHD 750 - OK

You have a driver or video card problem.

**Comment by mzso** [comment]
@v0lt
The driver didn't change, I've been using it since last year. For a while I also suspected a video card problem. But with a fresh installation of windows it worked. It only breaks when I start using MPC video renderer in the player.

**Comment by mzso** [comment]
@clsid2 Well, it was rendered non-functional. And it seems neither of the above. No Windows or driver updates happened for a long time, and the GPU still functions.
In any way, it was triggered by using MPC VR, whichever way it happened.

**Comment by v0lt** [comment]
> The driver didn't change, I've been using it since last year.

The driver should not break due to exposure to the client application.

**Comment by v0lt** [comment]
You can view the debug log and send it to AMD.
https://github.com/Aleksoid1978/VideoRenderer/wiki/View-debug-log
