### ISSUE TITLE
Super Resolution on vertical video with >= 1440p Frame Height

### ISSUE THREAD

**Issue by jameswortiz728** [Aleksoid1978/VideoRenderer#165]
Super resolution does not seem to scale vertical videos with >= 1440p frame height, ex. 1080x1920 will not be upscaled. It works as intended with vertical and horizontal video <= 1440p with the right settings. 

I use a 4k monitor in portrait mode for vertical content that I would also like to have upscaled as the 1080p looks a bit blurry. I believe this is a new issue as it has worked in the past, unless there is a setting I am missing. Thanks.

**Comment by v0lt** [comment]
The request is clear. There was even a patch for something like this somewhere. But it’s unclear why use Super Resolution when the frame height is slightly smaller than the display height?

**Comment by Aleksoid1978** [comment]
Can you upload video 1080x1920.

**Comment by v0lt** [comment]
I think the solution should be like this.
[RotatedSuperRes.diff.txt](https://github.com/user-attachments/files/15756129/RotatedSuperRes.diff.txt)

**Comment by Aleksoid1978** [comment]
Done.

**Comment by v0lt** [comment]
another solution with 1280p and 1920p
https://disk.yandex.ru/d/diD-2ngj76vl-w
