### ISSUE TITLE
RTX Super Resolution not working

### ISSUE THREAD

**Issue by TrixySa** [Aleksoid1978/VideoRenderer#166]
Hello, I'm having this issue with VSR that shows that it's activated but has no visual improvements whatsoever. And the scaling is the same with it on or off.

I'm attaching the screenshots. Also, I have tried this on a normal 1080p monitor and a 3440*1440 ultrawide. Same result on both.

![Screenshot 2024-06-08 153440](https://github.com/Aleksoid1978/VideoRenderer/assets/109800970/149443ca-cbb6-423b-8acb-a55f349a6d13)

![Screenshot 2024-06-08 153412](https://github.com/Aleksoid1978/VideoRenderer/assets/109800970/62deb24f-fdcd-49d4-9768-f4e5eedb06b7)

Here I attached screenshots of it on and off.

**Comment by Aleksoid1978** [comment]
That's right, we can't know - activate in drivers ot not. Ant when we call activate functional - it's always return "true".

**Comment by v0lt** [comment]
[history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/adccf0286464bf42b0b32a3f3cc921c83a494b4c/history.txt#L46)
> 0.6.7.2013 - 2023-03-29
> ------------------------
> Added "Request Super Resolution" option for Nvidia and Intel graphics adapters. Hardware and driver support required. The display of "SuperResolution*" in the statistics only means that the request was sent successfully.

**Comment by TrixySa** [comment]
> That's right, we can't know - activate in drivers ot not. Ant when we call activate functional - it's always return "true".


Got it, so is there no fix for this right now or?
