### ISSUE TITLE
RTX VSR + System setting "Automatically manage color for apps" causes videos to look dim

### ISSUE THREAD

**Issue by Artins90** [Aleksoid1978/VideoRenderer#167]
Disabling either RTX VSR or "Automatically manage color for apps" (in Windows 26120.712) immediately fixes the issue.
Currently I am using MPC-HC version 2.3.0, toggling "Use legacy display ICC color management" under right click > properties > compatibility doesn't fix the issue.

Using RTX VSR with web content (Youtube, Twtitch etc.) on the same system doesn't cause similar dimming issues.

Clip of the issue: https://file.io/1kd6Yf61xBXS

Pin info:
`Filter : MPC Video Renderer - CLSID : {71F080AA-8661-4093-B15E-4F6903E77D0A}

Connected to:
CLSID: {EE30215D-164F-4A92-A4EB-9D4C13390F9F}
Filter: LAV Video Decoder
Pin: Output

Connection media type:
Video: P010 896x480 (427:240) 59.94fps

AM_MEDIA_TYPE:
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: MEDIASUBTYPE_P010 {30313050-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo2 {F72A76A0-EB0A-11D0-ACE4-0000C0CC16BA}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1229760
cbFormat: 132

VIDEOINFOHEADER:
rcSource: (0,0)-(854,480)
rcTarget: (0,0)-(854,480)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 166833

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 427
dwPictAspectRatioY: 240
dwControlFlags: 0x00002581
dwReserved2: 0x00000000

BITMAPINFOHEADER:
biSize: 40
biWidth: 896
biHeight: 480
biPlanes: 1
biBitCount: 24
biCompression: P010
biSizeImage: 1290240
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 56 03 00 00 e0 01 00 00 ........V...à...
0010: 00 00 00 00 00 00 00 00 56 03 00 00 e0 01 00 00 ........V...à...
0020: 00 00 00 00 00 00 00 00 b1 8b 02 00 00 00 00 00 ........±�......
0030: 00 00 00 00 00 00 00 00 ab 01 00 00 f0 00 00 00 ........«...ð...
0040: 81 25 00 00 00 00 00 00 28 00 00 00 80 03 00 00 �%......(...�...
0050: e0 01 00 00 01 00 18 00 50 30 31 30 00 b0 13 00 à.......P010.°..
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070:|80 03 00 00 e0 01 00 00 56 03 00 00 e0 01 00 00 �...à...V...à...
0080: 50 30 31 30 P010
`

`Filter : LAV Video Decoder - CLSID : {EE30215D-164F-4A92-A4EB-9D4C13390F9F}

Connected to:
CLSID: {B98D13E7-55DB-4385-A33D-09FD1BA26338}
Filter: LAV Splitter Source
Pin: Video

Connection media type:
Video: MPEG4 Video (H264) 854x480 59.94fps

AM_MEDIA_TYPE:
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {31435641-0000-0010-8000-00AA00389B71}
formattype: FORMAT_MPEG2_VIDEO {E06D80E3-DB46-11CF-B4D1-00805F6CBBEA}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 173

VIDEOINFOHEADER:
rcSource: (0,0)-(854,480)
rcTarget: (0,0)-(854,480)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 166833

VIDEOINFOHEADER2:
dwInterlaceFlags: 0x00000000
dwCopyProtectFlags: 0x00000000
dwPictAspectRatioX: 427
dwPictAspectRatioY: 240
dwControlFlags: 0x00000000
dwReserved2: 0x00000000

MPEG2VIDEOINFO:
dwStartTimeCode: 0
cbSequenceHeader: 41
dwProfile: 0x0000006e
dwLevel: 0x00000028
dwFlags: 0x00000004

BITMAPINFOHEADER:
biSize: 40
biWidth: 854
biHeight: 480
biPlanes: 1
biBitCount: 15
biCompression: AVC1
biSizeImage: 769920
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 56 03 00 00 e0 01 00 00 ........V...à...
0010: 00 00 00 00 00 00 00 00 56 03 00 00 e0 01 00 00 ........V...à...
0020: 00 00 00 00 00 00 00 00 b1 8b 02 00 00 00 00 00 ........±�......
0030: 00 00 00 00 00 00 00 00 ab 01 00 00 f0 00 00 00 ........«...ð...
0040: 00 00 00 00 00 00 00 00 28 00 00 00 56 03 00 00 ........(...V...
0050: e0 01 00 00 01 00 0f 00 41 56 43 31 80 bf 0b 00 à.......AVC1�¿..
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070: 00 00 00 00 29 00 00 00 6e 00 00 00 28 00 00 00 ....)...n...(...
0080: 04 00 00 00|00 1e 67 6e 00 28 a6 c7 28 44 0d 83 ......gn.(¦Ç(D.�
0090: de 6f ff 03 55 03 56 10 00 00 3e 90 00 1d 4c 00 Þoÿ.U.V...>�..L.
00a0: f1 83 18 46 00 07 68 e8 43 82 32 c8 b0 ñ�.F..hèC�2È°`

**Comment by v0lt** [comment]
> RTX VSR + System setting "Automatically manage color for apps" causes videos to look dim

Do not use one of these driver or system features. It is obvious.
It’s not clear what MPC VR has to do with it.

**Comment by Artins90** [comment]
@clsid2 I was just experimenting with settings trying to figure whether it might be related to HDR.  
RTX VSR works correctly with 16bit texture format as long as "Automatically manage color for apps" is disabled in system settings.

While experimenting, I noticed that setting "RTX Video HDR", "Passthrough to display", "Windows HDR toggle" and "Automatically manage color for apps" to ON, the image goes back to normal HDR brightness levels.

Strangely, with the same "RTX Video HDR", "Passthrough to display", "Automatically manage color for apps" set to ON but "Windows HDR toggle" set to off, the output goes into a sort of half-state, with brighter levels similar to correct SDR but crushed highlights, due to the HDR toggle being off.
