### ISSUE TITLE
Question about Super Resolution

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#168]
Is Super Resolution possible with AMD GPU? If Yes, will you support it in future?
Because, VLC's 3.0.21 changelog shows this.
![Screenshot (80)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/7c9edae8-fd21-4a20-a4be-cf60463cfad0)

https://www.videohelp.com/software/VLC-media-player#:~:text=Super%20Resolution%20scaling%20with%20AMD%20GPUs

**Comment by Aleksoid1978** [comment]
No.

**Comment by v0lt** [comment]
Similar issue #114.
