### ISSUE TITLE
[Feature request] chroma upscaling algorithm jinc to mpcvr Chroma upsampling 

### ISSUE THREAD

**Issue by AhmedSamir899** [Aleksoid1978/VideoRenderer#169]
i use mpc with madvr and notice that colors look much better with jinc compare to mpcvr with catmull-rom or bilinear chroma upsampling

**Comment by v0lt** [comment]
I can't agree with "colors look much better".
On a regular video, people will not be able to feel the difference between Catmull-Rom and Jinc2m for chroma in a blind test. You'll likely see an improvement on special samples, but those are the rare cases you'll want to use madVR for. There are a lot of things in madVR that won't be implemented in MPC VR for various reasons.

**Comment by AhmedSamir899** [comment]
"There are a lot of things in madVR that won't be implemented in MPC VR for various reasons."  can you tell me the reason because even if there is no big difference between Catmull-Rom and Jinc2m it will not be bad to have both and you can choose.

**Comment by Aleksoid1978** [comment]
Not planned.

**Comment by v0lt** [comment]
> even if there is no big difference between Catmull-Rom and Jinc2m it will not be bad to have both and you can choose.

Catmull-Rom is simply implemented to increase the component by 2 times. Therefore, now we are implementing it as part of a large shader of color transformation.
Jinc2m requires more input pixels and it has more complicated code. And since the benefits of it are not enough, we do not plan to introduce it.

**Comment by AhmedSamir899** [comment]
what about Lanczos it gives almost same result as Jinc2m and more efficient

**Comment by v0lt** [comment]
> Lanczos it gives almost same result as Jinc2m

No. It's similar to Catmull-Rom, but a little sharper.
[And as I said](https://github.com/Aleksoid1978/VideoRenderer/issues/169#issuecomment-2187209522), on regular videos this does not make a noticeable positive difference in a blind test.
