### ISSUE TITLE
Video blinks (black frames?) when not on top (with MPC Video Renderer)

### ISSUE THREAD

**Issue by Faiakes** [Aleksoid1978/VideoRenderer#17]
This is not happening on every video. 
It does not happen with EVR-CP.

**This is my current setup:**

MPC-HC (Nightly, 64-bit)

Build information:
    Version:            1.9.6.28 (e518e401c)
    Compiler:           MSVC v19.26.28806
    Build date:         Jul 10 2020

LAV Filters:
    LAV Splitter:       0.74.1.64
    LAV Video:          0.74.1.64
    LAV Audio:          0.74.1.64
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 10.0 (build 20170)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    GPU:                Intel(R) HD Graphics 620 (driver version: 27.20.100.8425)[/CODE]

**Here's one file it happens with:**

Format                      : Matroska
Format version              : Version 4
File size                   : 1.91 GiB
Duration                    : 30 min 7 s
Overall bit rate mode       : Variable
Overall bit rate            : 9 054 kb/s
Encoded date                : UTC 2020-07-20 04:01:56
Writing application         : mkvmerge v48.0.0 ('Fortress Around Your Heart') 64-bit
Writing library             : libebml v1.4.0 + libmatroska v1.6.0

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 30 min 7 s
Bit rate mode               : Variable
Bit rate                    : 8 668 kb/s
Maximum bit rate            : 12.4 Mb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 29.970 (30000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.139
Stream size                 : 1.82 GiB (96%)
Language                    : English
Default                     : Yes
Forced                      : No

Audio
ID                          : 2
Format                      : AC-3
Format/Info                 : Audio Coding 3
Commercial name             : Dolby Digital
Codec ID                    : A_AC3
Duration                    : 30 min 7 s
Bit rate mode               : Constant
Bit rate                    : 384 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossy
Stream size                 : 82.8 MiB (4%)
Language                    : English
Service kind                : Complete Main
Default                     : Yes
Forced                      : No

Text
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 29 min 47 s
Bit rate                    : 129 b/s
Count of elements           : 1150
Stream size                 : 28.2 KiB (0%)
Title                       : English (SDH)
Language                    : English
Default                     : No
Forced                      : No

**Comment by Aleksoid1978** [comment]
Try in MPC-BE with internal filters - https://yadi.sk/d/hlf1lfC8mKU58/!_last

**Comment by Faiakes** [comment]
I tried it and it does it, too.
Could it be an Intel driver thing?

**Comment by Aleksoid1978** [comment]
Enable statistic in options. Then record short video with blinking.

**Comment by Faiakes** [comment]
Here you go:

https://www.dropbox.com/s/lniuiiqcgmcgbl6/MPC-blink.mp4?dl=0

**Comment by Aleksoid1978** [comment]
1 - Enable statistics in MPC VR and record again.
2 - Disable subtitles output.

**Comment by Faiakes** [comment]
Hi

What do you mean by  MPC VR?
Did you mean Ctrl+J, to show statistics on the video?

**Comment by Aleksoid1978** [comment]
In MPC Video Renderer(MPC VR), in options check "Show statistics".

**Comment by Faiakes** [comment]
I don't see such a check mark anywhere but Ctrl+J works.
If that is not right, please provide more detailed instructions how to enable statistics.  :) 
Here you go:
https://www.dropbox.com/s/n1jxmvk0qfw2omb/Blink2.mp4?dl=0

**Comment by Aleksoid1978** [comment]
Very strange issue.
What's happen if you disable subtitles output ?

**Comment by Faiakes** [comment]
The issue persists.

**Comment by v0lt** [comment]
@**Faiakes**
What subtitle renderer are you using?

**Comment by Faiakes** [comment]
I don't know. How do you figure that out?

Would the issue be related to the fact that I'm not using MPC-BE but rather MPC within the K-Lite Codec Pack?

**Comment by Aleksoid1978** [comment]
Show filter list when playback.

**Comment by Aleksoid1978** [comment]
Also try - uninstall K-Lite Codec Pack then install MPC-HC or MPC-BE with clean install(drop existing settings).

**Comment by Faiakes** [comment]
Uninstalled K-Lite.
MPC-BE + MPC VR works fine.

**Comment by Aleksoid1978** [comment]
Close issue.
