### ISSUE TITLE
Saving images when Windows HDR is enabled results in wrong colors

### ISSUE THREAD

**Issue by RieGo** [Aleksoid1978/VideoRenderer#170]
When you work with windows HDR mode enabled and try to save a (SDR) image from a video, its colors are washed out. when you disable HDR mode they look fine.
the result should always be the same IMHO.
I'm using MPC-HC and MPC Video Renderer with RTX HDR disabled.

HDR:
![HDR](https://github.com/user-attachments/assets/2411afc3-4451-4378-bbdc-d3985ef22f61)
SDR:
![SDR](https://github.com/user-attachments/assets/9ab0844a-9b08-47c4-a4f2-5784dbd3ccdc)

**Comment by rampageX** [comment]
Use Windows logo key + Shift + R for a HDR video capture.

![hdr_screenshot](https://github.com/user-attachments/assets/976aa7b5-685a-43d5-9604-257272a85fba)

**Comment by RieGo** [comment]
I think you misunderstood. I don't need an HDR capture.
I need to save a frame of an SDR video file.
The result differs, wether windows HDR is enabled or not.

**Comment by Aleksoid1978** [comment]
This behavior is normal when watch with HDR passthrough - no HDR -> SDR conversion occurs when saving the image.

**Comment by Aleksoid1978** [comment]
No - he's play HDR + passthrough and want save as SDR.

**Comment by Aleksoid1978** [comment]
> When `RTX Video HDR` is enabled in the renderer it will assume that is also enabled and working in the graphics driver.
> 
> @Aleksoid1978 It should check for feature availability first, like in VLC? https://code.videolan.org/videolan/vlc/-/blob/master/modules/video_output/win32/d3d11_tonemap.cpp#L113 And same for SuperRes: https://code.videolan.org/videolan/vlc/-/blob/master/modules/video_output/win32/d3d11_scaler.cpp#L111
> 
> @RieGo Test build that performs capability check: [MpcVideoRenderer64.zip](https://github.com/user-attachments/files/16238823/MpcVideoRenderer64.zip)

Have you checked?
We are checking by vendor, and these checks via VideoProcessorGetStreamExtension always return available, even if I disable it in the Nvidia driver, at least it used to be so.

**Comment by Aleksoid1978** [comment]
I double-checked and it is true. Therefore, checking through the **VideoProcessorGetStreamExtension** call does not make any sense.

**Comment by Aleksoid1978** [comment]
Just "RTX Video HDR" in the renderer settings.

**Comment by Aleksoid1978** [comment]
I see no point, at least for now, in adding completely pointless checks.
Maybe over time, when they implement this in drivers and these checks will work.

**Comment by RieGo** [comment]
It's unfortunate that it can't be checked.
Let me explain why I enabled the setting:
I've become accustomed to switching the setting in the NVIDIA driver because it was always enabled on YouTube. So I figured this was the only way to turn it off globally.

Anyways, thanks for your help.
