### ISSUE TITLE
Switching to HDR mode on Windows 24H2 Build 26100 when "Automatically manage color for apps" is enabled in SDR mode

### ISSUE THREAD

**Issue by 1aTa** [Aleksoid1978/VideoRenderer#172]
Windows 24H2 Build 26100 has a new option which seems to be confusing all HDR mode switching utilities and media players, including MPC Video Renderer.

The new option "Automatically manage color for apps" under "System > Display > Color Management" increases the color range of Windows SDR to HDR levels to remove things like color banding. It works great and is very noticeable throughout the Windows UI but a side effect is all apps think they are already in HDR mode, when they're actually not. With this option enabled the only way I've found to switch Windows HDR mode on and off is with the toggle in Windows settings.

MPC Video Renderer is unable to switch to HDR mode from SDR mode when "Windows HDR: Allow turn on" is enabled in the settings.

More info here: https://support.microsoft.com/en-us/windows/auto-color-management-in-windows-11-64a4de7f-9c93-43ec-bdf1-3b12ffa0870b

**Comment by Aleksoid1978** [comment]
Don't use dev windows build. If use - don't write any issue.

**Comment by 1aTa** [comment]
Windows 24H2 is released in the Retail channel on arm64 (for Copilot+ PCs) and the amd64 Retail channel release is imminent.

**Comment by Aleksoid1978** [comment]
I don't have arm64 PC.

**Comment by 1aTa** [comment]
It's in the Release Preview channel (not dev) for amd64 if you fancy having a look.

Expecting Retail channel any day now.

**Comment by 1aTa** [comment]
This is the first app that I know of which has resolved this issue: https://github.com/res2k/HDRTray/issues/13

**Comment by Aleksoid1978** [comment]
> Relevant example code for new Windows 11 24H2 API: https://github.com/res2k/HDRTray/pull/15/files

Install this version of Windows, write code, test, send a patch :)

**Comment by Aleksoid1978** [comment]
Fixed.
