### ISSUE TITLE
add option to define display transfer function for HDR -> SDR tone mapping for more accurate tonemapping.

### ISSUE THREAD

**Issue by mightyhuhn** [Aleksoid1978/VideoRenderer#173]
Currently it is hard coded to 2.2 which is a gamma the majority of calibrator will not target i changed the value to 2.4 and it seem to work just fine so this should be do able.

i wanted to map the nits/100 to it but could not manage to do it that for testing.

**Comment by Aleksoid1978** [comment]
Not planned.
