### ISSUE TITLE
No video window from MPCVideoRenderer 0.8.3.2255 in GraphStudioNext

### ISSUE THREAD

**Issue by gaamaaresosa** [Aleksoid1978/VideoRenderer#174]
Hi 

I love all your MPC projects.

But unfortunately I get no video output from any on your  **MPCVideoRenderer_0.8.3.2255**

Please check the graph I try on  GraphStudioNext 32bit

I tried for years and left the interest on it.
But you are keep updating which I wonder.

So what is wrong in my tests ?
I use Windows 10 64bit OS (Even same with Win7 and Win11)

Note: The Active Movie Window itself will not open.

**Even on all older version too:**
MPC Video Renderer 0.3.7.1018
MPC Video Renderer 0.3.8.1060
MPC Video Renderer 0.4.0.1122
MPC Video Renderer 0.4.6.1283
MPC Video Renderer 0.5.6.1807

Thanks in advance.
g

![NoVideoOut](https://github.com/user-attachments/assets/1de282a6-b359-49b9-91e0-e0f11bca46cc)
![NoVideoOut2](https://github.com/user-attachments/assets/806fe3ea-965e-4fd4-bfd3-deb1eb4869b5)

**Comment by v0lt** [comment]
This "problem" is known. But no one tried to solve it, because it is not necessary. If you have a solution, then show a patch or make a pull request.

**Comment by gaamaaresosa** [comment]
> This "problem" is known. But no one tried to solve it, because it is not necessary. If you have a solution, then show a patch or make a pull request.
> because it is not necessary
lol !
Video Renderer means it is understood that it must display the frames on the screen.
Otherwise its called sink filter.

**Comment by v0lt** [comment]
> Video Renderer means it is understood that it must display the frames on the screen.

MPC Video Renderer displays video frames in MPC-BE, MPC-HC and PotPlayer on the display screen. Many people use it to watch movies, animations and TV series. And they do not need the ability to watch videos in GraphStudioNext.

**Comment by gaamaaresosa** [comment]
> > Video Renderer means it is understood that it must display the frames on the screen.
> 
> MPC Video Renderer displays video frames in MPC-BE, MPC-HC and PotPlayer on the display screen. Many people use it to watch movies, animations and TV series. And they do not need the ability to watch videos in GraphStudioNext.

You mean they have purposely don't support other video players.
No where they had mentioned that.

>MPC Video Renderer is a free and open-source video renderer for DirectShow. The renderer can potentially work with any >DirectShow player, but full support is available only in the MPC-BE. Recommended MPC-BE 1.7.0.19 or newer.

**Comment by gaamaaresosa** [comment]
> What exactly is the problem? Does GraphStudioNext not create a window to render on?

Yes, please drop the filter on any graph edit or any video player.
Render and play. It will play, but no video window will invoke. It behaves Just like sink filter.

**Comment by Aleksoid1978** [comment]
https://github.com/cplussharp/graph-studio-next/issues/332

**Comment by gaamaaresosa** [comment]
> [cplussharp/graph-studio-next#332](https://github.com/cplussharp/graph-studio-next/issues/332)

Couldn't understand !
There is a link pointing as below.
Custom VideoRenderer - https://github.com/Aleksoid1978/VideoRenderer

Should I download the binary from Release link because master source code doesn't have binary file.
I downloaded and tested 
https://github.com/Aleksoid1978/VideoRenderer/releases/download/0.8.5/MpcVideoRenderer-0.8.5.2268.zip

Still same issue.
![Bad](https://github.com/user-attachments/assets/900880ac-317f-4f80-aad9-b7e95cd39240)

**Comment by gaamaaresosa** [comment]
> [cplussharp/graph-studio-next#332](https://github.com/cplussharp/graph-studio-next/issues/332)

This is not a GraphStudioNext issue.
Its 100% MPCVideoRenderer issue which I am seeing more than 10 Years.

See my application also no video.

Please don't close this issue, instead try to fix it.

![Bad2](https://github.com/user-attachments/assets/58c7e097-6ea1-4f72-9c51-e467b9d41e20)


![Bad2](https://github.com/user-attachments/assets/dc3616f1-ccd5-4151-9cdf-e24e41840112)

**Comment by gaamaaresosa** [comment]
> I check source for uses of `IVideoWindow` and GSN only uses it to set caption: https://github.com/cplussharp/graph-studio-next/blob/master/src/display_graph.cpp#L3124 It does not call `put_Owner` like MPC-HC/BE do. But I don't think that is an actual requirement. That function is for if the player wants to make the video window a child of (one of) its own window(s). GSN seems to expect video renderer to make its own standalone window.

I can make any changes on my source code and test in no time.
I set parent window properly.
I prefere MCPVideoRenderer because VMR9 on secondary display  hand often.
HaaliVideoRender only one instance.
Windows VMR7 only white screen on Windows 10/11
madVR out of maintenance

**Comment by gaamaaresosa** [comment]
> I check source for uses of `IVideoWindow` and GSN only uses it to set caption: https://github.com/cplussharp/graph-studio-next/blob/master/src/display_graph.cpp#L3124 It does not call `put_Owner` like MPC-HC/BE do. But I don't think that is an actual requirement. That function is for if the player wants to make the video window a child of (one of) its own window(s). GSN seems to expect video renderer to make its own standalone window.

Please don't close this issue, at least some one may fix it in the future.
See the Input Pin 0 is not tagged as Renderer on MPCVideoRenderer.

![Comarpare](https://github.com/user-attachments/assets/fc41b1bd-f06b-43d0-8289-76bf7c07cdc9)

My code also says no video visible.
![code1](https://github.com/user-attachments/assets/49c56f10-88a3-4210-8f43-dbb1ec88a50d)

**Comment by Aleksoid1978** [comment]
MPC VR does not create its own window and will not.
It uses an existing window that the player or any other VR-using program must point to it, period.

**Comment by Aleksoid1978** [comment]
> HaaliVideoRender only one instance.

MPC VR also only ONE instance.

**Comment by gaamaaresosa** [comment]
> MPC VR does not create its own window and will not. It uses an existing window that the player or any other VR-using program must point to it, period.

I do video projects for last 20 years.
Done many combination of video rendering self, virtual. windows.
I marked MPCVideoRenderer has Issues several years, back.
Today I some how took it as the newer version would be better.

Some where some issue is there.
Any how let me spend some time to experiment.

**Comment by gaamaaresosa** [comment]
> > HaaliVideoRender only one instance.
> 
> MPC VR also only ONE instance.

Oh !
That means this also can't help me.
But I will keep in my array and use one after other.

**Comment by Aleksoid1978** [comment]
The short summary - is that if you want to use MPC VR, you need to create the window yourself and pass its hwnd to VR by calling IVideoWindow::put_Owner(). MPC VR will not create the output window itself. That's it - the discussion is over.

**Comment by gaamaaresosa** [comment]
> Its one instance per application. You can use multiple player instances.

Good !

**Comment by gaamaaresosa** [comment]
> The short summary - is that if you want to use MPC VR, you need to create the window yourself and pass its **hwnd** to VR by calling **IVideoWindow::put_Owner()**. MPC VR will not create the output window itself. That's it - the discussion is over.

Yes I do that.
```

    Set VidWindow = MediaControl
    'TO AVOID FLICK WE MUST DO VidWindow.Owner 2 TIMES AS BELOW
    VidWindow.Owner = m_VideoWindowOwner 'UserControl.hwnd
    VidWindow.WindowStyle = CLng(&H6000000)
    VidWindow.Owner = m_VideoWindowOwner 'UserControl.hwnd
    'Most important, this sends all windows messages to the UserControl
    VidWindow.MessageDrain = m_VideoWindowOwner
```

**Comment by Aleksoid1978** [comment]
I don't care at all what works or doesn't work for you there. If you have to, figure it out. The sources are open, see in the debugger what's wrong.
We'll write here from now on - I'll just delete this issue and that's it.

**Comment by gaamaaresosa** [comment]
> I don't care at all what works or doesn't work for you there. If you have to, figure it out. The sources are open, see in the debugger what's wrong. We'll write here from now on - I'll just delete this issue and that's it.

I observe adding the renderer on our graph fails.
I tried 2 methods. Both fails.
Best thing is that we have to fix it by fiddling the settings inside GraphStudioNext GUI itself.

```

   Method1:
        Dim RegFilters As IRegFilterInfo
        **RegFilters.Filter objFilter**

```

```
   Method 2:
        'Dim f As IFilterClass
        Set f = catlist.Item(FilterIndex)
        FilterName = f.Name
        **Set objFilter = f.Create(CurrentGraph)**
```
