### ISSUE TITLE
dull colors in update 0.8.5.2268

### ISSUE THREAD

**Issue by SamerDesgin** [Aleksoid1978/VideoRenderer#175]
Hi , after this update the image is dull and washed out due too Auto Color Management, i use this feature and in prev updates the problem was there but it fixed when i use  RTX video HDR in mpc render, but in this update i cant workaround it no matter what i do and the only fix is to turn off the auto color management .  my monitor doesn't support HDR btw

**Comment by Aleksoid1978** [comment]
Auto Color Management is not available in the release version of Windows and there is no support for it in MPC VR. Stop writing about this.

**Comment by SamerDesgin** [comment]
but it was ok in the prev updates why is that ? i dont understand it correctly

**Comment by v0lt** [comment]
> but it was ok in the prev updates why is that ?

Please provide the previous version number of MPC VR and try again.

In any case, MPC VR does not have any support for Auto Color Management and is not planned to.

**Comment by Aleksoid1978** [comment]
Set **Convert to SDR**.
Uncheck **RTX Video HDR**.

**Comment by SamerDesgin** [comment]
> > but it was ok in the prev updates why is that ?
> 
> Please provide the previous version number of MPC VR and try again.
> 
> In any case, MPC VR does not have any support for Auto Color Management and is not planned to.

 0.8.3.2255 and most of the prev updates as far as i used .
 
 k it worked the way i did is to choose  texture format 8-bit integer other than that it will be dull . even with "Set Convert to SDR.
Uncheck RTX Video HDR" . also iwanna thank you  @Aleksoid1978  for this great project

**Comment by SamerDesgin** [comment]
i found a nother related cause of the problem, i cant use any shader now i tried many of them they all will make the video dull
