### ISSUE TITLE
PQ to SDR post-processing not getting enabled/disabled when switching to fullscreen and back

### ISSUE THREAD

**Issue by ACertainCoder** [Aleksoid1978/VideoRenderer#176]
Hi there, I noticed the following issue: when starting playback of an HDR video on a SDR display and then switching to fullscreen on a HDR monitor **without moving MPC-HC to that other monitor first**, causes the "PQ to SDR" post-processing to still apply. The HDR processing switches correctly to "passthrough". The same thing happens also when launching MPC-HC on an HDR monitor and then switching to fullscreen on a SDR monitor, but backwards: the "PQ to SDR" post-processing does not get applied.

Statistics on SDR monitor:
![grafik](https://github.com/user-attachments/assets/d47b9926-ff8d-4532-9b96-16c6e0c3a5c4)

Statistics on HDR monitor after switching to fullscreen while keeping player controls on SDR monitor:
![grafik](https://github.com/user-attachments/assets/85a7c76d-ad12-4294-a057-18e89751f11e)

Setup details:

Monitor 1: SDR
Monitor 2: HDR (1,000 nits)
Fullscreen separate controls: enabled
Fullscreen output device: monitor 2
Fullscreen action id: 830/831 (both affected)

MPC Video Renderer config:
![grafik](https://github.com/user-attachments/assets/00b74979-717a-4190-96c0-b37ec71f321a)

Originally reported here: https://github.com/clsid2/mpc-hc/issues/2978

**Comment by Aleksoid1978** [comment]
Set - "Reinitialize device..."

**Comment by Aleksoid1978** [comment]
I don't have 2 monitor's, can't help :)

**Comment by ACertainCoder** [comment]
Sadly "reinitialize device" doesn't fix it for me. Are there maybe some debug logs or something else I could provide you?

**Comment by Aleksoid1978** [comment]
You can guess as much as you want - but without 2 monitors this problem cannot be solved. I only have 1.

**Comment by Aleksoid1978** [comment]
Try check "Use exclusive fullscreen".

**Comment by ACertainCoder** [comment]
Exclusive fullscreen doesn't fix it either. I only know the basics of C++ but looking through the source code, it seems like `m_strCorrection` in DX11VideoProcessor/DX9VideoProcessor is only ever reset if `ReleaseVP()` gets called, which happens in `ReleaseDevice()` and conditionally in `InitMediaType(...)`.

I tried to enable DirectShow logging based on the [this article](https://learn.microsoft.com/en-us/windows/win32/directshow/debug-output-functions) by Microsoft, but couldn't get it to work. With proper logging, I could maybe print out some variables to figure out which ones don't get updated properly. Do you maybe know how to get this to work or is there a way to debug it via Visual Studio itself?

**Comment by ACertainCoder** [comment]
My DirectShow registry entries:
![grafik](https://github.com/user-attachments/assets/7e98444f-a8b8-4f67-b853-e9877c55dd0d)

**Comment by v0lt** [comment]
[MpcVideoRenderer-0.8.5.2268_**Debug**.zip ](https://github.com/Aleksoid1978/VideoRenderer/releases/tag/0.8.5)
[DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)

**Comment by ACertainCoder** [comment]
👍 Thanks, got it working. Here is the output when switching to fullscreen on the different monitor:
![grafik](https://github.com/user-attachments/assets/4b0e3d05-37c5-4f6d-9035-de2ea65561eb)

It seems that neither `ReleaseDevice()` nor `InitMediaType(...)` get called, causing the filter to stilll apply.

**Comment by ACertainCoder** [comment]
Found the problem! Creating a pull request soon...

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip](https://github.com/user-attachments/files/16571150/MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip)
Check this build.

**Comment by ACertainCoder** [comment]
Your build only fixes it with "Exclusive fullscreen" enabled. If this option is disabled, the problem still occurs. With my own build, containing the changes from https://github.com/Aleksoid1978/VideoRenderer/pull/178, this was also fixed.

**Comment by Aleksoid1978** [comment]
Your pull request is incorrect.

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip](https://github.com/user-attachments/files/16571208/MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip)
Try this build.
Use **Exclusive fullscreen** or **Reinitialize device...**.

**Comment by ACertainCoder** [comment]
Can you give me feedback on what's exactly incorrect?
This updated build works like your last one only in exclusive fullscreen, although now the image is completely black (not even the statistics are rendered) if it's disabled.

**Comment by Aleksoid1978** [comment]
https://github.com/Aleksoid1978/VideoRenderer/pull/178/commits/7a9d90401b9fddadc75aa03b04b6c0b928c7bfb4
This is wrong. Code only for Exclusive fullscreen but you disable check.

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip](https://github.com/user-attachments/files/16571230/MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233.zip)

**Comment by ACertainCoder** [comment]
> This is wrong. Code only for Exclusive fullscreen but you disable check.
Ok, it didn't give me any errors so I thought it was fine.

Your latest build behaves just like the last one.
Exclusive fullscreen: successful switch to HDR
Non-exclusive fullscreen: blackscreen without any statistics

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233_Debug.zip](https://github.com/user-attachments/files/16571242/MpcVideoRenderer-0.8.6.2275_git2024.08.06-ab77233_Debug.zip)
Debug build - give me log.

**Comment by ACertainCoder** [comment]
Here you go:
![grafik](https://github.com/user-attachments/assets/5a263550-8033-46d5-bdc7-25dcab1f1610)

![grafik](https://github.com/user-attachments/assets/6d4bf3bc-ddaf-464d-b640-83e9ff0294e6)

**Comment by Aleksoid1978** [comment]
[diff.zip](https://github.com/user-attachments/files/16571276/diff.zip)
If you can debug in Visual Studio - apply this patch and check where is assertion.

**Comment by ACertainCoder** [comment]
Will check tomorrow as it's late in the night in my country. Wasn't able to attach a debugger so far as Visual Studio always tells me that the AX file isn't an executable.

**Comment by Aleksoid1978** [comment]
You need run player and then attach to process.

**Comment by Aleksoid1978** [comment]
Test latest commit - for me it's working.
Swap effect - change to "Flip".

**Comment by ACertainCoder** [comment]
Same Debug Assertion as yesterday. This happens whether exclusive fullscreen is enabled or not.
https://drdump.com/UploadedReport.aspx?DumpID=131609139

Got the debugger working and the error occurs in this line, the second time it gets called during the transition to fullscreen on the different display:
![grafik](https://github.com/user-attachments/assets/f17a6737-e20d-429d-8b2c-eed1ecaf5c77)

**Comment by ACertainCoder** [comment]
Corresponding log output:
![grafik](https://github.com/user-attachments/assets/672074e6-2f77-4dbd-88e5-fe31b892afb4)

**Comment by Aleksoid1978** [comment]
I don't know what's wrong - for me all is good, can't help.

**Comment by Aleksoid1978** [comment]
Use "Exclusive fullscreen".

**Comment by ACertainCoder** [comment]
I will try debugging a bit more later. If you like, we could also do a Discord call or something to test this together sometime.

**Comment by Aleksoid1978** [comment]
I don't care about MPC-HC :)

**Comment by Aleksoid1978** [comment]
MPC-VR support use separate window, check in MPC-BE.

**Comment by ACertainCoder** [comment]
> I don't care about MPC-HC :)

This issue also affects MPC-BE, just checked. 😜

> Maybe this helps:
> `if (hwnd == m_hWndParent) { m_bIsD3DFullscreen = true; }`

Sadly it didn't.

After some debugging I noticed that due to the `initMediaType` call within `InitSwapChain`, latter function gets called twice, causing `CreateSwapChainForHwnd` to also get executed two times. Returning after `initMediaType` fixes the assertion error for me.
![grafik](https://github.com/user-attachments/assets/1dc5de7d-c1e2-4f45-8b70-4f6098ce4b54)

**Comment by ACertainCoder** [comment]
Also I noticed that in the video renderer, the following `Init` call seemingly hasn't been updated. I added the `true` argument in my source code.
![grafik](https://github.com/user-attachments/assets/5885553d-f97b-498c-b850-87bacf8e3132)

**Comment by ACertainCoder** [comment]
Do you think that these changes would be ok? If so, I can create another pull request if you like.

**Comment by Aleksoid1978** [comment]
> Also I noticed that in the video renderer, the following `Init` call seemingly hasn't been updated. I added the `true` argument in my source code. ![grafik](https://private-user-images.githubusercontent.com/47316898/356897247-5885553d-f97b-498c-b850-87bacf8e3132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MTU0OTIsIm5iZiI6MTcyMzQxNTE5MiwicGF0aCI6Ii80NzMxNjg5OC8zNTY4OTcyNDctNTg4NTU1M2QtZjk3Yi00OThjLWI4NTAtODdiYWNmOGUzMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIyMjYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzJjMjQ2MTNhMDEwODc3ZjljZmJkNDdlODFhNTc1OGNlZjgxYjJmZDAwYzQyOWE1YTY2YTIyMmRiMWU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrSwiFW_f4zIcrErwQ5bDAQpC1UirJ2c4IqG0DuSIQg)

And here there is no need.

**Comment by Aleksoid1978** [comment]
If I can't reproduce the problem myself, then no pull request will help, and of course I won't accept them.
You can "fix" it for yourself and use it.

**Comment by Aleksoid1978** [comment]
> > > Also I noticed that in the video renderer, the following `Init` call seemingly hasn't been updated. I added the `true` argument in my source code. ![grafik](https://private-user-images.githubusercontent.com/47316898/356897247-5885553d-f97b-498c-b850-87bacf8e3132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MTU0OTIsIm5iZiI6MTcyMzQxNTE5MiwicGF0aCI6Ii80NzMxNjg5OC8zNTY4OTcyNDctNTg4NTU1M2QtZjk3Yi00OThjLWI4NTAtODdiYWNmOGUzMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIyMjYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzJjMjQ2MTNhMDEwODc3ZjljZmJkNDdlODFhNTc1OGNlZjgxYjJmZDAwYzQyOWE1YTY2YTIyMmRiMWU5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrSwiFW_f4zIcrErwQ5bDAQpC1UirJ2c4IqG0DuSIQg)
> > 
> > 
> > And here there is no need.
> 
> Seems wrong to me. Second function parameter is missing. Only the changedevice parameter is optional due to its default value.

Yes - thx.

**Comment by Aleksoid1978** [comment]
[MpcVideoRenderer-0.8.6.2278_git2024.08.12-b0d41f7_Debug.zip](https://github.com/user-attachments/files/16576470/MpcVideoRenderer-0.8.6.2278_git2024.08.12-b0d41f7_Debug.zip)
Debug build. I need log - in DbgView -> File -> Save As and upload here, not screenshot :)

**Comment by ACertainCoder** [comment]
> @ACertainCoder In `CDX11VideoProcessor::InitSwapChain()` move down the line `ReleaseSwapChain()` till after the block containing `InitMediaType`. I think that should fix it as well?

Also fixes the issue in MPC-HC and MPC-BE.

> [MpcVideoRenderer-0.8.6.2278_git2024.08.12-b0d41f7_Debug.zip](https://github.com/user-attachments/files/16576470/MpcVideoRenderer-0.8.6.2278_git2024.08.12-b0d41f7_Debug.zip) Debug build. I need log - in DbgView -> File -> Save As and upload here, not screenshot :)

This build no longer gives me an assertion error. Here's the log file:
[MPCVR-b0d41f7.LOG](https://github.com/user-attachments/files/16590011/MPCVR-b0d41f7.LOG)
