### ISSUE TITLE
DV works less than a second when in fullscreen, but works in windowed mode

### ISSUE THREAD

**Issue by fcueto** [Aleksoid1978/VideoRenderer#177]
When I play DV content using mpc-hc 2.3.4 it is working and improves image quality considerably, but... it stops working in full-screen mode unless the seekbar is showing.

my settings:
![settings](https://github.com/user-attachments/assets/43f03ab9-7f42-419a-bc86-f98327fe13bc)

Capture of the screen. DV works for less than a second then it disable (when in fullscreen)
<img width="1920" alt="fullscreen2" src="https://github.com/user-attachments/assets/57cb97ba-81cc-4b25-b93e-c768ffdec8dd">

In windowed mode DV works normally
<img width="1747" alt="notfullscreen" src="https://github.com/user-attachments/assets/efd0ecf9-1632-49e1-96eb-1061478c2f17">

**Comment by fcueto** [comment]
In case you want to know, "Prefer DV over PQ and HLG" makes no difference.

**Comment by v0lt** [comment]
I don't see any difference in color or statistics

**Comment by fcueto** [comment]
me neither but I don't know if what I capture is what I see on the screen?

**Comment by v0lt** [comment]
Try looking at DolbyVision Profile 5 samples. It will immediately be clear whether DolbyVision processing works or not.
https://www.demolandia.net/4k-video-test/dolby-vision/page-1.html

**Comment by fcueto** [comment]
windows calibration tool has no effect. I tried with extreme values just to be sure but not effect at all.

When in windowed mode, DV seems to remain active.
When in fullscreen mode, it works during a fraction of a second then DV goes off (my monitor removes the DV label right away)
If I use the arrow keys to get back or forward, it activates DV again during .2 second and it goes off again.

**Comment by fcueto** [comment]
my monitor is asus pg32ucdm with firmware 105

**Comment by fcueto** [comment]
colors are great on Profile 5 samples

**Comment by fcueto** [comment]
what you said about HDR metadata seems to be correct but I don't get why I see no difference playing with the HDR calibration tool.
Maybe when windows 11 detects a DV capable display, it uses different metadata than the HDR calibrated ones ?

**Comment by fcueto** [comment]
I get that but does it affect how the desktop looks in DV mode ? (because when HDR is activated, windows 11 is sending a DV signal when a compatible display is detected).

**Comment by Aleksoid1978** [comment]
You can't output DV passthrough on Windows, only HDR.
MPC-VR read DV rpu and convert DV colors to PQ. That's all.
