### ISSUE TITLE
HEVC 60fps 10bit sdr RTX Video HDR inactive

### ISSUE THREAD

**Issue by starmonker** [Aleksoid1978/VideoRenderer#179]
MPCVR 0.8.6.2275 .nvidia 560.81

Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/dby1/iso2/mp41)
File size                      : 16.4 GiB
Duration                       : 1 h 38 min
Overall bit rate               : 23.8 Mb/s
Frame rate                     : 60.000 FPS
Movie name                     : 白蛇：缘起(2019)
Writing application            : QHstudIo
Copyright                      : HD Dolby
Cover                          : Yes
Comment                        : 8E12C0A578AE317E246ABFFC7679CD5C

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@Main
Codec ID                       : hev1
Codec ID/Info                  : High Efficiency Video Coding
Duration                       : 1 h 38 min
Bit rate                       : 23.2 Mb/s
Width                          : 3 840 pixels
Height                         : 1 616 pixels
Display aspect ratio           : 2.39:1
Frame rate mode                : Variable
Frame rate                     : 60.000 FPS
Minimum frame rate             : 59.960 FPS
Maximum frame rate             : 60.040 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.062
Stream size                    : 16.0 GiB (97%)
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709
Codec configuration box        : hvcC

![789](https://github.com/user-attachments/assets/ab386c18-4e47-450f-b3c9-1071628a3ef7)

**Comment by Aleksoid1978** [comment]
Check P010/P016.

**Comment by starmonker** [comment]
thanks
