### ISSUE TITLE
Please add HDR support

### ISSUE THREAD

**Issue by z826540272** [Aleksoid1978/VideoRenderer#18]
i have a hdr screen，
Do you plan to add hdr support?
Just like the hdr metadata passthrough of madvr
i dont use madvr because high overhead.

**Comment by Aleksoid1978** [comment]
Yes it's planned. But currently i don't have screen with HDR & collecting money to buy it.

**Comment by cdytoby** [comment]
I can help testing it, I have one. But I'm not a professional c++ dev.

**Comment by Aleksoid1978** [comment]
Add.
