### ISSUE TITLE
Fullscreen windowed not activated

### ISSUE THREAD

**Issue by zh4ngx** [Aleksoid1978/VideoRenderer#180]
Going fullscreen (pressing the fullscreen button on MPC) during playback does not activate "fullscreen windowed" mode. Instead, the mode doesn't change at all (it continues to say "primary windowed"). For comparison, MadVR will go into fullscreen windowed under the same circumstances.

The only to get "fullscreen" is to switch on exclusive mode, but then you lose mouse control and the ability to hover over the seek bar to show it on demand.

A few questions:

1. Is this intended behavior?
2. Is what is happening in exclusive mode also expected behavior?
3. If no to 1. and 2., is there a mode switch that should happen in MPC-VR when going fullscreen in MPC?

**Comment by Aleksoid1978** [comment]
Yes - it is intended behavior.
