### ISSUE TITLE
Maximum luminance capped with “P010/P016” enabled

### ISSUE THREAD

**Issue by OneMoreAccForMe** [Aleksoid1978/VideoRenderer#181]
Hi together,
when watching a movie in HDR10 and “P010/P016” in the “DXVA2 and D3D11 video processor” settings enabled, highlights aren’t very bright. It seems the maximum luminance is capped.
When disabling the “P010/P016” setting, the highlights get much brighter. (see images)
Is this the intended behavior? Why does the “P010/P016” setting affect maximum luminance?

Maybe related:
When watching a movie with a Dolby enhancement layer and “P010/P016” enabled and “Prefer Dolby Vision over PQ and HLG” enabled, peak luminance seems correct.
When disabling “Prefer Dolby Vision over PQ and HLG” the maximum luminance level drops. (see 2. image)

Setup:
MPC-BE 1.7.3 with MPC VR 0.8.5.2268 
AMD Ryzen 5 PRO 4650G connected to LG CX TV

1
![p010_p016issue](https://github.com/user-attachments/assets/22d90369-05ae-48ab-b1b0-b9bb38e4aea7)

2
![prefDVissue](https://github.com/user-attachments/assets/e7e8658a-d622-4324-8ea5-15c291a75d1f)

**Comment by Aleksoid1978** [comment]
When check "Prefer Dolby Vision over PQ and HLG" - MPC VR use shaders instead of Video Processor.

**Comment by OneMoreAccForMe** [comment]
Understood, thanks!
But why does the "P010/P016" setting make a difference when the "Prefer Dolby Vision over PQ and HLG" is off?
Shouldn't the peak brightness be the same?

**Comment by v0lt** [comment]
> When watching a movie with a Dolby enhancement layer and “P010/P016” enabled and “Prefer Dolby Vision over PQ and HLG” enabled, peak luminance seems correct.
> When disabling “Prefer Dolby Vision over PQ and HLG” the maximum luminance level drops. (see 2. image)

Your video has two display output options: DolbyVision and HDR10 compatible. Naturally, there may be different parameters because electronics manufacturers need to sell TVs.

> When disabling the “P010/P016” setting, the highlights get much brighter. (see images)
> Is this the intended behavior? Why does the “P010/P016” setting affect maximum luminance?

We don't know. If you or anyone knows the reason, please tell us what's going on here. If there is a bug, we'd like to see a patch.

**Comment by OneMoreAccForMe** [comment]
I found that the issue is related to the AMD video processor.

With Nvidia grafics:
“P010/P016”, “Prefer Dolby Vision over PQ and HLG”, shaders or D3D11 VP --> does not make any difference in peak brightness. Everything seems OK

With AMD grafics:
“Prefer Dolby Vision over PQ and HLG - ON”  uses shaders with DV movie --> OK
“P010/P016 - OFF" uses shaders --> OK
“P010/P016 - ON" uses D3D11 VP --> NOK

The comment from Aleksoid1978 led me in the right direction. It seems that with shaders the peak brightness is correct but as soon as D3D11 VP is used with AMD the peak brightness is capped.

Is this an issue in MPC VR or is this something that needs to be addressed to AMD directly?

**Comment by Aleksoid1978** [comment]
It's driver issue.

**Comment by v0lt** [comment]
There are settings in the video renderer. Change the settings to get the best result. This is done specifically to solve your problems. There is no ideal configuration to make everyone happy.
