### ISSUE TITLE
mpcvr fullscreen cause windows font rendering change in HDR mode

### ISSUE THREAD

**Issue by muyangwang** [Aleksoid1978/VideoRenderer#183]
Hi, 
I have been using mpcvr for some time and really love it. Recently I want to try some HDR things and some issues get in my way. I would appreciate it if you could take a look.

The issue is if you play a video in full-screen mode with mpcvr, the windows desktop font quality will degrade after that. (become thinner, not smooth with small glitches).

My phone's camera sharpened the image taken automatically, so it actually looks much worse than the picture below. But you can still see "5" is rendered poorly. (Screenshots are not affected, only onscreen display)
Correct display:
![image1](https://github.com/user-attachments/assets/f44c00f1-f211-4a0f-9fb2-86d693ca929c)
Wrong display:
![image0](https://github.com/user-attachments/assets/94482503-41c0-433d-b0ad-260b319cacbf)

This happened if:
1. Windows HDR on
2. Played any videos (HDR or SDR, I tested a few, made no difference), make it full screen (either exclusive fullscreen or not).

This could be fixed if:
1. turn Windows HDR off and on again.

I tested 4 scenarios:
1. MPC-HC 2.3.5 with MPC Video Renderer 0.8.6.2282 (git-2024.08.31-06097d7) x64
2. MPC-HC 2.3.5 with EVR
3. Potplayer 1.7.22289 with MPC Video Renderer 0.8.5.2268 x64
4. Potplayer 1.7.22289 with built-in D3d11 Video Render

Only 1 and 3 caused font rendering change. 

A few system information if you need:
Windows 11 23H2, I tried to update to 24H2 yesterday, made no difference.
Nvidia graphic card, newest driver.
Display: LG 32gq950, with HDR support.

mpcvr setting:
![Screenshot 2024-09-13 210433](https://github.com/user-attachments/assets/b7e748a9-0fa8-4ea1-81bc-3fafa6da8a0a)

**Comment by Aleksoid1978** [comment]
Maybe you should think before asking questions?
MPC VR has nothing to do with this and cannot have anything to do with it.

**Comment by muyangwang** [comment]
> Maybe you should think before asking questions? MPC VR has nothing to do with this and cannot have anything to do with it.

I am sorry it may look stupid, but this is what I actually experienced. I did a few tests before I decided to put this post, since switching to other renderer won't cause the same problem. I wonder if the renderer interact with any of the windows hdr settings?
