### ISSUE TITLE
HVEC x265 encoded content chroma issue (RTX Super Resolution ON only)

### ISSUE THREAD

**Issue by MasterEmerald** [Aleksoid1978/VideoRenderer#184]
Not sure if this is an issue with MPCVR or MPC-BE, video driver, windows build, or combination of factors,
but recently I've noticed that content encoded with x265/HVEC outputs crushed colors, and has chroma issues when the video frame is scaled to 100% or more and/or the video is outputting in full-screen. x264 and VVC/H.266/x266 encoded material has no such issue. 

![bad_x265_10bit_100](https://github.com/user-attachments/assets/b2aede2d-e0ee-406d-af61-dc3091272ae6)
![bad_x265_90](https://github.com/user-attachments/assets/2780457d-8c08-444c-8df4-ab03dd260c3b)
![bad_x265_100](https://github.com/user-attachments/assets/a6e38164-6da7-49d9-8a4e-172528f54d03)
![bad_x265_105](https://github.com/user-attachments/assets/e3a7910f-ea8b-4fd4-8d50-d1f92a7e0fc0)
![good_x264_100](https://github.com/user-attachments/assets/465c2b1f-d12c-4b04-a23d-87cc88755368)
![good_x264_110](https://github.com/user-attachments/assets/cc03ead2-0feb-4dac-a337-ef285a20ef18)
![good_x265_10bit_99](https://github.com/user-attachments/assets/879202fc-187b-4d8f-a08d-dba1ff4130de)
![good_x265_890](https://github.com/user-attachments/assets/f0624325-8ebf-4b4c-8d90-f4cdf0f30437)

**Comment by Aleksoid1978** [comment]
Show filter list in MPC-BE.

**Comment by v0lt** [comment]
Please provide detailed Windows version.
Please provide video driver version.

**Comment by MasterEmerald** [comment]
Thanks guys! See attached, default filters and latest drivers. 
I've noticed this for the past few (at least) Nvidia driver releases... not sure if it was there before.
Finally saw something changing when I started resizing the video frame window so figured I'd share.

PS - MPC-HC -> MPC-BE and MPCVR are hands down the BEST pieces of video playback software around.
Been using both for years, decade+ where applicable. Amazing work!
![Screenshot 2024-09-15 072828](https://github.com/user-attachments/assets/e75c0246-d7ac-4596-b1ff-94880c6ba2e1)
![Screenshot 2024-09-15 072850](https://github.com/user-attachments/assets/991aa287-ef65-4f4b-a8f9-8e7343c5d2a3)
![Screenshot 2024-09-15 073042](https://github.com/user-attachments/assets/0f8d364d-8183-4a10-96b6-19cb615340c6)
![Screenshot 2024-09-15 073120](https://github.com/user-attachments/assets/fd59912a-51c0-4fe0-9461-c5d95ce2ad05)
![Screenshot 2024-09-15 073159](https://github.com/user-attachments/assets/156efa02-b2e6-45b0-b6e3-8639e379daf7)
