### ISSUE TITLE
MPC video renderer won't switch to HDR mode if RGB 10bit is selected on Nvidia Control Panel

### ISSUE THREAD

**Issue by xatornet** [Aleksoid1978/VideoRenderer#186]
My issue is that If I'm using this config in SDR mode:

![image](https://github.com/user-attachments/assets/3b0557b9-a340-4924-8827-a7296fac7006)

Then, DisplayInfo will tell that I'm using HDR:

![image](https://github.com/user-attachments/assets/55f0e2bc-aa59-4cbc-a4e6-bb6954022256)

When I'm really not using it.  So MPC won't switch on HDR automatically whenever I use a HDR movie:

![image](https://github.com/user-attachments/assets/3851233d-f464-4019-92a8-489e658a630a)

If I select SDR 8bit mode on nvidia panel, everything works.

![image](https://github.com/user-attachments/assets/5336008c-e470-4467-ae3a-aa7e38ed9a45)
![image](https://github.com/user-attachments/assets/cdf1e4a9-d810-45b1-a6fb-73cd4ce70ba1)
![image](https://github.com/user-attachments/assets/1cbfdd9c-8f40-4cc3-ae45-bc93df4c403b)

**Comment by Aleksoid1978** [comment]
We "don't" support 24H2.

**Comment by xatornet** [comment]
![i-know-you-will-i-believe-in-you](https://github.com/user-attachments/assets/be1436bb-779f-496f-91c6-9782d681232c)

**Comment by xatornet** [comment]
> Automatically manage color for apps

Yeah, the thing is... I don't have that option....

![image](https://github.com/user-attachments/assets/2dd69910-33b9-44ef-93d5-40d21d535fc4)
