### ISSUE TITLE
Issue: Frame Rate Limitation in MPC Video Renderer

### ISSUE THREAD

**Issue by flowreen** [Aleksoid1978/VideoRenderer#187]
Hello,

I found an old comment in a forum thread mentioning that the frame rate of the MPC Video Renderer has been limited since version 0.7.3.2210. The comment states that earlier versions, like 0.7.1.2172, were still able to achieve the desired frame rates:
https://mpc-be.org/forum/index.php?topic=381.msg8818#msg8818

I downloaded the latest development build, but the issue still persists in the latest nightly version using default settings. Here's a screenshot showing the configuration set to output video frames at 1124 fps, yet the MPC Video Renderer caps it at 130 fps:
https://gyazo.com/71b33f92ba2de0b868609c907389653f

In contrast, when I switch to Enhanced Video Renderer, the video reaches the correct frame rate:
https://gyazo.com/d168df830631f8b6184c55a6e6140491
This shows that the latest MPC itself can handle higher frame rates, but the limitation seems specific to MPC Video Renderer.

Could you please review the changes between these two versions and identify if a frame cap was introduced? It would be great if this could be reverted or adjusted to allow for higher frame rates.

Additional Note:

On the forum, a developer suggested that a high refresh rate monitor might be needed to resolve this issue:
https://mpc-be.org/forum/index.php?msg=8873
However, as shown in my screenshots, I’m using a 240 Hz monitor, and the MPC statistics clearly indicate that the renderer should be able to exceed that limit. Therefore, the monitor's refresh rate doesn't appear to be the cause of the problem.

Thank you for your time and consideration!

**Comment by Aleksoid1978** [comment]
Yes, it does limit and no changes are planned.

**Comment by v0lt** [comment]
> In contrast, when I switch to Enhanced Video Renderer, the video reaches the correct frame rate:
> https://gyazo.com/d168df830631f8b6184c55a6e6140491

EVR statistics are deceiving you. It is impossible to display more frames than the display frequency allows.

**Comment by flowreen** [comment]
> > In contrast, when I switch to Enhanced Video Renderer, the video reaches the correct frame rate:
> > https://gyazo.com/d168df830631f8b6184c55a6e6140491
> 
> EVR statistics are deceiving you. It is impossible to display more frames than the display frequency allows.

Correct. The point here is that even without the required hardware that allows you to physically see them, the video player should still try to display all the frames that it's given to it while vsync is OFF.
With vsync ON it should cap the frame rate at your monitor display frequency:
https://gyazo.com/c0f92f2219b0847ec6bd869b8a4e489f
Current issue is that it caps it way lower than that and we don't have any checkbox like EVR has to disable it.

**Comment by Aleksoid1978** [comment]
I have no restrictions on my monitor with a frequency of 60.
And the developers don't have monitors with a frequency of >= 120.
If you want to fix it, you can provide the developers with the necessary equipment.

**Comment by flowreen** [comment]
Hmm i think you're right. I want to try more stuff first.
Meanwhile please ask one of your developers to add me on discord with username:
flowreen
Thanks!

**Comment by Aleksoid1978** [comment]
We don't use discord :)

**Comment by flowreen** [comment]
Skype? Whatsapp? Pidgeon mail?

**Comment by flowreen** [comment]
GG easy fix:
https://gyazo.com/09e2e7fc38bbd664c03de0399931a7ad

**Comment by v0lt** [comment]
> GG easy fix:
> https://gyazo.com/09e2e7fc38bbd664c03de0399931a7ad

You just disabled other functionality and broke the playback of interlaced video.

Issue #45 - Deinterlacing not working well on high frequency displays (144 Hz)
Pull request #130 - implement simplified frame syncing (fix issue #45)

> For a better fix, please check ChatGPT suggestions:
> https://chatgpt.com/share/66f46c78-d91c-800b-bf61-385fd5018c3d

I think it's stupid and inappropriate. But no one is stopping you from creating a fork of MPC VR and modifying it as you need using ChatGPT.

**Comment by v0lt** [comment]
In commit b8ab79f (0.8.6.2289), the "Adjust the frame presentation time" setting was added.

**Comment by flowreen** [comment]
Nice solution!
I tested and works.
Default is active so gets capped.
Unchecking the checkbox correctly prevents the frame syncing and fps goes up to monitor's refresh rate of 240 fps.
Thanks a lot!
