### ISSUE TITLE
When playing a video with Dolby Vision Profile 7 or Profile 5 specifications, the video will suddenly darken when switched to fullscreen

### ISSUE THREAD

**Issue by funnybones2015** [Aleksoid1978/VideoRenderer#188]
This issue is as stated in the title, and I've tried many methods but couldn't resolve it.

**Comment by funnybones2015** [comment]
It's not that the entire video has become darker; it seems that the contrast of the image has increased, making the dark areas darker, which has caused details in the shadows that were originally visible to be obscured.

**Comment by Aleksoid1978** [comment]
Don't confirm.
Show screenshots with statistics.

**Comment by Aleksoid1978** [comment]
I compare in window, in fullscreen and exclusive fullscreen. Everything is the same.
Window:
![изображение](https://github.com/user-attachments/assets/2edb99ae-a84e-4ee8-840d-4b848a9f3d8b)

Fullscreen:
![Fullscreen](https://github.com/user-attachments/assets/4b8fefb1-79aa-4745-bdf9-4e43da1bb557)

Exclusive fullscreen:
![FullscreenExclusive](https://github.com/user-attachments/assets/40c6c8a2-3f59-4208-9cd5-6bfef8a5dc15)

**Comment by funnybones2015** [comment]
It seems that playing Profile 5 video alone is fine, but if Profile 5 is played after a Profile 7 video has darkened, the tone follows and also becomes darker. The Profile 7 video doesn't always darken in fullscreen; sometimes, after restarting the monitor or resetting the graphics card driver, full-screen playback doesn't result in darkening. This issue doesn't occur 100% of the time; it happens with a certain probability. I'll take a screenshot for you next time the issue recurs.

**Comment by Aleksoid1978** [comment]
This looks like some local problem - maybe drivers, maybe the system, maybe some software.
MPC-VR has 100% nothing to do with it.

**Comment by funnybones2015** [comment]
> This looks like some local problem - maybe drivers, maybe the system, maybe some software. MPC-VR has 100% nothing to do with it.

But I tried MPC-BE, MPC-HC and Potplayer etc with MPC-VR using both windows 11 23h2 and 24h2, and resetting the Nvidia drivers, etc. It still happens sometimes. When using these player with other video renderer, this error never occurred.

**Comment by funnybones2015** [comment]
> In HDR mode the same.

The issue occurred again today. Please see the comparison in the screenshots below: one shows the default playback effect, and the other shows the dimmed effect after switching to full screen. They both played with the HDR mode enabled in win 11.
@clsid2  FYI：

![微信图片_20241011191838](https://github.com/user-attachments/assets/5bfdfe9b-58b8-42ed-8562-a90e1cdc96af)
![微信图片_20241011191848](https://github.com/user-attachments/assets/be8fdf0e-461c-46a7-8b30-e06d5f7f9e92)

**Comment by funnybones2015** [comment]
> https://support.microsoft.com/en-us/windows/hdr-settings-in-windows-2d767185-38ec-7fdc-6f97-bbc6c5ef24e6 Test if changing `SDR content brightness` or `HDR content brightness` setting makes any difference.
> 
> The specs of that monitor says it has a brightness sensor. So look in Windows settings and disable `dynamic brightness`. That adjusts brightness based on light intensity in your room.

Dynamic brightness was disabled in OSD menu in the monitor before. I guess changing SDR and HDR brightness may not work, since the darkening when entering full screen happens sometimes, not always. Thank you for your kind suggestion~~

**Comment by funnybones2015** [comment]
> https://www.tenforums.com/tutorials/70157-enable-disable-adaptive-brightness-windows-10-a.html
> 
> And if you have Intel CPU, then look in Intel GPU settings, because that also has dynamic brightness feature that is often enabled by default.
> 
> Running on battery instead of power cord can also affect brightness, see Windows Power settings.

Thanks for your kind reply. My laptop is equipped with an AMD 7840H processor and is connected to a 27-inch 4K HDR 1000 mini LED monitor, with the laptop plugged into power, not running on battery.
