### ISSUE TITLE
Color Error with RTX SR and Win11 24H2 SDR ACM

### ISSUE THREAD

**Issue by BallanceHZ** [Aleksoid1978/VideoRenderer#189]
MPC-BE version：1.8.0
MPC-VR version：0.8.7.2295
ISSUE：in SDR and Windows 11 24H2 ACM on，when using RTX SR，the color will go wrong. Disable RTX SR then color is right.

RTX SR on：
![image](https://github.com/user-attachments/assets/94cb5141-56b6-4c95-863d-ffa523eeaa18)
RTX SR off：
![image](https://github.com/user-attachments/assets/46fae580-8c84-46f4-aeae-417db3b73078)

video in chrome has no problem with RTX SR on

**Comment by v0lt** [comment]
Try selecting Texture format = 8-bit Integer.

**Comment by BallanceHZ** [comment]
> Try selecting Texture format = 8-bit Integer.

![image](https://github.com/user-attachments/assets/ba09c80c-f9d0-4338-ab5f-7c810c7f6efa)
8bit integer indeed fixed the color，but i consider this still is a problem？

**Comment by v0lt** [comment]
> 8bit integer indeed fixed the color，but i consider this still is a problem？

Yes. The problem is in the driver.

**Comment by v0lt** [comment]
Added information on Texture format to [Known Issues](https://github.com/Aleksoid1978/VideoRenderer/wiki/Known-Issues).
