### ISSUE TITLE
MPC-HC support

### ISSUE THREAD

**Issue by Zero3K** [Aleksoid1978/VideoRenderer#19]
Is it possible to get support for MPC-HC added to it (since MPC-BE hasn't been developed in a while)?

**Comment by Aleksoid1978** [comment]
MPC-BE hasn't been developed in a while ? This is a joke ?

About MPC-HC - i think you need ask MPC-HC's developers.

**Comment by Zero3K** [comment]
1. Well, I don't see a new nightly release.
2. It turns out that its fully supported in MPC-HC thanks to the guy who resumed development of it.

**Comment by Aleksoid1978** [comment]
Latest MPC-BE SVN version here - https://yadi.sk/d/hlf1lfC8mKU58/!_last
