### ISSUE TITLE
RTX Video HDR went crazy after updating to driver 566.03

### ISSUE THREAD

**Issue by k6G52m4Dz75W** [Aleksoid1978/VideoRenderer#190]
As the subject suggests, the RTX Video HDR function sometimes works while in most time doesn't. And the case varies in fullscreen and window mode. The color often appears washed out or oversaturated. If the texture format is manually set to 8 bit integer, the color will get more shiny in 1-2 seconds after the windows is switched to full screen.
Tested with the latest MPC-BE.1.8.0.18_git2024-10-20-7d32a542d and MpcVideoRenderer-0.8.8.2296_git2024.10.16-8ba736f.

**Comment by v0lt** [comment]
Disable "Automatically manage color for apps" in Windows 11 settings or use Windows 10.

**Comment by v0lt** [comment]
If you think it was fine with the previous driver version, then it's probably a driver issue, not a video renderer issue.

**Comment by k6G52m4Dz75W** [comment]
> Disable "Automatically manage color for apps" in Windows 11 settings or use Windows 10.

Tried but with the same result. And as it plays fine if you drag and drop video in the latest Edge/Chrome, maybe it is not a bug in the driver but some internal change occurrs.

**Comment by Aleksoid1978** [comment]
I don't confirm - checked with 566.03 drivers.

**Comment by v0lt** [comment]
> maybe it is not a bug in the driver but some internal change occurrs.

You wrote it yourself "went crazy after updating to driver 566.03".
