### ISSUE TITLE
Bug: Super Resolution Color Degradation on 10Bit movies, Works fine on 8Bit movies or if 8Bit is Enforced

### ISSUE THREAD

**Issue by Wontell** [Aleksoid1978/VideoRenderer#191]
Hello,
I found a bug related to Super Resolution
To make it clear, i posted screenshots below with stats visible:

1] 10Bit/rec.709 Encoded video, ALWAYS degraded color is super resolution enabled and default AUTO settings used or 10-Bit Integer selected.
Auto 8/10Bit = Degraded color
8-Bit Integer = Correct Color
10Bit = Degraded color
16Bit = Degraded color

2] 8Bit/rec.709 Encoded Video, works fine if set to Auto 8/10Bit and 8Bit.
Auto 8/10Bit = Correct Color
8-Bit Integer = Correct Color
10Bit = Degraded color
16Bit = Degraded color

**Update**: Real 10Bit video like HDR video that have BT.2020 work fine under Auto 8/10 bit and 10Bit modes, no color degradation.

Basically the issue is with 8Bit/REC.709 videos that got encoded as 10Bit to enhance encoding quality.

FIX: If you can make it so if MPC Renderer detects rec.709 video, it AUTOMATICALLY forces 8Bit mode, even if setting set to 10Bit.
This should fix it permanently and let us use 10bit mode for HDR videos

10Bit/rec.709 Video, Default Settings + Super Resolution Enabled, Auto 8/10Bit enabled, Degraded Color 
![10Bit_1](https://github.com/user-attachments/assets/bd4215a8-d93a-4985-a0f4-ed8d6a33c503)

10Bit/rec.709 Video, Default Settings + Super Resolution Enabled, 10Bit enabled, Degraded Color 
![10Bit_2](https://github.com/user-attachments/assets/8d457320-9dce-4cf7-9d49-dfa110d752d9)

10Bit/rec.709 Video, Default Settings + Super Resolution Enabled, 8Bit enabled, Correct Color 
![10Bit_3](https://github.com/user-attachments/assets/0b25c6f9-a380-401d-8c9a-543d9219c2e6)

8Bit/rec.709 Video, Default Settings + Super Resolution Enabled, Auto 8/10Bit enabled, Correct Color 
![8Bit_1](https://github.com/user-attachments/assets/ea4ec112-e322-41ff-b70b-eb2d749258a6)

8Bit/rec.709 Video, Default Settings + Super Resolution Enabled, 10Bit enabled, Degraded Color 
![8Bit_2](https://github.com/user-attachments/assets/2b5bcb37-f36f-4045-8b73-68a98890035c)

**Comment by Wontell** [comment]
> Try this build with auto 8/10bit setting: [MpcVideoRenderer64_superres_acm_fix.zip](https://github.com/user-attachments/files/17532305/MpcVideoRenderer64_superres_acm_fix.zip) It forces 8-bit if superres is used in combination with wide color display mode (ACM enabled in Windows 11 24h2) for non-HDR output.
> 
> Also test it with Auto Color Management (ACM) disabled.


Hi,
Thanks for fast replay.

so whats the Auto Color management option and what it does exactly? If it makes more trouble than benefit i will just disable it

When i disabled it, everything worked fine, but with it enabled the color was degraded again, your fix didn't work

![fix](https://github.com/user-attachments/assets/40549682-f5cd-4cd0-b9f9-dc549d1e3682)

**Comment by Wontell** [comment]
> Superres and ACM are not compatible. So you have to disable one or the other. Or wait till NVIDIA fixes it.
> 
> New attempt. This should disable superres for 10bit input with ACM enabled: [MpcVideoRenderer64_v2.zip](https://github.com/user-attachments/files/17532398/MpcVideoRenderer64_v2.zip) Don't have 24h2 myself, so can't test this shitty new Microsoft function.

Thanks, but I rather keep ACM disabled than disable super res.

Can you consider implementing what i recommended above?
I mean if its not too hard and not today, when you have time....

Basically, your renderer detects input format and it displays them in statistics, so can you make it "if REC.709 detected, force 8-Bit Integer mode", this will fix the issue, since only 10Bit REC709 has this problem, BT2020 works fine.

You can add it as optional check-box option in the settings if you want.

P.S.
I heard ACM only worth it for people that use HDR on all the time, so it doesn't look over-bright on SDR content, so i can keep it off for now.
I turn HDR manually when im about to play HDR movie or a game.

**Comment by Wontell** [comment]
> Last attempt: [MpcVideoRenderer64_v3.zip](https://github.com/user-attachments/files/17532453/MpcVideoRenderer64_v3.zip)

What have you done here?

It works.

With ACP:ON
 it set to 8bit/10bit AUTO, the 10Bit + P010 + REC709 movie is set to 8bit internal format and presentation, color is fine.
BUT even if i change the plugin to 10-bit integer, which before broke the video on both 8bit and 10bit/rec709 movies now the color is fine

The ONLY diffrence is that
10Bit/REC709 movie has Video_processor Out put line set to 10Bit
8Bit/REC709 movie it shows 8bit

I think you can implement this fix in the mainline version and for correct color i would recommend to keep 8-bit/10bit auto just in case

ACP:ON, 10BIT+REC709 movie, P010 Format, 8/10Bit AUTO
![t1](https://github.com/user-attachments/assets/4d31ced3-5f33-46c9-ae43-8b0ba88f7567)

ACP:ON, 8BIT+REC709 Movie, NV12 Format, 8/10Bit AUTO
![t2](https://github.com/user-attachments/assets/659bb104-04d5-450d-9654-a71f74db3e5e)

**Comment by Wontell** [comment]
I can test but i only have 4K movies so super res will be disabled

I made 4 .png screenshots [maybe i should use jphXL for HDR, whats best?]

I made 2 of each with ACM on and ACM off, with HDR off and HDR auto

ACM Enabled, HDR Disabled, HDR passthrough enabled in settings [it doesnt do anything when HDR is disabled], 10bit HDR movie
![HDR_Auto_OFF_ACM_ON](https://github.com/user-attachments/assets/b62416a2-431d-4147-81ac-faff6813e88e)

ACM Disabled, HDR Disabled, HDR passthrough enabled in settings [it doesnt do anything when HDR is disabled], 10bit HDR movie
![HDR_Auto_OFF_ACM_OFF](https://github.com/user-attachments/assets/91614cad-0e45-4510-bc57-5558813bd4b3)


ACM Enabled, HDR AUTO, HDR passthrough enabled in settings, 10bit HDR movie
![HDR_Auto_ON_ACM_ON](https://github.com/user-attachments/assets/9e043a27-931e-496d-a97e-a95b359e12af)



ACM Disbaled, HDR AUTO, HDR passthrough enabled in settings, 10bit HDR movie
![HDR_Auto_ON_ACM_OFF](https://github.com/user-attachments/assets/dc63c30b-79e0-4cfd-845c-faf14cde5847)

**Comment by Aleksoid1978** [comment]
> @Aleksoid1978
> 
> ```
> diff --git a/Source/DX11VideoProcessor.cpp b/Source/DX11VideoProcessor.cpp
> index 68df966..d8cd92b 100644
> --- a/Source/DX11VideoProcessor.cpp
> +++ b/Source/DX11VideoProcessor.cpp
> @@ -539,6 +539,7 @@ HRESULT CDX11VideoProcessor::Init(const HWND hwnd, const bool displayHdrChanged,
>  	m_hWnd = hwnd;
>  	m_bHdrPassthroughSupport = false;
>  	m_bHdrDisplayModeEnabled = false;
> +	m_bWcgDisplayMode = false;
>  	m_DisplayBitsPerChannel = 8;
>  
>  	MONITORINFOEXW mi = { sizeof(mi) };
> @@ -549,6 +550,7 @@ HRESULT CDX11VideoProcessor::Init(const HWND hwnd, const bool displayHdrChanged,
>  		m_bHdrDisplayModeEnabled = displayConfig.HDREnabled();
>  		m_bHdrPassthroughSupport = displayConfig.HDRSupported() && m_bHdrDisplayModeEnabled;
>  		m_DisplayBitsPerChannel = displayConfig.bitsPerChannel;
> +		m_bWcgDisplayMode = displayConfig.WCGEnabled();
>  	}
>  
>  	if (m_bIsFullscreen != m_pFilter->m_bIsFullscreen) {
> @@ -1051,9 +1053,11 @@ HRESULT CDX11VideoProcessor::SetShaderDoviCurves()
>  void CDX11VideoProcessor::UpdateTexParams(int cdepth)
>  {
>  	switch (m_iTexFormat) {
> -	case TEXFMT_AUTOINT:
> -		m_InternalTexFmt = (cdepth > 8 || m_bVPUseRTXVideoHDR) ? DXGI_FORMAT_R10G10B10A2_UNORM : DXGI_FORMAT_B8G8R8A8_UNORM;
> +	case TEXFMT_AUTOINT: {
> +		bool superRes = m_bVPScaling && m_iVPSuperRes != SUPERRES_Disable && (!m_bHdrPassthroughSupport || !m_bHdrPassthrough || !SourceIsHDR());
> +		m_InternalTexFmt = (cdepth > 8 && (!m_bWcgDisplayMode || !superRes || m_srcExFmt.VideoTransferFunction >= MFVideoTransFunc_2020_const) || m_bVPUseRTXVideoHDR) ? DXGI_FORMAT_R10G10B10A2_UNORM : DXGI_FORMAT_B8G8R8A8_UNORM;
>  		break;
> +	}
>  	case TEXFMT_8INT:    m_InternalTexFmt = DXGI_FORMAT_B8G8R8A8_UNORM;     break;
>  	case TEXFMT_10INT:   m_InternalTexFmt = DXGI_FORMAT_R10G10B10A2_UNORM;  break;
>  	case TEXFMT_16FLOAT: m_InternalTexFmt = DXGI_FORMAT_R16G16B16A16_FLOAT; break;
> diff --git a/Source/DX11VideoProcessor.h b/Source/DX11VideoProcessor.h
> index 9de4cfb..8012d84 100644
> --- a/Source/DX11VideoProcessor.h
> +++ b/Source/DX11VideoProcessor.h
> @@ -161,6 +161,7 @@ private:
>  	bool m_bHdrDisplaySwitching   = false; // switching HDR display in progress
>  	bool m_bHdrDisplayModeEnabled = false;
>  	bool m_bHdrAllowSwitchDisplay = true;
> +	bool m_bWcgDisplayMode        = false;
>  	UINT m_srcVideoTransferFunction = 0; // need a description or rename
>  
>  	std::map<std::wstring, bool> m_hdrModeSavedState;
> diff --git a/Source/DisplayConfig.h b/Source/DisplayConfig.h
> index b44ee7f..173f78f 100644
> --- a/Source/DisplayConfig.h
> +++ b/Source/DisplayConfig.h
> @@ -127,6 +127,12 @@ struct DisplayConfig_t {
>  
>  		return advancedColor.advancedColorEnabled && !advancedColor.wideColorEnforced && !advancedColor.advancedColorForceDisabled;
>  	}
> +	bool WCGEnabled() const {
> +		if (IsWindows11_24H2OrGreater()) {
> +			return windows1124H2Colors.highDynamicRangeSupported && windows1124H2Colors.activeColorMode == DISPLAYCONFIG_ADVANCED_COLOR_MODE::DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG;
> +		}
> +		return false;
> +	}
>  };
> ```
> 
> If ACM and SuperRes are both enabled, it uses 10-bit texture only if VideoTransferFunction is bt2020 or higher. WCG mode (wide color) is when ACM is enabled, but HDR is not.
> 
> @Wontell Can you test the following: Windows HDR disabled + 10bit HDR movie + HDR passthrough and also SDR tonemap disabled in MPCVR. Colors will not be ok that way, but I am only curious if having ACM enabled or not has effect on colors in that situation. If it does, then I should probably restrict 10bit texture use further to bt2020 only in case of ACM.



> @Aleksoid1978
> 
> ```
> diff --git a/Source/DX11VideoProcessor.cpp b/Source/DX11VideoProcessor.cpp
> index 68df966..d8cd92b 100644
> --- a/Source/DX11VideoProcessor.cpp
> +++ b/Source/DX11VideoProcessor.cpp
> @@ -539,6 +539,7 @@ HRESULT CDX11VideoProcessor::Init(const HWND hwnd, const bool displayHdrChanged,
>  	m_hWnd = hwnd;
>  	m_bHdrPassthroughSupport = false;
>  	m_bHdrDisplayModeEnabled = false;
> +	m_bWcgDisplayMode = false;
>  	m_DisplayBitsPerChannel = 8;
>  
>  	MONITORINFOEXW mi = { sizeof(mi) };
> @@ -549,6 +550,7 @@ HRESULT CDX11VideoProcessor::Init(const HWND hwnd, const bool displayHdrChanged,
>  		m_bHdrDisplayModeEnabled = displayConfig.HDREnabled();
>  		m_bHdrPassthroughSupport = displayConfig.HDRSupported() && m_bHdrDisplayModeEnabled;
>  		m_DisplayBitsPerChannel = displayConfig.bitsPerChannel;
> +		m_bWcgDisplayMode = displayConfig.WCGEnabled();
>  	}
>  
>  	if (m_bIsFullscreen != m_pFilter->m_bIsFullscreen) {
> @@ -1051,9 +1053,11 @@ HRESULT CDX11VideoProcessor::SetShaderDoviCurves()
>  void CDX11VideoProcessor::UpdateTexParams(int cdepth)
>  {
>  	switch (m_iTexFormat) {
> -	case TEXFMT_AUTOINT:
> -		m_InternalTexFmt = (cdepth > 8 || m_bVPUseRTXVideoHDR) ? DXGI_FORMAT_R10G10B10A2_UNORM : DXGI_FORMAT_B8G8R8A8_UNORM;
> +	case TEXFMT_AUTOINT: {
> +		bool superRes = m_bVPScaling && m_iVPSuperRes != SUPERRES_Disable && (!m_bHdrPassthroughSupport || !m_bHdrPassthrough || !SourceIsHDR());
> +		m_InternalTexFmt = (cdepth > 8 && (!m_bWcgDisplayMode || !superRes || m_srcExFmt.VideoTransferFunction >= MFVideoTransFunc_2020_const) || m_bVPUseRTXVideoHDR) ? DXGI_FORMAT_R10G10B10A2_UNORM : DXGI_FORMAT_B8G8R8A8_UNORM;
>  		break;
> +	}
>  	case TEXFMT_8INT:    m_InternalTexFmt = DXGI_FORMAT_B8G8R8A8_UNORM;     break;
>  	case TEXFMT_10INT:   m_InternalTexFmt = DXGI_FORMAT_R10G10B10A2_UNORM;  break;
>  	case TEXFMT_16FLOAT: m_InternalTexFmt = DXGI_FORMAT_R16G16B16A16_FLOAT; break;
> diff --git a/Source/DX11VideoProcessor.h b/Source/DX11VideoProcessor.h
> index 9de4cfb..8012d84 100644
> --- a/Source/DX11VideoProcessor.h
> +++ b/Source/DX11VideoProcessor.h
> @@ -161,6 +161,7 @@ private:
>  	bool m_bHdrDisplaySwitching   = false; // switching HDR display in progress
>  	bool m_bHdrDisplayModeEnabled = false;
>  	bool m_bHdrAllowSwitchDisplay = true;
> +	bool m_bWcgDisplayMode        = false;
>  	UINT m_srcVideoTransferFunction = 0; // need a description or rename
>  
>  	std::map<std::wstring, bool> m_hdrModeSavedState;
> diff --git a/Source/DisplayConfig.h b/Source/DisplayConfig.h
> index b44ee7f..173f78f 100644
> --- a/Source/DisplayConfig.h
> +++ b/Source/DisplayConfig.h
> @@ -127,6 +127,12 @@ struct DisplayConfig_t {
>  
>  		return advancedColor.advancedColorEnabled && !advancedColor.wideColorEnforced && !advancedColor.advancedColorForceDisabled;
>  	}
> +	bool WCGEnabled() const {
> +		if (IsWindows11_24H2OrGreater()) {
> +			return windows1124H2Colors.highDynamicRangeSupported && windows1124H2Colors.activeColorMode == DISPLAYCONFIG_ADVANCED_COLOR_MODE::DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG;
> +		}
> +		return false;
> +	}
>  };
> ```
> 
> If ACM and SuperRes are both enabled, it uses 10-bit texture only if VideoTransferFunction is bt2020 or higher. WCG mode (wide color) is when ACM is enabled, but HDR is not.

I will not implement any such "automation" because either Microsoft or Nvidia works crookedly in some situations.
Issue is closed.
Write more here and I will delete it.

**Comment by Wontell** [comment]
@Aleksoid1978
Than whats the solution to the problem? You want to keep it as?
Если все видео на 10бит будет сломанное, в чем тогда смысл?
