### ISSUE TITLE
Video seeking is slow/sluggish compared to other renderers.

### ISSUE THREAD

**Issue by batuhankrmn** [Aleksoid1978/VideoRenderer#192]
As the title says, opening network streams in players using MPC Video Renderer and seeking in the video are very slow compared to other players. The video takes a long time to open, and after opening, it is not instantly possible to seek anywhere in the video. For example, if I want to fast-forward the video by 5 seconds with MPC-BE, I have to wait at least 1-2 seconds. In mpv, it takes almost no time at all. I think MPC Video Renderer is one of the most powerful and best featured renderers at the moment, so thanks for that. The only problem I have is the opening of network streams and seek slowness. I believe this would be a very important improvement for people who use MPC Video Renderer in applications that stream using Debrid services such as Stremio. Thank you in advance. If you need more information on any topic, feel free to ask.

Video Player version: MPC-BE 1.8.0
MPC Video Rendere version:  0.8.7.2295 x64
Windows 11

Opening and seeking with MPC-BE using MPC Videro Renderer:

https://github.com/user-attachments/assets/e593d253-f896-4a60-91f9-b217aa3105bb

Opening and seeking with SMPlayer using mpv renderer (you can notice how much faster it opens the stream and seeking with keyboard/mouse is also noticeably faster:

https://github.com/user-attachments/assets/b90af7c7-5f38-4418-84a1-ffea1145546e

**Comment by Aleksoid1978** [comment]
MPC Video Renderer has nothing to do with opening and working with files or links, this is done either by the player itself or by an external Source filter if one is used. Show the list of filters after opening.

If this happens when opening online - need a link to check. Well, maybe other players have a better way of working with online.
If this happens when opening a local file - I can't confirm, everything works instantly.

**Comment by v0lt** [comment]
MPC Video Renderer does not open video files. Never. The player does this using built-in or external source filters.

Menu: Play > Filters > Copy filter list to clipboard.

**Comment by batuhankrmn** [comment]
@Aleksoid1978 @v0lt These are the filters that copied from MPC-BE:
MPC-BE x64 1.8.0
Filters currently loaded:
  - MPC Audio Renderer
  - MPC Video Renderer
  - AC3Filter
  - MPC Video Decoder
  - Audio Switcher
  - MPC Audio Decoder
  - MPC Audio Decoder
  - MPC Audio Decoder
  - MPC Audio Decoder
  - MPC Audio Decoder
  - MPC Matroska Source

I'm not sure about what is causing this issue, It could be the player or filter as you guys mentioned but I assumed that it is MPC Video Renderer since it was exactly same for the PotPlayer with using MPC Video Renderer.

**Comment by Aleksoid1978** [comment]
Where is a link ?
Remove AC3 filter.

**Comment by batuhankrmn** [comment]
Sorry, link was a private debrid download link, which should not be downloaded from another IP due to Real-Debris rules. It was a huge file like 75 GB+. Removing AC3 Filter changed nothing unfortunately.

**Comment by Aleksoid1978** [comment]
Without link do nothing.

**Comment by Aleksoid1978** [comment]
Your link opens quickly and rewinding works quite quickly.
And yes - in MPC-BE there is no buffering when reading online, data is read as needed.
