### ISSUE TITLE
Low quality rescaling in DX11 with DXVA2 enabled

### ISSUE THREAD

**Issue by zybexXL** [Aleksoid1978/VideoRenderer#194]
MPC v0.8.8.2303, installed via KLite pack.

Upscaling quality is now terrible with DX11 + DXVA2 enabled. It was not like this before (AMD GPU).

MadVR's upscaling with DXVA2 + DX11 is still high-quality, so I don't think it's a driver issue. Can you please quickly check? It looks like "use DXVA2 for rescaling" in DX11 is actually doing something else, or not enabling the proper DXVA2 algo.

Compare the text quality in the screenshots below:

OK: DX9, DXVA2 (similar to MadVR quality in DX11+DXVA2 mode):
![image](https://github.com/user-attachments/assets/c7ca547c-a82f-4859-8254-671bb1f9cf1b)

Bad: DX11, "use DXVA2" enabled:
![image](https://github.com/user-attachments/assets/c3b14508-8058-44bb-bb08-9dc8eb6d9c8e)

**Comment by zybexXL** [comment]
> MadVR does not use D3D11 video processor, so you can not compare with Madvr.

You're right, I see it's doing Bilinear when DXVA is selected in DX11 mode.
I didn't change the GPU driver, just KLite. It's possible that I wasn't using DX11 before.

**Comment by zybexXL** [comment]
It's indeed a Vega 8 inside a Ryzen PRO 5850U (Zen3 Cezanne-U).
Driver is the latest from the OEM for this model, v31.021024.5005 (likely corresponds to Adrenalin 23.11.1).

I'll see if I can force-install the latest from AMD (24.09.1), Lenovo doesn't have a newer one for this model.

**Comment by Aleksoid1978** [comment]
Try uncheck this:
![изображение](https://github.com/user-attachments/assets/08209440-982b-4243-ae79-aec903eb4ac6)

**Comment by zybexXL** [comment]
Just unchecking "use for resizing" under the DXVA section works fine - it then uses the selected shader below.
