### ISSUE TITLE
HDR / Dolby Vision

### ISSUE THREAD

**Issue by whitelightning76** [Aleksoid1978/VideoRenderer#195]
Hello!

I am not sure if this already implemented, but could it be possible to add in the information tab if a file is being played in HDR10 or in Dolby Vision ?
I can only see `"HDR10: ON"

Thanks!

**Comment by v0lt** [comment]
> I can only see `"HDR10: ON"

MPC Video Renderer only supports two display modes: SDR and HDR10.

> I am not sure if this already implemented, but could it be possible to add in the information tab if a file is being played in HDR10 or in Dolby Vision ?

When playing Dolby Vision video in "Dolby Vision mode" the information is present in the "Imput format" field. You should see this immediately when playing Profile 5. When playing compatible formats (e.g. Profile 8) the information in the "Imput format" field will depend on the corresponding setting.

**Comment by whitelightning76** [comment]
Ah i see what you mean now.

I do not know how it works with the profiles, but not all are working right ?  (same as on other players.)

Is it possible to have full Dolby Vision support ?

**Comment by v0lt** [comment]
> Is it possible to have full Dolby Vision support ?

I doubt it. For full Dolby Vision support, use certified equipment.
