### ISSUE TITLE
RTX Super Resolution won't activate in some files

### ISSUE THREAD

**Issue by SKProCH** [Aleksoid1978/VideoRenderer#196]
Hello, i've try to explore some other players than VLC and getting troubles with activating super resolution.

Seems like some video files doesn't allow enabling RTX SR (tested in potplayer, mpc hc, mpc be):

![image](https://github.com/user-attachments/assets/c61ef988-4e6b-4b59-bb14-e39c8977f44c)

![image](https://github.com/user-attachments/assets/f31a669c-cb88-47c6-87b5-51cd75139c9b)

Or:

![image](https://github.com/user-attachments/assets/2e62b6ec-1750-4b08-8098-cc33d1c781cc)

But some files works fine:

![image](https://github.com/user-attachments/assets/57efb414-58a8-4656-9f52-61329d1f21b9)

VLC handles SR in all this files fine. 

![image](https://github.com/user-attachments/assets/1ef4a077-5e72-4f2b-a744-a3e1b7917441)

MPC VR installed and selected in players settings. MPC BE tested out of the box, just selected MPC renderer in settings.

Is I'm missing something?

**Comment by Aleksoid1978** [comment]
1). DV - uses shaders, but D3D11 VP requires to run super resolution.
2). Upload second file/sample.

**Comment by SKProCH** [comment]
1. So, there is no workarounds for this problem and it has no solution in the foreseeable future?
2. https://github.com/user-attachments/assets/dd85cbcd-db2e-4a3d-83be-681b17a1c92b (this is `mkv` file renamed to mp4 due to github supported files limitations)

**Comment by Aleksoid1978** [comment]
1 - Yes. For convert DV -> HDR use shaders, but SuperRes requires D3D11 VP.

**Comment by Aleksoid1978** [comment]
2 - SuperRes breaks the picture when used together with HDR Passthrough, so it is simply disabled for such cases.

**Comment by Aleksoid1978** [comment]
Does VLC support HDR Passthrough ? I don't know, but if not - that's why it's working in VLC.

**Comment by Aleksoid1978** [comment]
In general, you have an 8-bit screen - there simply can't be normal HDR support - just turn it off in Windows settings and watch normally in SDR.

**Comment by v0lt** [comment]
Super Resolution for Dolby Vision is nonsense.

**Comment by SKProCH** [comment]
Ok, thanks for support!
