### ISSUE TITLE
When using this renderer and turning on the VSR, the VSR function cannot be activated when starting the player and playing for the first time.

### ISSUE THREAD

**Issue by RBHakureiReimu** [Aleksoid1978/VideoRenderer#198]
As the title says, whenever I turn on the player for the first time and play a video that can be processed by the VSR, the VSR function will not take effect automatically. It will only take effect when I toggle the VSR image quality restriction option in the settings of this renderer. When I turn off the player and restart playing the same video, the VSR function will fail again, and the VSR will not take effect until the previously described steps are performed again.
![屏幕截图 2024-12-21 155538](https://github.com/user-attachments/assets/473ec7d1-0e3d-41d7-9654-fa6dc4259a2a)
![屏幕截图 2024-12-21 155632](https://github.com/user-attachments/assets/c6696492-e695-47b6-ab62-ef84fa058f66)
![屏幕截图 2024-12-21 155954](https://github.com/user-attachments/assets/cd1c668b-abf2-41da-9a84-914585e0182c)
Figure 1 is before modifying the settings shown in Figure 2, and Figure 3 is after modifying the settings shown in Figure 2. Each time a video is played, the settings shown in Figure 2 need to be modified to activate the VSR.

**Comment by Aleksoid1978** [comment]
Don't confirm. For me VSR working when a start play.

**Comment by Aleksoid1978** [comment]
Confirm for P010 input.

**Comment by RBHakureiReimu** [comment]
> Confirm for P010 input.

Then I'm not very clear. I'll try to reinstall the renderer first.

**Comment by RBHakureiReimu** [comment]
> Confirm for P010 input.

我重新安装了渲染器，并重启了电脑，但问题仍然存在，请问我在哪里可以获取相关日志以确定问题来源

**Comment by RBHakureiReimu** [comment]
> Confirm for P010 input.

I reinstalled the renderer and restarted the computer, but the problem still exists. May I ask where I can obtain relevant logs to determine the source of the problem?

**Comment by RBHakureiReimu** [comment]
> Confirm for P010 input.

新的问题，当播放器自动播放下一个视频时，VSR也会失效

**Comment by RBHakureiReimu** [comment]
> Don't confirm. For me VSR working when a start play.

New problem. When the player automatically plays the next video, VSR will also fail.

**Comment by RBHakureiReimu** [comment]
> Don't confirm. For me VSR working when a start play.

My current computer system version is 26120.2705.

**Comment by RBHakureiReimu** [comment]
> Confirm for P010 input.

When I switched to the 0.8.7 version, the problem was fixed, but the new version will still have the issues I mentioned in this article.

**Comment by v0lt** [comment]
> My current computer system version is 26120.2705.

There is no such version. The MPC Video Renderer version is written in the settings window (can be copied to the clipboard) or can be viewed in the renderer statistics.

**Comment by v0lt** [comment]
I don't know what VSR is.

But I can say that Super Resolution is disabled for 10-bit videos (P010) and it is written in [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt).

**Comment by Klaus1189** [comment]
26120.2705 is version of Windows 11 24H2 Dev build

**Comment by RBHakureiReimu** [comment]
> I don't know what VSR is.
> 
> But I can say that Super Resolution is disabled for 10-bit videos (P010) and it is written in [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt).

The problem is that the VSR function works in 0.8.7, under 10-bit video

**Comment by Klaus1189** [comment]
As v0lt already posted:
[history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt).

That is expected. Please click on it and read line 11:
"Super Resolution" will only be enabled for 8-bit video due to driver limitations.

**Comment by Aleksoid1978** [comment]
Fixed.
