### ISSUE TITLE
Occasional freeze when skipping forward repeatedly

### ISSUE THREAD

**Issue by LigH-de** [Aleksoid1978/VideoRenderer#2]
Using MPC-HC 1.9.0 with MPC Renderer (both 64 bit, on Windows 7 SP1, 64 bit), the player sometimes freezes when I repeatedly skip forward to scan a video optically.

If I press the "Right" cursor key about each half second to jump forward, over and over, after about 20 skips the player freezes so that not even clicking the "Close application" button :x: twice forces the AppCrash dialog to appear, I really have to kill the process in a task manager.

There is no freeze with e.g. madVR, a VMR9 or EVR variant.

**Comment by v0lt** [comment]
I can not reproduce.
Please show the settings and statistics of the renderer.

**Comment by LigH-de** [comment]
Options:
![MPC-VR_Options](https://user-images.githubusercontent.com/5917225/71735047-a8593700-2e4d-11ea-94cd-492c225799c5.png)

Info:
![MPC-VR_Info](https://user-images.githubusercontent.com/5917225/71735058-aee7ae80-2e4d-11ea-9d23-409ac1934151.png)

OSD Statistics while playing:
![MPC-VR_Stats](https://user-images.githubusercontent.com/5917225/71735069-b4dd8f80-2e4d-11ea-8f71-b251e2abd465.png)

It is impossible to make a screenshot after MPC-HC with MPCVR has crashed.

You need a lot of patience, and don't tap forward too quickly. But I can reproduce it reliably.

**Comment by LigH-de** [comment]
Tested v0.3.8.1060 on another PC (GTX 1050Ti, 4 GB): No freeze. So it may depend on the specific graphic card, possibly its low amount of VRAM.

**Comment by v0lt** [comment]
For HD and FullHD video, 1 GB of video memory is usually enough.
Only 4k problems can occur, in this case 2 GB is desirable, especially if the stream is 10-bit.
In any case, you can start the GPU-Z and see the video memory consumption.

**Comment by LigH-de** [comment]
Correction:

I made MPC-HC + MPC-VR crash on the PC with the 4 GB GTX 1050 Ti by holding down the "right" arrow key to "scroll" fast forward through a video with a resolution less than 720p.

**Comment by Aleksoid1978** [comment]
Try test build - https://yadi.sk/d/sepvEyA2Ur95nQ

**Comment by LigH-de** [comment]
Tried hard to freeze it again ... but it didn't. Seems fixed for me. :+1:
