### ISSUE TITLE
HDR image looks too dark

### ISSUE THREAD

**Issue by z826540272** [Aleksoid1978/VideoRenderer#20]
HDR image looks too dark
with HDR Screen

**Comment by Aleksoid1978** [comment]
Can't confirm.
Enable statistics and take screen, also take screen options.

**Comment by z826540272** [comment]
i will test later

**Comment by cdytoby** [comment]
Hello, I can say that with D3DX11, HDR works perfectly on my side, and both beta version of MPC BE and release version are tested.

Here is the setting on my side:

![image](https://user-images.githubusercontent.com/15671368/103664160-3e98cf00-4f72-11eb-96b0-146ff7de0c2a.png)

What bothers me though, is when using this MPC Renderer with HDR, it will force turn off HDR option in Windows whenever I quit the MPC BE Player, regardless which states HDR is in Windows setting. It doesn't happen when using madVR.

**Comment by Aleksoid1978** [comment]
Auto display HDR on/off - enable/disable system HDR mode.

**Comment by clsid2** [comment]
What he means, is that when OS HDR is already enabled when creating the renderer, then it should not disable OS HDR when playback is finished.

**Comment by Aleksoid1978** [comment]
For me it’s working. If HDR enable in OS and open HDR video - after close HDR mode stay ON in OS, if open SDR video - HDR mode disable in OS and stay disabled. Using MPC-BE with internal filters.

**Comment by Aleksoid1978** [comment]
I also check using LAV Video. So - after open LAV Video set "flag" that's is SDR video - MPC VR off HDR mode in OS, then LAV Video set "flag" that is HDR video, MPC VR on HDR mode in OS and after close "restore" previous state ... SDR mode in OS.
Using MPC-BE's internal video decoder all is good.

I will think about what can be done.

**Comment by clsid2** [comment]
That sounds like it overwrites the "original" state each time it switches HDR on/off. It should backup the state just once.
```
int origHDRstate = -1;
// backup:
if (origHDRstate < 0) {
// save original state, set to 0 for normal mode, 1 for HDR mode
}
// restore:
if (origHDRstate >= 0) {
// restore original state, if 1 HDR mode, otherwise normal mode
}
```

**Comment by z826540272** [comment]
> I also check using LAV Video. So - after open LAV Video set "flag" that's is SDR video - MPC VR off HDR mode in OS, then LAV Video set "flag" that is HDR video, MPC VR on HDR mode in OS and after close "restore" previous state ... SDR mode in OS.
> Using MPC-BE's internal video decoder all is good.
> 
> I will think about what can be done.



> Auto display HDR on/off - enable/disable system HDR mode.

MPC-BE doesnt support Hardware decode when add SVP filter,but this video render cannot work with MPC-HC

**Comment by Aleksoid1978** [comment]
Good working in MPC-HC.

**Comment by clsid2** [comment]
The renderer works great with latest MPC-HC (1.9.8). You might be using an old version (1.7.13).
https://github.com/clsid2/mpc-hc/releases/tag/1.9.8
