### ISSUE TITLE
Regarding the issue that VSR does not take effect in the latest nightly version

### ISSUE THREAD

**Issue by RBHakureiReimu** [Aleksoid1978/VideoRenderer#200]
First of all, regarding the "Super Resolution" will only be enabled for 8-bit video due to driver limitations. "written in the" [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt) "document mentioned by several developers in my previous feedback, the picture below is a comparison screenshot when I open the VSR function in the suspended 10-bit video state. The left side is the VSR enabled. As long as my picture is not re-compressed by Github, I believe you can find that the renderer plays 10-bit video. VSR can take effect.
![屏幕截图 2024-12-25 231730](https://github.com/user-attachments/assets/e591c2e8-7168-429f-8de2-a74dc0fc9bb8)
After a long list of foreshadowing, I would like to explain that starting from the "MpcVideoRenderer- 0.9.0. 2331_git 2024.12-72c47a5" version, when I play 10-bit videos, even if I switch on the VSR related options, the VSR does not work at all.
Here I also went through a series of tests, I found that the version of the problem raised when "[#198](https://github.com/Aleksoid1978/VideoRenderer/issues/198)" appeared on my computer is from "MpcVideoRenderer- 0.8.8 2314_git 2024.11 26-d5137fe", its previous version "MpcVideoRenderer- 0.8.8 2313_git 2024.11 25-3a470ba" did not have a problem, the following is a comparison screenshot, I hope to provide some help to developers to fix this problem.
![屏幕截图 2024-12-25 232008](https://github.com/user-attachments/assets/0ab64e26-2c5d-4762-a937-f31a5a0000d7)

**Comment by v0lt** [comment]
[history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt)
_"Super Resolution" will only be enabled for 8-bit video due to driver limitations._

This limitation did not always work, but it has now been fixed.

**Comment by RBHakureiReimu** [comment]
> [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt) _"Super Resolution" will only be enabled for 8-bit video due to driver limitations._
> 
> This limitation did not always work, but it has now been fixed.

But if it can be effective, why not make it effective?

**Comment by RBHakureiReimu** [comment]
> [history.txt](https://github.com/Aleksoid1978/VideoRenderer/blob/master/history.txt) _"Super Resolution" will only be enabled for 8-bit video due to driver limitations._
> 
> This limitation did not always work, but it has now been fixed.

On the premise that VSR can take effect in 10-bit, is it also not supported for the sake of the documents already written? I don't think this is reasonable. Since the function is proven to be effective, it is not limited but open or released as a new function, right?

**Comment by v0lt** [comment]
This function works for you for P010, **but does not work for others**. And the reason is unclear. Due to unstable operation, users begin to write bug reports.

**Comment by RBHakureiReimu** [comment]
> This function works for you for P010, **but does not work for others**. And the reason is unclear. Due to unstable operation, users begin to write bug reports.

I am a user of the Windows Preview Experience Program. The device I am using is a laptop + external monitor, and the configuration is 10875H + 2070Max-Q. Since the renderer supports VSR, the VSR can be displayed in the preview information when I play a 10bit video. After I posted the "[#113](https://github.com/Aleksoid1978/VideoRenderer/issues/113)" feedback, the VSR also officially took effect on my computer (as shown in the previous screenshot, the picture is obviously processed, and the NVIDIA control panel also shows that the VSR is being processed). I hope this can help your development.

**Comment by RBHakureiReimu** [comment]
> This function works for you for P010, **but does not work for others**. And the reason is unclear. Due to unstable operation, users begin to write bug reports.

And when I installed MPC-BE and the renderer for my college roommate before, his computer could also play 10bit video and make VSR work at the same time. His computer configuration was 11800H + 3060Laptop and an external monitor was connected, so from my understanding, the developer you said "This function works for you for P010, but does not work for others. And the reason is unclear. Due to unstable operation, users began to write bug reports." In my opinion, it is unbelievable and unimaginable.

**Comment by RBHakureiReimu** [comment]
> This function works for you for P010, **but does not work for others**. And the reason is unclear. Due to unstable operation, users begin to write bug reports.

I am using machine translation, and I am modifying the content while looking for relevant information. Please forgive me for any inconvenience.
This is my final question about VSR functionality: the discussion posts I found on various Chinese internet forums about the video renderer for this project all state that MPCVR + 10Bit Video + VSR is valid, so is there a possibility that something related to the Windows language affects VSR running on your Russian-language computers?
I saw such a discussion about the VSR function under the MPV player branch that is also maintained by the Chinese[This is a Chinese discussion, please use machine translation by yourself, thank you.](https://github.com/hooke007/MPV_lazy/discussions/286)。
I am just a simple user rather than a developer, and I don't understand the essential difference between the DirectShow +-based player you maintain and the cross-platform player MPV, but I read the MPV topics and discussions, and the maintainers in it are saying that the idea of using MPCVR code implements VSR technology for MPV, and the discussion in the Chinese-maintained MPV I listed earlier also mentioned that MPCVR supports 10Bit video + VSR, so I still hope you can find out the reason carefully. After all, it is impossible for a large group of Chinese users to collectively fabricate a meaningless lie in order to interfere with your development, right? This is ridiculous, isn't it?

**Comment by RBHakureiReimu** [comment]
> This function works for you for P010, **but does not work for others**. And the reason is unclear. Due to unstable operation, users begin to write bug reports.

Finally, because this discussion has been closed, I don't know if you can see, want to see, and have time to see my comments, so this is the last question: before you label VSR + 10Bit as impossible, why not explain that this works on Chinese computers? Not to mention whether it works on other operating systems other than Russian and Chinese has not been confirmed by valid evidence.

**Comment by v0lt** [comment]
It is not clear. Does it work on the driver starting from what version? Does it work correctly?
I can't answer these questions (I don't have RTX), but the information I get is not as good as you write.

**clsid2** recently asked similar questions, but the user preferred to simply roll back to an older version.
https://github.com/Aleksoid1978/MPC-BE/issues/674#issuecomment-2580806385

**Comment by RBHakureiReimu** [comment]
I'm using a machine translation, and the last one if I understand correctly it should stand for "Does the VSR take effect correctly".
Windows version+build:Windows23H2、24H2、Canary(Follow the latest Dev or Canary channels for real-time updates)
GPU:NVIDIA RTX 2070 MAX-Q
GPU driver version:It can take effect from 531.38 to the latest 566.36.And I will follow up on the driver updates released by Nvidia as soon as possible.
MPCVR version:From 0.7.2 to 0.8.8 2313
MPCVR texture setting: auto/8/10/16 These can all work,But I have been using 16 for a long time.
Video color primary:BT709
Output resolution:3840*2160
RTX HDR enabled: no
ACM enabled: no
Windows HDR mode enabled: no
Result correct: yes

> It is irrelevant that it works for you. And it has nothing to do with language. What is relevant is that it sometimes does NOT work properly. Often when used in combination with RTX HDR. And 10bit also had issues with the initial driver versions.
> 
> The developers are tired of constant bug reports about it not working good. Users only look at their own limited situation, do not listen properly, and do not give proper feedback when asked.
> 
> @v0lt How about an option (registry only) to allow superres for 10bit? Then users can manually enable it (for testing).
> 
> And create an issue for testing feedback that forces users to fill in a template with the following details:
> 
> > Windows version+build:
> > GPU:
> > GPU driver version:
> > MPCVR version:
> > MPCVR texture setting: auto/8/10/16
> > Video color primary:
> > Output resolution:
> > RTX HDR enabled: yes/no
> > ACM enabled: yes/no
> > Windows HDR mode enabled: yes/no
> > Result correct: yes/no
> > Notes:
> > Input color primary can be seen on MPCVR OSD by pressing Ctrl+J, for example BT709 or BT2020.|
> > ACM means Automatic Color Management and is an option in Windows 11 display settings to run desktop in 10bit.

**Comment by RBHakureiReimu** [comment]
> It is irrelevant that it works for you. And it has nothing to do with language. What is relevant is that it sometimes does NOT work properly. Often when used in combination with RTX HDR. And 10bit also had issues with the initial driver versions.
> 
> The developers are tired of constant bug reports about it not working good. Users only look at their own limited situation, do not listen properly, and do not give proper feedback when asked.
> 
> @v0lt How about an option (registry only) to allow superres for 10bit? Then users can manually enable it (for testing).
> 
> And create an issue for testing feedback that forces users to fill in a template with the following details:
> 
> > Windows version+build:
> > GPU:
> > GPU driver version:
> > MPCVR version:
> > MPCVR texture setting: auto/8/10/16
> > Video color primary:
> > Output resolution:
> > RTX HDR enabled: yes/no
> > ACM enabled: yes/no
> > Windows HDR mode enabled: yes/no
> > Result correct: yes/no
> > Notes:
> > Input color primary can be seen on MPCVR OSD by pressing Ctrl+J, for example BT709 or BT2020.|
> > ACM means Automatic Color Management and is an option in Windows 11 display settings to run desktop in 10bit.

By the way, this may be my unauthorized understanding. If you gave up the 10Bit + VSR function because of ACM, then I have already raised relevant issues here. ACM will cause abnormal video brightness processed by VSR on non-HDR monitors:[Click here.](https://github.com/Aleksoid1978/VideoRenderer/issues/171)

**Comment by RBHakureiReimu** [comment]
> It is irrelevant that it works for you. And it has nothing to do with language. What is relevant is that it sometimes does NOT work properly. Often when used in combination with RTX HDR. And 10bit also had issues with the initial driver versions.
> 
> The developers are tired of constant bug reports about it not working good. Users only look at their own limited situation, do not listen properly, and do not give proper feedback when asked.
> 
> @v0lt How about an option (registry only) to allow superres for 10bit? Then users can manually enable it (for testing).
> 
> And create an issue for testing feedback that forces users to fill in a template with the following details:
> 
> > Windows version+build:
> > GPU:
> > GPU driver version:
> > MPCVR version:
> > MPCVR texture setting: auto/8/10/16
> > Video color primary:
> > Output resolution:
> > RTX HDR enabled: yes/no
> > ACM enabled: yes/no
> > Windows HDR mode enabled: yes/no
> > Result correct: yes/no
> > Notes:
> > Input color primary can be seen on MPCVR OSD by pressing Ctrl+J, for example BT709 or BT2020.|
> > ACM means Automatic Color Management 和 is an option in Windows 11 display settings to run desktop in 10bit.

One more thing, I installed the Debug renderer you provided for download before, maybe because I didn't find the relevant information, so I don't know where to find the relevant logs and provide them to you. Therefore, all I can do is to show screenshots and describe the phenomenon. Maybe you can consider using the Debug renderer or log generation directory in "readme", or when users provide feedback, you can let them use the Debug renderer, otherwise "Users only look at their own limited situation, do not listen properly, and do not give proper feedback when asked." This kind of problem will never be solved, will it?

**Comment by RBHakureiReimu** [comment]
It's really my problem that I didn't take the whole situation into account, and I offer my sincerest apologies here.

> And now you are giving improper feedback as well. The template should only contains your CURRENT versions and only things you tested TODAY. Nothing else.
> 
> And the fact that you confirm the problem with ACM, yet ignore it completely is the whole reason why VSR is now disabled for 10bit. YOU may not have ACM enabled right now, but others do. If we know exactly when VSR does not work, then we can effectively disable it for only those specific cases. So ALL combinations need to be tested.

**Comment by RBHakureiReimu** [comment]
acm off + rtx hdr off + 8bit texture + bt709 = Yes
acm off + rtx hdr off + 10bit texture + bt709 = Yes
acm off + rtx hdr off + 16bit texture + bt709 = Yes
acm off + rtx hdr off + 8bit texture + bt2020 = Yes
acm off + rtx hdr off + 10bit texture + bt2020 = Yes
acm off + rtx hdr off + 16bit texture + bt2020 = Yes

acm on + rtx hdr off + 8bit texture + bt709 = No, the brightness has been reduced.
acm on + rtx hdr off + 10bit texture + bt709 = No, the brightness has been reduced.
acm on + rtx hdr off + 16bit texture + bt709 = No, the brightness has been reduced.
acm on + rtx hdr off + 8bit texture + bt2020 = No, the brightness has been reduced.
acm on + rtx hdr off + 10bit texture + bt2020 = No, the brightness has been reduced.
acm on + rtx hdr off + 16bit texture + bt2020 = No, the brightness has been reduced.

Regarding the HDR-related test below, my monitor only supports fake HDR, but when I switch RTX HDR on and off, the color of the video does change, so the one marked "Yes" I think it works, just for reference.

acm off + rtx hdr on + 8bit texture + bt709 = Yes
acm off + rtx hdr on + 10bit texture + bt709 = Yes
acm off + rtx hdr on + 16bit texture + bt709 = Yes
acm on + rtx hdr on + 8bit texture + bt709 = Yes
acm on + rtx hdr on + 10bit texture + bt709 = Yes
acm on + rtx hdr on + 16bit texture + bt709 = Yes

acm off + rtx hdr on + 8bit texture + bt2020 = The BT2020 film source of the SDR was not found, and the hardware reason could not be tested.
acm off + rtx hdr on + 10bit texture + bt2020 = ditto
acm off + rtx hdr on + 16bit texture + bt2020 = ditto
acm on + rtx hdr on + 8bit texture + bt2020 = ditto
acm on + rtx hdr on + 10bit texture + bt2020 = ditto
acm on + rtx hdr on + 16bit texture + bt2020 = ditto

**Comment by RBHakureiReimu** [comment]
There is another issue related to ACM: when I turn on ACM + VSR, the brightness is not mapped by exceptions at MPV.
Under the premise that MPV and MPCVR play NV12 and P010 simultaneously.
The following is my conjecture about the brightness being mapped incorrectly when using ACM + VSR in MPCVR: When both ACM and VSR are turned on in MPCVR, some algorithms of ACM and HDR are incorrectly bound.
Reasons to guess: As I've reported before, I'm using a laptop, so I have two monitors. My external monitor has a fake HDR, and the screen will show abnormal brightness when turned on in the settings; my laptop's built-in monitor has no HDR at all (including fake ones), and HDR cannot be turned on in the settings. When I also turned on ACM and played VSR-processed video on both monitors, the video brightness of the monitor with the fake HDR was mapped incorrectly, while the monitor without HDR at all was fine.

**Comment by RBHakureiReimu** [comment]
@clsid2 My question, sorry, please let me explain in detail: I did download the BT2020 video, but that video is a P010 + HDR video, but this video can be converted to SDR by MPCVR, so I also tested it, and it turned out that the VSR did work, so I filled it in.

**Comment by RBHakureiReimu** [comment]
If this is not rigorous, maybe you can tell me where to download the video of P010 + BT2020 + SDR, because I really can't find it, all I can find is Y410 + BT2020 + SDR or P010 + BT2020 + HDR.
I also tested the source of the Y410 film, but the VSR below did not work.

**Comment by RBHakureiReimu** [comment]
这是使用MPCVR内置HDR转SDR算法（第二张图标记处）的前提下，P010+BT2020视频的对比图（第一张图），从2560*1440缩放到3840*2160，左侧开启VSR，右侧关闭VSR，最后一张图是信息界面。
![屏幕截图 2025-01-11 005117](https://github.com/user-attachments/assets/32621a1d-cdfc-4d71-8b47-c50d2db677cb)
![屏幕截图 2025-01-11 005432](https://github.com/user-attachments/assets/d3120b34-8093-4ffe-895b-be2d4ab227ed)
![屏幕截图 2025-01-11 005655](https://github.com/user-attachments/assets/71f44c57-a048-427b-a35f-4353da98b418)

**Comment by Aleksoid1978** [comment]
Improved SuperResolution activation - now it works for 10-bit videos if ACM is disabled in the system (Windows 11 24H2).

**Comment by Aleksoid1978** [comment]
Check first and then ask.
