### ISSUE TITLE
Is it possible to add "jinc" to the image upscaling setting?

### ISSUE THREAD

**Issue by yeezylife** [Aleksoid1978/VideoRenderer#21]
Jinc could be a interesting choice for image upscaling.

**Comment by Aleksoid1978** [comment]
1 - There are examples of this algorithm on shaders?
2 - There is a comparison of this algorithm with others?

**Comment by yeezylife** [comment]
I've been using jinc in Madvr,it's just slightly less sharp than lanczos3 , but have much less ringing.
Comparison can be found in[https://forum.doom9.org/showthread.php?t=146228&page=718](url)

**Comment by Aleksoid1978** [comment]
Is there open source implementation ?

**Comment by yeezylife** [comment]
https://github.com/AviSynth/jinc-resize
https://github.com/Asd-g/AviSynth-JincResize
https://github.com/AviSynth/jinc-resize/tree/master/JincResize
I searched on github and found these..

**Comment by Aleksoid1978** [comment]
We use shaders - i don't think that we can write it based on c++ code.

**Comment by yeezylife** [comment]
How about these,sorry I'm not a coder.
https://forums.libretro.com/t/jinc-2-fixes/21146/5
https://pastebin.com/raw/fH2A3Y42
https://git.libretro.com/libretro-assets/glsl-shaders/-/blob/master/nedi/shaders/nedi-jinc.glsl

**Comment by yeezylife** [comment]
[jinc2.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5734450/jinc2.zip)

**Comment by v0lt** [comment]
Thanks.
This is a shader for GLSL. Someone needs to understand it, translate it into HLSL and adapt it to our environment.
I don't plan on doing this anytime soon.

**Comment by qwerttvv** [comment]
just take a look
https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/resize.c
@yeezylife

**Comment by v0lt** [comment]
Added in 9ce801a59499c3f182ca294cb92b57de246a7522.
The status of this resizer is experimental. I'm seeing some distortion at large scales. If you know how to fix this, please write.
