### ISSUE TITLE
The output seems to be a little green

### ISSUE THREAD

**Issue by hooke007** [Aleksoid1978/VideoRenderer#22]
After testing enough videos, I found the strange output of MPCVR.
The output shows a little green. And it is easy to be perceived if the the background of the picture is pure or light.
Compared with other video-renderers, I think it shows the incorrect output.
Another important problem is that, d3d11 seems to be more unstable (it creates many bandings)

![be d9](https://user-images.githubusercontent.com/41094733/103459065-67894c00-4d47-11eb-9031-8c907807beb3.jpg)
![be d11](https://user-images.githubusercontent.com/41094733/103459066-6d7f2d00-4d47-11eb-9ce7-654a3781da9c.jpg)
![madvr](https://user-images.githubusercontent.com/41094733/103459068-707a1d80-4d47-11eb-903e-a881a250e72d.jpg)
![mpv](https://user-images.githubusercontent.com/41094733/103459071-73750e00-4d47-11eb-8a86-805eb588b215.jpg)

**Comment by Aleksoid1978** [comment]
Upload sample video - i compare.

**Comment by v0lt** [comment]
You say that there is more green, but your frame is green in all pictures. There may be a slight difference in brightness or saturation.

**Comment by hooke007** [comment]
> You say that there is more green, but your frame is green in all pictures. There may be a slight difference in brightness or saturation.

I do not change the brightness or saturation, do you mean mpcvr did the extra process?

> Upload sample video - i compare.
> Show Options.

[sample1-seg1 (1).zip](https://github.com/Aleksoid1978/VideoRenderer/files/5761262/sample1-seg1.1.zip)
[Snipaste_2021-01-03_13-43-03](https://user-images.githubusercontent.com/41094733/103472637-87ae1f00-4dca-11eb-823d-ee88f44ff9a0.jpg)

**Comment by hooke007** [comment]
I tested the white (255,255,255), and I found it often outputted the (253,254,253) (maybe lower)
Other vrs are correct.
[screenshots.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5761287/screenshots.zip)
[sample2-B&W.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5761292/sample2-B.W.zip)

**Comment by v0lt** [comment]
I see a problem (+1 to green, rarely +2) only for 10-bit video and shader VP. I don’t understand how you look at it.
Try version [0.5.1.1600_git2021.01.03-6622539](https://yadi.sk/d/X0EVMKP4TcmnHQ) anyway.

**Comment by hooke007** [comment]
> I see a problem (+1 to green, rarely +2) only for 10-bit video and shader VP. I don’t understand how you look at it.
> Try version [0.5.1.1600_git2021.01.03-6622539]

Tested again with the latest version of mpcvr by sample2-B&W.zip on another PC, I saw the same problem as before.

**Comment by v0lt** [comment]
Test build - [mpcvr-1600_fixUV_1.zip](https://yadi.sk/d/NGDX8dvluwQoUg?w=1)

**Comment by hooke007** [comment]
Maybe worse. White(253,255,252) Black(0,1,0)
[Snipaste_2021-01-06_17-16-35.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5774858/Snipaste_2021-01-06_17-16-35.zip)

**Comment by Aleksoid1978** [comment]
Test build
[MPCVideoRenderer-0.5.1.1605_git2021.01.11-b51f251.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5806516/MPCVideoRenderer-0.5.1.1605_git2021.01.11-b51f251.zip)

**Comment by hooke007** [comment]
Perfect, it seems also solve the another problem (banding).

**Comment by v0lt** [comment]
[MPCVideoRenderer-0.5.1.1606_git2021.01.13-3735f30](https://yadi.sk/d/X0EVMKP4TcmnHQ)
Please check.

**Comment by hooke007** [comment]
It works well too.

**Comment by v0lt** [comment]
Thank you.
