### ISSUE TITLE
No subtitles

### ISSUE THREAD

**Issue by fcuk02** [Aleksoid1978/VideoRenderer#23]
Playing video has no subtitles
Only work with default video renderer

**Comment by Aleksoid1978** [comment]
What version VideoRenderer use ?
What player(version) use ?

**Comment by fcuk02** [comment]
0.5.1.1604
MPC-HC 1.9.8.115

**Comment by Aleksoid1978** [comment]
All working perfect.
![изображение](https://user-images.githubusercontent.com/11625603/104114681-d15eb280-5352-11eb-9581-1732ecb1553f.png)

**Comment by fcuk02** [comment]
Default Subtitle Renderer

**Comment by fcuk02** [comment]
Can you try with default MPC Video Renderer setting

**Comment by fcuk02** [comment]
Same issue using MPC-BE

**Comment by fcuk02** [comment]
I finally made it work by installing it instead of using as external filter
Why does subtitle only work if Video Renderer is install?

**Comment by Aleksoid1978** [comment]
Full working only if install and select as video renderer.
