### ISSUE TITLE
DX11 dithering and mpc-be shaders

### ISSUE THREAD

**Issue by dezo2** [Aleksoid1978/VideoRenderer#26]
Hi, when I use dx11 and 10bit integer + dithering, post-resize pixel shader (sharpen complex 2) stops working. When I disable dithering, sharpen shader works again. This is working together in dx9 no problem, so I use dx9 for now. Is there perhaps some incompatibility between dithering and post-resize shaders in dx11? I need dithering to avoid banding when converting from 10bit internal to 8bit display.
Setup: mpc-be 1.5.6.6000, mpc VR 0.5.2.1607, win10 (1909), gpu RTX2080 (driver 456.71)

**Comment by Aleksoid1978** [comment]
Fixed.

**Comment by dezo2** [comment]
That was quick. Thanks!
