### ISSUE TITLE
When using d3d11, subs cannot be rendered

### ISSUE THREAD

**Issue by hooke007** [Aleksoid1978/VideoRenderer#28]
If selecting the option "use direct3d 11", subs cannot be rendered by the mpc-be's internal sub-renderer. I have to use the xysubfilter instead to show the subtitle in that case.

ps.
MPC-BE.1.5.7.6180.x64
MPCVideoRenderer_git_0.5.3.1689_x64

**Comment by Aleksoid1978** [comment]
All working perfect. Try reset settings.
Show filter list in MPC-BE.
What subtitles ?

**Comment by hooke007** [comment]
MPC-BE 1.5.7.6180
Filters currently loaded:
  - MPC Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - MPC Video Decoder
  - MPC Audio Decoder
  - MPC Matroska Source

default setting is OK. But selecting "use direct3d 11" is not OK.

Any kinds of subs.

**Comment by Aleksoid1978** [comment]
Try latest version.
[latest_x64.zip](https://github.com/Aleksoid1978/VideoRenderer/files/6339806/latest_x64.zip)

**Comment by hooke007** [comment]
No, it doesn't work.

**Comment by Aleksoid1978** [comment]
Hmm, can’t help. works for everyone except you.

**Comment by hooke007** [comment]
Hmm..Sorry, I heard the issue from my friends and reproduced it in my PC. (He doesn't know where to post the bug.)
Maybe keep it open to see if more people will meet this kind of problem.

**Comment by Aleksoid1978** [comment]
Video driver latest ?

**Comment by hooke007** [comment]
Yes.

**Comment by Aleksoid1978** [comment]
Here debug build + DbgView.
run DbgView, then player, open video with subtitles, close player, save log in DbgView and upload for me.
[MPCVideoRenderer-0.5.3.1699_git2021.04.08-1c833a0_Debug.zip](https://github.com/Aleksoid1978/VideoRenderer/files/6341918/MPCVideoRenderer-0.5.3.1699_git2021.04.08-1c833a0_Debug.zip)

**Comment by hooke007** [comment]
[d3d11.LOG](https://github.com/Aleksoid1978/VideoRenderer/files/6341978/d3d11.LOG)

**Comment by Aleksoid1978** [comment]
Something wrong, can't create shared texture DX9 -> DX11(it use for subtitles render).

**Comment by hooke007** [comment]
I have some findings to help. My device is laptop which have two GPU. when I use the internal monitor. The output was totally controlled by iGPU and it's OK. When I use the external monitor, 2070 control the output. In this case, d3d11 cannot show the subs.

**Comment by Aleksoid1978** [comment]
We don't have such hardware, can't help.

**Comment by clsid2** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-opensharedresource

Maybe wrong interface used in call to OpenSharedResource()? Use D3D9 texture instead of D3D11 texture?

**Comment by Aleksoid1978** [comment]
No - all is good :)

**Comment by hooke007** [comment]
> https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-opensharedresource
> 
> Maybe wrong interface used in call to OpenSharedResource()? Use D3D9 texture instead of D3D11 texture?

I don't know the differences about the internal sub-render between HC and BE. HC's internal sub-render can show the subs.

**Comment by Aleksoid1978** [comment]
Hm, the same HC/BE.

**Comment by Aleksoid1978** [comment]
It's Nvidia Optimus. Maybe MPC-HC set to Nvidia but MPC-BE to Intel or auto. Try set MPC-BE as MPC-HC or something else :)

**Comment by hooke007** [comment]
A good solution. I firstly forced it to run by Nvidia in the driver settings but failed again. So I use the Nvidia Inspector to add the be with hc. It works!
![Snipaste_2021-04-23_19-40-07](https://user-images.githubusercontent.com/41094733/115866056-bcbeaa00-a46b-11eb-96df-1b6cf6d21e26.jpg)
