### ISSUE TITLE
Speeding up playback in a Virtual Machine

### ISSUE THREAD

**Issue by Zero3K** [Aleksoid1978/VideoRenderer#3]
It would be nice if playback of videos using it when in a Windows 7 Virtual Machine ran by Windows Virtual Machine was sped up. I am able to use it by placing the WineD3D for Windows and Mesa3D dlls in the directory where mpc-be.exe is located.

**Comment by v0lt** [comment]
We do not have the competence and ability, and do not plan to add special code for virtual machines.

**Comment by Zero3K** [comment]
Maybe someone else could do it. Its nice that it is as fast as it is (maybe its faster in a ReactOS based guest).
