### ISSUE TITLE
enabling d3d11 causes subtitle to disappear in potplayer

### ISSUE THREAD

**Issue by wanderforwater** [Aleksoid1978/VideoRenderer#31]
potplayer loses the ability  to show information when pressing the tab button as well as subtitles no longer show when playing a video with subtitles but all the above problems occur only when d3d11 is enabled in mpc video renderer otherwise this renederer is amazing thanks also can you tell me which settings you use for the best quality image in mpc video renderer i would greatly appreciate that

**Comment by wanderforwater** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/89676390/131206020-8355f129-c5ab-4a7b-a60e-96d9a5c006f9.png)
This is the tab menu which doesn't work when d3d11 is enabled

**Comment by Aleksoid1978** [comment]
Ask Pot's author

**Comment by wanderforwater** [comment]
👍
