### ISSUE TITLE
MPC Video Renderer "ruins" HDR in 16.4.5

### ISSUE THREAD

**Issue by BigS12** [Aleksoid1978/VideoRenderer#32]
[https://i.servimg.com/u/f61/20/37/12/61/mpc_vi10.jpg](url)
[https://i.servimg.com/u/f61/20/37/12/61/mpc_vi11.jpg](url)

Please excuse my english, and noob skills explaing my issue, but here we go. :) 

HDR doesn't work out of the box, with K-lite codec ver. 16.4.5 compared to 16.4.0, because of the new setting under HDR. See pics.
This because, with 16.4.5, it's not possible to save the settings in "Auto Display HDR On/Off".
It always reverts to "not used" the next time you open MPC HC.
So you need to change manually to "always used", everytime you play a mkv with HDR support for example.

I rolled back to 16.4.0 where it works flawlessly, with just the option "on/off". (not the three "not used" / "used for fullscreen" / "always used" options)

**Comment by Aleksoid1978** [comment]
Thx - wait fix.

**Comment by clsid2** [comment]
Lo/Hi values in discard function are incorrect when reading the setting.

**Comment by Aleksoid1978** [comment]
Fixed.

**Comment by clsid2** [comment]
Default value is now OFF. Any reason why it is not ALWAYS?

**Comment by v0lt** [comment]
There was a typo. The current default is "used for fullscreen". 
```
int  m_iHdrToggleDisplay = HDRTD_Fullscreen;
m_Sets.iHdrToggleDisplay = discard<int>(dw, HDRTD_Fullscreen, HDRTD_Off, HDRTD_Always);
```
I'm not sure if the default is "always used". I don't have an HDR display.

**Comment by v0lt** [comment]
In 0477f32, the "HdrToggleDisplay" option is now "always used" by default.

**Comment by BigS12** [comment]
Tested with k-lite codec pack, update 14.4.6, and it works perfectly.
Thanks.

Sendt fra E-post for Windows

Fra: v0lt
Sendt: lørdag 18. september 2021 kl. 13.00
Til: Aleksoid1978/VideoRenderer
Kopi: BigS12; Author
Emne: Re: [Aleksoid1978/VideoRenderer] MPC Video Renderer "ruins" HDR in16.4.5 (#32)

In 0477f32, the "HdrToggleDisplay" option is now "always used" by default.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
