### ISSUE TITLE
Dropping frames when using DmitriRender

### ISSUE THREAD

**Issue by ROOOCCCK** [Aleksoid1978/VideoRenderer#33]
Когда я воспроизвожу вашу работу с MPC-HC и заполнителем кадров DmitriRender, у меня возникают проблемы с периодическим падением кадров, но она воспроизводится стабильно с рендером MADVR, в чем причина этого?

**Comment by Aleksoid1978** [comment]
А при чем здесь этот проект ?

**Comment by clsid2** [comment]
I think he uses MPCVR.

DmitriRender is filter that can be placed between decoder and renderer. It converts/interpolates framerate to 60fps, similar to SVP.

Dropped frames usually just means your GPU is not fast enough to process the video. Make screenshot with Renderer OSD enabled (press Ctrl+J) with both madVR and MPCVR.

You can try disabling the video processor options in MPCVR. Then it uses shaders for scaling.

**Comment by zhangsenpei** [comment]
> 我想他用 Mpcvr
> 
> DmitriRender 是可放置在解码器和渲染器之间的过滤器。它转换/插值帧到 60fps，类似于 SVP。
> 
> 掉落的帧通常只是意味着您的 GPU 处理视频的速度不够快。使屏幕截图与渲染器 OSD 启用 （按 Ctrl+J） 与疯狂VR和 MPCVR。
> 
> 您可以尝试禁用 MPCVR 中的视频处理器选项。然后，它使用遮阳机进行缩放。

Thank you for your message, I have been using your updated production MPC-HC, it is very useful.
The performance of my computer is sufficient (R7-5800H+NVIDIA 3060), and the frame filling is possible, the GPU occupies about 40% when using MPCVR to fill frames, in some static screens and switching scenes DmitriRender will pause the frame filling work and resume about 3 seconds. This is not the case when using MADVR for rendering, mainly because MADVR consumes too much, so you want to use MPCVR for quality playback effects.
The difference is only the renderer, so I'll leave a message for this developer to see what the solution is

Translated with www.DeepL.com/Translator (free version)

**Comment by zhangsenpei** [comment]
Compensated frame rate of 165

**Comment by Aleksoid1978** [comment]
I don't use DmitriRender - it's not free.
If you want - write author of DmitriRender.

**Comment by Aleksoid1978** [comment]
Check using trial DmitriRender, videocard - 1650, test on VP9/HEVC 4K 10bit using DX11 Native Decoder + DX11 output in MPC VR - perfect playback, 24fps -> 60fps, there is no issue, not dropped frames. GPU loading 30-50%.

**Comment by clsid2** [comment]
> Compensated frame rate of 165

That is a very high refreshrate. Test if it works better with much lower rate. 

Video playback does not work well with variable refreshrate (GSync/FreeSync). It is recommended to disable that in the driver settings for the player.

**Comment by zhangsenpei** [comment]
> Check using trial DmitriRender, videocard - 1650, test on VP9/HEVC 4K 10bit using DX11 Native Decoder + DX11 output in MPC VR - perfect playback, 24fps -> 60fps, there is no issue, not dropped frames. GPU loading 30-50%.
> Test in MPC-BE.
> 
> And as was saying before - show screenshot with statistics(Ctrl+J).

Hello, may I ask how long you test the video, I watch 10 minutes in a row basically will pause to fill the frame situation, the rest of the time is also perfect playback, MADVR is no matter how long to play the whole stable frame will not pause

**Comment by zhangsenpei** [comment]
> > Compensated frame rate of 165
> 
> That is a very high refreshrate. Test if it works better with much lower rate.
> 
> Video playback does not work well with variable refreshrate (GSync/FreeSync). It is recommended to disable that in the driver settings for the player.

Hello, should not have much to do with the frame rate, I look at 10 minutes in a row will basically pause to fill the frame situation, the rest of the time is also perfect play, MADVR filter or EVE CP filter will not appear to pause to fill the frame situation

**Comment by Aleksoid1978** [comment]
WHERE IS SCREENSHOT WITH STATISTICS(Ctrl+J). Do it when frame start dropped.

**Comment by v0lt** [comment]
Skipping video frames in the general case is not a problem. It will always be happening if the video frequency is greater than the display frequency. It will also happen if the frame is obtained with a delay from the previous filter.
Maybe Dmitrirender is trying to add too many frames and it is worth limiting it appetite.

In any case, will advise using MPC-BE.
You can also try to change the following MPC VR settings: 
- Use Direct3D 11 = On/Off
- Swap effect = Flip
- Wait for VBlank before Present = On/Off

**Comment by catshitz** [comment]
> using mpc-be+mpcvr same setting above with only dimitrirender activated, testing for a long while, conclusion is DmitriRender just won't work with mpc video render(red taskbar icon ocassionally).
Wonder if mpcvr works with svp4 pro?
