### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by johnpatrick9** [Aleksoid1978/VideoRenderer#4]
Hello,I am unable to install the video renderer,I keep getting the following error whenever I try to run the batch file in administrator mode
"'regsvr32.exe' is not recognized as an internal or external command,
operable program or batch file.

   Installation failed.

   You need to right click "Install_MPCVR_64.cmd" and choose "run as admin"."
And I am using windows 7 ultimate x64.Could someone please help me out?

**Comment by Aleksoid1978** [comment]
Something wrong with you system - regsvr32.exe always present on any Windows version.
try that - run cmd.exe as administrator, type "where regsvr32.exe" and hit enter. What output ?

**Comment by johnpatrick9** [comment]
and here is the output
C:\Windows\system32>where regsvr32.exe
C:\Windows\System32\regsvr32.exe

**Comment by v0lt** [comment]
Did you unblock the archive after downloading?

**Comment by LucianAndries** [comment]
Hello.

I'm new, so I'm stupid. But how do I install this?
I ran it as admin, it says successful, but it doesn't show anywhere in MPC........ :(

**Comment by johnpatrick9** [comment]
> 
> 
> Did you unblock the archive after downloading?

It's was not blocked and further I extracted it to where mpc player is located and tried to run it there but still showed the same error @v0lt

**Comment by v0lt** [comment]
1. Unzip the files from the archive into a separate folder on drive C:
2. Find "cmd" or "Command line" in the Start menu. Run it as an administrator.
2. Execute the CD command
`CD "c:\path_to_your_folder"`
Make sure that the current folder on the command line matches the folder where the extracted files are located.
PS: You can run the "DIR" command to view a list of files.
3. Run the command
`regsvr32.exe MpcVideoRenderer64.ax`
Read the message.

**Comment by johnpatrick9** [comment]
I get the same thing and here is the output
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd "C:\Users\user\Desktop\New folder (2)"

C:\Users\user\Desktop\New folder (2)>regsvr32.exe MpcVideoRenderer64.ax
'regsvr32.exe' is not recognized as an internal or external command,
operable program or batch file.
@v0lt

**Comment by v0lt** [comment]
You can try using this command
`C:\Windows\System32\regsvr32.exe MpcVideoRenderer64.ax`
I think something is wrong with your system, as the path "_C:\Windows\System32_" must be written in the variable "_Path_".

**Comment by johnpatrick9** [comment]
Oh ok thank you so much for the help it works now @v0lt
