### ISSUE TITLE
HDR videos freezes

### ISSUE THREAD

**Issue by fcuk02** [Aleksoid1978/VideoRenderer#41]
0.5.7.1811
HDR videos with VP9 codec does not play using MPC-BE 1.6.1.6784
0.5.6.1807 works

**Comment by Aleksoid1978** [comment]
I check some VP9 10-bit HDR videos - all is good.

**Comment by v0lt** [comment]
> Some HDR videos with VP9 codec

Can you provide examples of "some HDR videos"?

**Comment by Aleksoid1978** [comment]
Check HEVC 10-bit HDR.

**Comment by Aleksoid1978** [comment]
MPC-BE - what filters use, internal or some external, like LAV ?

**Comment by fcuk02** [comment]
HEVC HDR works
only HDR videos downloaded from Youtube does not work

**Comment by v0lt** [comment]
What video card do you have?

**Comment by fcuk02** [comment]
Video card is not the problem it the latest nightly build

**Comment by clsid2** [comment]
Please answer simple questions like which GPU do you have. Developers ask them for a reason! Your problem can not magically be solved without proper information.

For example latest AMD driver has a crash bug with HDR.

If playback freezes, then there may actually be a probably with decoding, rather than a problem with the renderer.

**Comment by fcuk02** [comment]
GTX 960
0.5.6.1807 no problem
install 0.5.7.1811 video freezes

**Comment by v0lt** [comment]
Hmm.
What operating system?
What version of the video driver?

**Comment by Aleksoid1978** [comment]
Monitor with HDR support ?

**Comment by fcuk02** [comment]
Yes DisplayHDR 1000

**Comment by Aleksoid1978** [comment]
Show Video Renderer settings.

**Comment by v0lt** [comment]
Try this build  - [mpcvr_1811_revert_47887db](https://disk.yandex.ru/d/tkbqRJRKLPNd5A)

**Comment by fcuk02** [comment]
It works perfectly thank you
