### ISSUE TITLE
Tearing with enabled Direct3D 11 option on Win7

### ISSUE THREAD

**Issue by bw4518** [Aleksoid1978/VideoRenderer#42]
I do have a noticeable tearing with Direct3D 11 enabled (exclusive fullscreen), but no tearing when Direct3D 11 is disabled.

**Comment by Aleksoid1978** [comment]
Don't use Direct3D 11 :)

**Comment by Aleksoid1978** [comment]
Use Aero or classic themes ?

**Comment by bw4518** [comment]
Yes, I use some custom theme, no Aero.

**Comment by Aleksoid1978** [comment]
Enable Aero or don't use D3D11.
