### ISSUE TITLE
DV (Dolby Vision) File has green tint...

### ISSUE THREAD

**Issue by isarrider** [Aleksoid1978/VideoRenderer#44]
Hallo,

a DV (Dolby Vision) File plays with green tint...
Is this known?

BR,
Alex

**Comment by clsid2** [comment]
Dolby Vision is yet not supported.

**Comment by isarrider** [comment]
ah...
and if it is just ignored?
My understanding is that DV should be ignored by incompatible Players...

**Comment by clsid2** [comment]
@Aleksoid1978
If you guys ever want to add support for DV tonemapping, or improve HDR10 tonemapping quality, then have a look at libplacebo.

https://code.videolan.org/videolan/libplacebo

**Comment by isarrider** [comment]
> It is ignored, resulting in the green/purple/pink colors.

Seems it depends on the level...
my file is Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU,
and this is the only one that isnt cross compatible with anything... ;)
https://professionalsupport.dolby.com/s/article/What-is-Dolby-Vision-Level?language=en_US

thx!
