### ISSUE TITLE
[Bug] Green screen at right side of video

### ISSUE THREAD

**Issue by Alp1821** [Aleksoid1978/VideoRenderer#46]
MPC VR can not play one of my videos properly when D3D11 is checked in renderer settings. Which is enabled by default in the latest version you know.
When I unchecked D3D11 in renderer settings then the problem is gone.

Why is it happening? This needs to be fixed or D3D11 should be disabled by default as before it was.

[Using win 10, MPC HC x64 latest. Don't know the problem is there in MPC BE or not? I use MPC HC only]

![Screenshot (238)](https://user-images.githubusercontent.com/98865389/153353256-52352f71-03ed-43b9-b78c-957a6811e842.png)
![Screenshot (239)](https://user-images.githubusercontent.com/98865389/153353268-387497a5-82de-4e7a-81c9-3cfb8f1b14a6.png)

**Comment by Klaus1189** [comment]
Upload sample file to google drive or similar

**Comment by Alp1821** [comment]
I have trimmed the video to save my mobile data, without re encoding using Avidemux. The trimmed video is also having same usse, so you can check this.

https://drive.google.com/file/d/1YX7Jxs0jiZEKOS1NJKTQRLXUCOFKbLw6/view?usp=sharing



[And also you are aware of the issue that MPC HC freezes randomly when using MPC VR. CPU usage drops to zero at that situation. Audio stills plays.
No such problem when using EVR CP.
I have seen that many people reported that issue at different places but no proper solution found]

**Comment by Klaus1189** [comment]
I tested it using MPC-BE with internal Filters and with external LAV Filters with both EVR custom and MPC Video Renderer in both D3D9 and D3D11 and never experienced an problem.

What GPU do you use?
What driver is installed?
Can you please download the latest stable or nightly to test with MPC-BE:
latest stable: https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.6.1/
latest nightly: https://disk.yandex.com/d/hlf1lfC8mKU58/1.6.2.6893

**Comment by Klaus1189** [comment]
I just googled the Nikon and found a videoclip straight from the cam:
https://img.photographyblog.com/reviews/nikon_coolpix_l26/sample_images/nikon_coolpix_l26_01.avi

**Comment by Alp1821** [comment]
Intel hd graphics 4400
Driver 10.18.15.4248

This version is download from hp's driver page.
There is a newer version available in intel website but that version has something issue with my laptop. Doesn't work properly. So i use that version instead of newer one.

**Comment by Alp1821** [comment]
> I just googled the Nikon and found a videoclip straight from the cam: https://img.photographyblog.com/reviews/nikon_coolpix_l26/sample_images/nikon_coolpix_l26_01.avi

Same issue in this video. If I untick Direct3D 11 in MPC VR settings then there is no issue.


If the issue is only in my system then it must be some driver related issue. Leave it.
Thanks for your time.

**Comment by Aleksoid1978** [comment]
Enable statistics in MPC VR - "Show statictics" in options.
And take a screenshot.

**Comment by clsid2** [comment]
4:2:2 chroma is probably what make this file different from others.

**Comment by Alp1821** [comment]
MPCVR default settings vs Direct3D 11 unchecked

![Screenshot (242)](https://user-images.githubusercontent.com/98865389/153535670-a96bd504-a921-4903-9535-7d7bf86469cc.png)
![Screenshot (243)](https://user-images.githubusercontent.com/98865389/153535692-1656a5c9-9bd1-4156-b7cc-8433dbe5373d.png)

**Comment by Alp1821** [comment]
> 4:2:2 chroma is probably what make this file different from others.

That MJPG codec is very rare. Is that a problem?

**Comment by Klaus1189** [comment]
D3D11VP caused already some problems on old GPUs.

**Comment by Alp1821** [comment]
Then default settings of MPCVR should be revert to that of previous version. Because DXVA2 does not have problem with old GPUs.

**Comment by Aleksoid1978** [comment]
No, we will not remake for old hardware/drivers.
This is not a renderer issue, but a video driver issue.
You can uncheck "Other supported formats" in MPC VR settings to disable D3D11 VP(video processor).

**Comment by Alp1821** [comment]
That settings is already disabled, as you told before.
Disabling Direct3D 11 fixed the problem for me.

**Comment by Alp1821** [comment]
@clsid2 why don't you include MPCVR in MPCHC setup. It's very good renderer and also uses less GPU compared to EVR CP.

Also very small is size, less than MB.
Please add it if possible 🙏

**Comment by v0lt** [comment]
I cannot reproduce the problem. 
Intel HD 4000, Win10 x64, MPC VR 0.5.7.1813
![MPC-VR_YUY2](https://user-images.githubusercontent.com/2035946/153623684-f3ef6cef-f133-41c4-bdd6-f7dae69f3dfb.PNG)

**Comment by v0lt** [comment]
Changing the target resolution does not cause a bug.

**Comment by Alp1821** [comment]
There are so many videos of same res. 1280x720. Same target res. 1365x768
No issue with them.
Driver bug may be.

![Screenshot (246)](https://user-images.githubusercontent.com/98865389/153697358-fa1166b5-b303-4d94-9063-da61c6837a01.png)

**Comment by Alp1821** [comment]
> As i say before - You can uncheck "YUV2" in MPC VR settings to disable D3D11 VP(video processor).

Yes I have done it. No issue when YUV2 is unchecked. Working well.

Basically my last comment was reply to clsid2's last comment.
Close the issue if u want.
