### ISSUE TITLE
Unhandled exception occurred at atiumd6a.dll on AMD 5800U

### ISSUE THREAD

**Issue by gongjimin** [Aleksoid1978/VideoRenderer#47]
If I play HDR video on monitor support HDR, the MPCVR  on potplayer will turn on the HDColor on Win10, then crash with this:
```text
---------------------------
Alert
---------------------------
Unhandled exception occurred[0xC0000005@0x0000000073754CE9] at atiumd6a.dll

Additional exception information has been stored locally

and this application will be terminated.
```
My CPU+GPU is AMD R7 5800U.

I've tried MPC-BE and almost the same thing happen. MPC-BE crashed and I found Error Reporting in Event shows:
```text
故障存储段 1849426165357592173，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: mpc-be64.exe
P2: 1.6.1.6845
P3: 61f63818
P4: atiumd6a.dll
P5: 30.0.14023.7007
P6: 61f0b056
P7: c0000005
P8: 0000000000214ce9
P9: 
P10: 
```

**Comment by clsid2** [comment]
Revert to AMD 21.11.3 driver.

**Comment by gongjimin** [comment]
> Revert to AMD 21.11.3 driver.

Thank you very much.
I‘ve installed 21.11.3 driver and it's OK now.

Is there some plan to compatible new drivers of AMD？

**Comment by v0lt** [comment]
> Is there some plan to compatible new drivers of AMD？
We have no plans to adapt to driver bugs. Use drivers without bugs.

**Comment by gongjimin** [comment]
Thanks. I Think I can tell this to AMD. :)
