### ISSUE TITLE
Dithering from 10-bit to 8-bit is not working well.

### ISSUE THREAD

**Issue by FX8350** [Aleksoid1978/VideoRenderer#48]
Hi

I encoded the 8-bit video (from BD) to 10-bit x265 using the following command of ffmpeg.
`ffmpeg -i input.m2ts -pix_fmt yuv420p10le -c:v libx265 out.mp4`
When I play it with MPC-xx+MPC-VR, there is a slight but noticeable color problem. (A little strong green-color)
I've tried changing settings `Texture format:` and `Use dithering` but that doesn't fix the problem.
I don't have the GPU that have the hardware decoder for HEVC, so I use software decoding for playback.
The following is an example, but I have tried it with several Blu-rays I own, and they all gave the same result.
<details>
<summary>Original, 8-bit H.264</summary>

![00000 m2ts_snapshot_10 23 845](https://user-images.githubusercontent.com/10481430/154836865-073bc9bc-624d-4507-83f2-41dd144ea0d7.png)
</details>
<details>
<summary>10-bit HEVC, MPC-HC/MPC-BE with MPC-VR</summary>

![MPC-VR](https://user-images.githubusercontent.com/10481430/154836932-bd253034-3b03-4876-8f94-88992efab88c.png)
</details>
<details>
<summary>10-bit HEVC, MPC-BE with built-in EVR-CP</summary>

![MPC-BE](https://user-images.githubusercontent.com/10481430/154836975-ee316e17-7c26-44ed-960c-ff97738e8ac0.png)
</details>
<details>
<summary>10-bit HEVC, MPC-HC with built-in EVR-CP</summary>

![MPC-HC](https://user-images.githubusercontent.com/10481430/154836987-e48f6cd1-ba95-4869-851d-8d18233366e8.png)
</details>

My system environment:
MPC Video Renderer 0.5.7.1811 (git-2021.12.21-f448e90) x64
MPC-BE 1.6.1.6845 x64
MPC-HC 1.9.19 x64
NVIDIA GeForce GTX 750 Ti with 472.12 driver
8-bit monitor (Dell AW3418DW)

UPDATE: I have tried 8-bit and 12-bit encoding, and both seem to play fine.
<details>
<summary>8-bit HEVC, MPC-HC/MPC-BE with MPC-VR</summary>

whitout any `-pix_fmt` option
![test_8bit mp4_snapshot_02 10 408](https://user-images.githubusercontent.com/10481430/154846850-1f06ad20-7955-40a2-891d-72a510884eaa.png)
</details>
<details>
<summary>12-bit HEVC, MPC-HC/MPC-BE with MPC-VR</summary>

with the `-pix_fmt yuv420p12le` option
![test_12bit mp4_snapshot_02 10 227](https://user-images.githubusercontent.com/10481430/154846886-ed4703ae-d8d4-41aa-b127-8abf4b0352ee.png)

**Comment by v0lt** [comment]
Compare renderer statistics when playing input.m2ts and out.mp4.

**Comment by FX8350** [comment]
Here is the status of renderers
<details>
<summary>out.mp4 with MPC-VR</summary>

![MPC-VR_HEVC](https://user-images.githubusercontent.com/10481430/154841305-fbc7d0ce-deb8-4eb8-986b-d8c5ff4c21ee.png)
</details>
<details>
<summary>out,mp4 with EVR-CP</summary>

![EVR_HEVC](https://user-images.githubusercontent.com/10481430/154841089-c51180e2-2842-4466-bbad-7d2c4ebb9f01.png)
</details>
<details>
<summary>input.m2ts with MPC-VR</summary>

![MPC-VR_H264](https://user-images.githubusercontent.com/10481430/154841274-b5b7eba4-d6c6-4c49-a6ae-771f8a31dcaa.png)
</details>
<details>
<summary>input.m2ts  with EVR-CP</summary>

![EVR_H264](https://user-images.githubusercontent.com/10481430/154841119-c6852c39-c910-4db3-91dc-70792f587440.png)
</details>

**Comment by v0lt** [comment]
I switch these two screenshots:
_input.m2ts with MPC-VR
out.mp4 with MPC-VR_
The video frame parameters are the same (only the format of the input texture is different). I don't see the difference in the pictures.

**Comment by FX8350** [comment]
>I don't see the difference in the pictures.

Does this mean that there is no difference in color between those two pictures?
Hmm...
![image](https://user-images.githubusercontent.com/10481430/154856376-8818dec9-800f-4f4f-8b29-517341078504.png)
![YUV](https://user-images.githubusercontent.com/10481430/154856713-e2429312-1fef-4788-acde-954e3cffc1b0.png)
This shows the YUV histogram of each screenshot.
The top left is input.m2ts, the top right is out.mp4 (MPC-VR), the bottom left is out.mp4 (EVR-CP), and the bottom right is 8-bit HEVC (MPC-VR).
Only in out.mp4+MPC-VR is there a noticeable difference in the histogram of U. ...Isn't there?

**Comment by v0lt** [comment]
On your screenshots RGB. The renderer outputs RGB. Looking at the YUV histogram is strange to me.

To convert from NV12 and P010 to RGB you use D3D11 VP. This conversion is controlled by the driver manufacturer and MicroSoft.
But you can disable NV12 and P010 options and convert with our shader.

**Comment by v0lt** [comment]
Also, if you think Dithering is the problem, you can turn it off and check again.

**Comment by v0lt** [comment]
You can also use the software decoder for the original video too, so that the FFmpeg decoder is used in both cases.

**Comment by FX8350** [comment]
> On your screenshots RGB. The renderer outputs RGB. Looking at the YUV histogram is strange to me.

Sorry, here is the RGB histogram

<details>
<summary>input.m2ts histogram overlaid with EVR-CP histogram with translucency.</summary>

There is a difference in the histogram due to encoding, but it is basically accurate to input.m2ts.
![INPUT+EVR-CP](https://user-images.githubusercontent.com/10481430/154894461-fc910007-1123-41a5-a28e-95f24faaf3e7.png)
</details>
<details>
<summary>input.m2ts histogram overlaid with MPC-VR histogram with translucency.</summary>

There is more difference in the histograms for both R and B, but histogram of G is looks fine
![INPUT+MPC-VR](https://user-images.githubusercontent.com/10481430/154894440-a3f8b0a7-24ab-4fac-950e-7ee95a15752e.png)
</details>
<details>
<summary>EVR-CP histogram overlaid with MPC-VR histogram with translucency.</summary>

Playing the same video, but the histograms for R and B are different.
![EVR-CP+MPC-VR](https://user-images.githubusercontent.com/10481430/154894408-be672c34-4466-4494-bb81-c5a4c4b6aaed.png)
</details>
<details>
<summary>gif</summary>

![8FaWTaO11YIEtQGKhVTe1645422480-1645423112](https://user-images.githubusercontent.com/10481430/154897781-f0e89c28-9e3e-4cca-ba46-f0fe4002d34e.gif)
</details>


> To convert from NV12 and P010 to RGB you use D3D11 VP. This conversion is controlled by the driver manufacturer and MicroSoft.
> But you can disable NV12 and P010 options and convert with our shader.

Thanks, Disabling them fixed the problem.

**Comment by fireattack** [comment]
Sorry for necroing an old ticket.

Actually I think it's not Microsoft, it's nVidia. nVidia's D3D11 video processor (VP) has been having this green tint issue for years. 
In MPC-VR's context, it happens when you convert P010 to R10G10B10A2_UNORM. It does not happen if you use Intel iGPU like UHD 770.

(I remembered it also happens to DXVA2 in some other players; but at least it works fine in MPC-VR.)

I suspect #98 is also related to this than HDR.
