### ISSUE TITLE
Video Rotation

### ISSUE THREAD

**Issue by rin20000** [Aleksoid1978/VideoRenderer#49]
When rotating video in windowed mode the window size is not changing. In full screen mode it is working well. Using latest stable MPCVR.

This is how it works now:
![Screenshot (293)](https://user-images.githubusercontent.com/100745985/156293910-7cfb25c7-6ea4-423f-b81e-94db4a9414d6.png)

This is how it should:
![Screenshot (294)](https://user-images.githubusercontent.com/100745985/156293957-96067e6d-752f-435a-be1b-a134a115bfc1.png)

Well this particular video does not need rotation, I used it just to show you.

**Comment by v0lt** [comment]
> When rotating video in windowed mode the window size is not changing.

Yes. This is how rotation works, like other **frame** transformations.

> In full screen mode it is working well.

Works exactly the same as in the window. The full screen size does not change.

There is also a window maximized to full screen and it will also not change when you make frame transformations.

**Comment by v0lt** [comment]
In addition, I note that your ticket does not apply to the video renderer. **The size of the window is controlled by the player**.
I'm closing the topic.
