### ISSUE TITLE
Screen tearing with disabled Desktop Composition (Aero)

### ISSUE THREAD

**Issue by Zero3K** [Aleksoid1978/VideoRenderer#5]
How do I fix it? I am using the latest nightly of it and MPC-BE.

**Comment by Aleksoid1978** [comment]
1 - Show screenshot with Statistics(Ctrl+J) in MPC-BE.
2 - Record video from desktop to view on "tearing".

**Comment by Zero3K** [comment]
Here's a screenshot of the Statistics in MPC-BE:

![MPC-BE MPC Video Renderer Statistics](https://user-images.githubusercontent.com/6194332/72959041-0905d080-3d77-11ea-9f9a-bd304e94280b.png)

**Comment by v0lt** [comment]
Turn on Aero (Desktop Composition).

**Comment by Zero3K** [comment]
I am using the classic theme. So, that's not possible.

**Comment by Aleksoid1978** [comment]
1 - Try change "Swap effect" to Flip.
2 - Try this build https://yadi.sk/d/XQXeY6QjJB6hdg

**Comment by Zero3K** [comment]
I think that build made it worse. You can try searching for and downloading the video I was playing on animetosho.rg and see if you can replicate it.

**Comment by Zero3K** [comment]
*animetosho.org

**Comment by Aleksoid1978** [comment]
I don't have Windows 7 & don't use classic theme. With Aero and on Windows 10 - perfect playback.

**Comment by v0lt** [comment]
MPC Video Renderer works correctly only with the active [Desktop Window Manager](https://en.wikipedia.org/wiki/Desktop_Window_Manager).

**Comment by Zero3K** [comment]
It only happens during certain animations, not all the time.

**Comment by Aleksoid1978** [comment]
Disable subtitles output.

**Comment by Zero3K** [comment]
1. I tried that but it didn't help.
2. I have no screen tearing when using the Sync Video Renderer.

**Comment by v0lt** [comment]
>     2. The DWM service is running.
Turn on Aero, then DWM will really work.

**Comment by v0lt** [comment]
You can also try enabling VSync in the settings of the video driver.

**Comment by Zero3K** [comment]
I don't have the ability to change it.

**Comment by Aleksoid1978** [comment]
Why ? You don't have admin access to you PC ?

**Comment by Zero3K** [comment]
Any updates regarding this issue?

**Comment by Aleksoid1978** [comment]
Yes - enable Aero.

**Comment by Zero3K** [comment]
I am not going to enable Aero.

**Comment by Aleksoid1978** [comment]
Ok - don't use it's project :)

**Comment by clsid2** [comment]
Any plans to ever implement an optional custom VSync algorithm like in EVR CP/Sync? That would solve this issue.

Detecting if DWM composition is disabled is easy:
https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmiscompositionenabled

**Comment by Aleksoid1978** [comment]
Custom VSync not planned. And - I don’t want spend my time for classic themes :)

**Comment by Aleksoid1978** [comment]
Try this build
[MPCVideoRenderer-v0.4.10.1473_git2020.11.14-f942987.zip](https://github.com/Aleksoid1978/VideoRenderer/files/5540317/MPCVideoRenderer-v0.4.10.1473_git2020.11.14-f942987.zip)

**Comment by Zero3K** [comment]
That doesn't help.

**Comment by Aleksoid1978** [comment]
Ok. So - enable Aero or don’t use VR.
