### ISSUE TITLE
Compatibility issues with vega8 in the 5800h

### ISSUE THREAD

**Issue by wxmjzt** [Aleksoid1978/VideoRenderer#54]
Recently, I bought a new Lenovo laptop(R7 5800H+RTX 3050).  When I use the MPC Video Renderer with MPC-BE or MPC-HC on the vega8 integrated graphics, it has some compatibility issues.
When I use the old driver(27.20.14032.9002) downloaded from Lenovo's official website, the video will overexposure, and the aliasing is very clear in anime.
When I use the latest Adrenalin Edition driver downloaded from AMD's official website, the overexposure is disappear, but the color of video is reddish.
When I force the MPC-HC or MPC-BE running on the RTX 3050, everything is correct.

**Comment by Aleksoid1978** [comment]
Enable statistics and made screenshots.

**Comment by wxmjzt** [comment]
![MPC-BE+mpcVR+Vega8](https://user-images.githubusercontent.com/53813295/168412261-f0d6639a-5049-4cf4-ae38-880e6cddcc9f.png)
![MPC-BE+mpcVR+RTX3050](https://user-images.githubusercontent.com/53813295/168412254-55a25043-ad38-4d93-805c-afec35399094.png)
![MPC-HC+mpcVR+Vega8](https://user-images.githubusercontent.com/53813295/168412267-577c1f03-b36d-4b10-9250-dd148e63dcbb.png)
![MPC-HC+madVR+RTX3050](https://user-images.githubusercontent.com/53813295/168412276-0e47b25a-e7f7-4ea6-97f5-dabe1dbae5c0.png)
Now the driver on Vega8 is Adrenalin 22.5.1

**Comment by Aleksoid1978** [comment]
About "the video will overexposure, and the aliasing is very clear in anime." - "DXVA2 and D3D11 video processor" -> uncheck "Use for resizing".
About wrong color - "Texture" -> try select "8-bit Integer".

**Comment by Aleksoid1978** [comment]
In any case, this is all 100% a driver bug.

**Comment by wxmjzt** [comment]
Thank you for your reply.
Unchecking "Use for resizing" is useful for solving aliasing.
But selecting "8-bit Integer" is no use for the wrong color.
I try to uncheck "Use Direct3D 11", then the color becomes correct. And the statistics change from "Direct3D 11" to "Direct3D 9Ex".
By the way, I don't think this is "all 100%" a driver bug. Because the madVR can work on the Vega8 normally. And the statistics in madVR show"D3D 11 windowed".

**Comment by Aleksoid1978** [comment]
madVR use all processing in DX9 and only render using DX11. We use all processing and render using DX11. It's AMD driver bug, something wrong when processing using DX11.

**Comment by clsid2** [comment]
Try adjusting video color profile in AMD settings:
https://www.amd.com/en/support/kb/faq/dh2-006

Custom preset allows you to tweak settings and turn color vibrance off.

**Comment by v0lt** [comment]
> When I use the old driver(27.20.14032.9002) downloaded from Lenovo's official website, the video will overexposure, and the aliasing is very clear in anime.

Update the driver and some color issues will most likely be resolved. I updated the driver from the AMD website and it worked for me. Notebook manufacturers rarely update drivers on their websites.

**Comment by wxmjzt** [comment]
> Try adjusting video color profile in AMD settings: https://www.amd.com/en/support/kb/faq/dh2-006
> 
> Custom preset allows you to tweak settings and turn color vibrance off.

I can only find a "Custom Brightness" in the Custom preset, there is no "Video Color Vibrance", even I use the Amernime Zone Unified Radeon 3rd-Party Driver. Do you know how to solve this problem?

**Comment by clsid2** [comment]
I don't have AMD. Looks like driver bug, so you should ask AMD for help.
