### ISSUE TITLE
Bad quality PGS sub scaling in DX11 mode

### ISSUE THREAD

**Issue by clsid2** [Aleksoid1978/VideoRenderer#58]
PGS subs get bad quality when (down)scaled. To reproduce, resize the player window to less than 1080p. Tested with latest MPC-BE nightly. Same happens with latest MPC-HC.

Only happens in DX11 mode. Quality is fine with DX9.

**Comment by Aleksoid1978** [comment]
Thx - fixed, but it's on player side.

**Comment by clsid2** [comment]
Thanks. I will port the changes to MPC-HC.
