### ISSUE TITLE
Distorted video

### ISSUE THREAD

**Issue by 2ndR** [Aleksoid1978/VideoRenderer#6]
When playing 10bit 4: 2: 0 movie with Use Direct3D11 checked, the color will be strange if Texture Format is other than 8bit integer

**Comment by Aleksoid1978** [comment]
Show screenshot with statistics.

**Comment by 2ndR** [comment]
Default Settings
![d](https://user-images.githubusercontent.com/60872236/74169449-af563f00-4c6e-11ea-8de6-f3e929d1ee62.png)

Use Direct3D11
Texture format 8-bit Integer
![a](https://user-images.githubusercontent.com/60872236/74169667-05c37d80-4c6f-11ea-843b-2ec87ac74e9b.png)
Texture format 10-bit Integer
![b](https://user-images.githubusercontent.com/60872236/74169519-ca28b380-4c6e-11ea-9171-a5707d6e8e3e.png)
Texture format 16-bit Floating Point
![c](https://user-images.githubusercontent.com/60872236/74169720-1e339800-4c6f-11ea-9d95-b87aea9a2cb7.png)

**Comment by Aleksoid1978** [comment]
Looks like bug in driver.
Try uncheck "DXVA2 and D3D11 video processor" -> "Use for:" -> "P010/P016"
And "Texture format" set to "Auto..."

**Comment by 2ndR** [comment]
The problem was avoided by making the scaling a shader, thank you
As for the driver, I tried the recently released Radeon Pro Software Enterprise 20.Q1 but did not see any improvement
I want to report the progress later

Screenshots will be posted again with the results of v0.3.8

v0.3.8.1060
Direct3D9
Texture format 8-bit Integer
![a](https://user-images.githubusercontent.com/60872236/74585917-a5915a80-5025-11ea-9dec-0afd2166860f.jpg)
Texture format 10-bit Integer
![b](https://user-images.githubusercontent.com/60872236/74585922-ad50ff00-5025-11ea-9587-dc7859609eca.jpg)
Texture format 16-bit Floating Point
![c](https://user-images.githubusercontent.com/60872236/74585924-b3df7680-5025-11ea-88ea-b99aac6e9f1b.jpg)
Direct3D11
Texture format 8-bit Integer
![d](https://user-images.githubusercontent.com/60872236/74585951-c659b000-5025-11ea-8252-c5c3cfbf32e1.jpg)
Texture format 10-bit Integer
![e](https://user-images.githubusercontent.com/60872236/74585955-ca85cd80-5025-11ea-910b-80ec94c16b16.jpg)
Texture format 16-bit Floating Point
![f](https://user-images.githubusercontent.com/60872236/74585957-cfe31800-5025-11ea-997c-7dfe795c1426.jpg)

v0.4.1.1130
Direct3D9
Texture format 8-bit Integer
![a](https://user-images.githubusercontent.com/60872236/74585966-f012d700-5025-11ea-95f9-38544345194c.jpg)
Texture format 10-bit Integer
![b](https://user-images.githubusercontent.com/60872236/74585968-f6a14e80-5025-11ea-90bd-b45c5c3bb394.jpg)
Texture format 16-bit Floating Point
![c](https://user-images.githubusercontent.com/60872236/74585972-fc972f80-5025-11ea-9e1d-82affada8443.jpg)
Direct3D11
Texture format 8-bit Integer
![d](https://user-images.githubusercontent.com/60872236/74585975-05880100-5026-11ea-82dc-a0f230d0c112.jpg)
Texture format 10-bit Integer
![e](https://user-images.githubusercontent.com/60872236/74585979-0b7de200-5026-11ea-9a61-a03a70ea1dec.jpg)
Texture format 16-bit Floating Point
![f](https://user-images.githubusercontent.com/60872236/74585983-120c5980-5026-11ea-9efb-c6a5c1fe4edf.jpg)

**Comment by v0lt** [comment]
Try this version
[MPCVideoRenderer-v0.4.2.1132_git2020.02.16-5a11686](https://yadi.sk/d/X0EVMKP4TcmnHQ)

**Comment by 2ndR** [comment]
MPC-BE 1.5.5.5080 x64
MPCVideoRenderer v0.4.2.1132
D3D11 Video Processor
Texture format 8-bit Integer
![a](https://user-images.githubusercontent.com/60872236/74601550-c9ff3c80-50e2-11ea-81cd-a13ced93381c.jpg)
Texture format 10-bit Integer
![b](https://user-images.githubusercontent.com/60872236/74601551-cf5c8700-50e2-11ea-9926-61b9da29eb4a.jpg)
Texture format 16-bit Floating Point
![c](https://user-images.githubusercontent.com/60872236/74601552-d4b9d180-50e2-11ea-99d6-36c2d6ecd57f.jpg)

No problems with other formats

Source
jellyfish-90-mbps-hd-hevc-10bit

**Comment by v0lt** [comment]
Thanks.
I close the Issue.
