### ISSUE TITLE
Framestimes change after resuming playback

### ISSUE THREAD

**Issue by daddy-cool** [Aleksoid1978/VideoRenderer#60]
![image](https://user-images.githubusercontent.com/5902578/183245845-f95e1c4b-de39-4c0f-871f-08199424e6b8.png)
As seen in the image, after resuming playback the frametimes sometimes become different and stay that way until I pause/resume or skip ahead 5 seconds.

Tested with MPC-HC 1.9.22 and MPC-BE 1.6.3 using MPC VR 0.6.1.1931

MPC VR Settings:
![image](https://user-images.githubusercontent.com/5902578/183245892-dab0e897-36a7-420b-921b-d416440d799b.png)
![image](https://user-images.githubusercontent.com/5902578/183245916-cf26ad8c-d622-4788-982e-693edef17f3a.png)
Also tested exclusive fullscreen -> same issue
Also tested with flip instead of discard -> same issue (could you explain the difference btw?)

Main problem is when the frametimes become like this:
![image](https://user-images.githubusercontent.com/5902578/183245934-1f7cee6c-61a6-46e7-9ad0-be177a707933.png)
This jitter won't go away unless I pause/resume so everytime I start a movie, pause it, etc I have to check that the frametimes are smooth otherwise I will see jitter/stutter on my OLED - when the frametimes are stable though I have butter smooth playback.
Also need to use 120Hz input with wait VBlank, as my OLED's built-in support for 24Hz playback is not stable enough to give me stutter-free 24Hz playback - need to send 120Hz input directly.

MadVR does not have a nice frametime graph like this so hard to compare but from testing with my eyes I can not reproduce this issue with MadVR.

Nvidia Settings: (G-Sync not enabled)
![image](https://user-images.githubusercontent.com/5902578/183246158-61fa266c-f187-4e1a-909e-bf999ed55a05.png)

Any ideas on how to fix this? As the issue goes away/comes back with resuming playback I assume it's not an issue with my settings but maybe I'm wrong and there is an easy fix out there :)

**Comment by clsid2** [comment]
Enabling Vertical Sync might help.

**Comment by daddy-cool** [comment]
You mean in the Nvidia settings?
![image](https://user-images.githubusercontent.com/5902578/183246636-858e301e-0e3b-4b76-9e01-537ccb4b4f58.png)
Tried that, no change sadly

**Comment by daddy-cool** [comment]
Copy and Paint are always at 0, Present is the one that seems problematic as I can reproduce several "states" of playback where present will behave very differently on the same scene:

Perfect Playback: Present is 1 and fluctuates +-1

"OK" Playback: Present is below 8 and fluctuates +-1

Problematic Playback: Present fluctuates between 0 and 8

**Comment by Aleksoid1978** [comment]
It's something specific with 120Hz output. Developers don't have such TV and can't test and do something.
What audio renderer use ?
Show Filters in MPC-BE when playback.

**Comment by daddy-cool** [comment]
MPC-BE 1.6.3.0
Filters currently loaded:
  - MPC Audio Renderer
  - MPC Video Renderer
  - Audio Switcher
  - MPC Video Decoder
  - MPC Audio Decoder
  - MPC Matroska Source

MPC Audio Renderer:
![image](https://user-images.githubusercontent.com/5902578/183247499-2748807e-018f-4bfc-b4a0-cf42d2db2217.png)

MPC Video Decoder: (also tried D3D11cb and NVDEC but no changes)
![image](https://user-images.githubusercontent.com/5902578/183247553-23293302-79c2-4519-a4c2-0461dc4ec1b9.png)

MPC Audio Decoder:
![image](https://user-images.githubusercontent.com/5902578/183247576-ab7bdcda-71f8-42b1-8170-2e4f0dbe6ec4.png)

Other filters are using default settings.

**Comment by Aleksoid1978** [comment]
Try select another audio renderer, system default.

**Comment by Aleksoid1978** [comment]
Try without VBlank.

**Comment by daddy-cool** [comment]
Other audio render -> no change

Disabling VBlank -> MPC frametimes are stable and present only shows 0, but now I can't get smooth playback @120Hz anymore, similar to as if I had bad frametimes in MPC before with VBlank enabled

**Comment by Aleksoid1978** [comment]
Close ticket until the developers get the appropriate hardware.

**Comment by clsid2** [comment]
120Hz means a frame interval of just 8.333 ms, and each video frame repeated 5 times. What is the current behavior when a frame takes longer to present than those 8ms? I assume skip a frame. But that next frame could be a repeat or a "new" input frame. If it is a new one, does it drop it completely (including repeats), or does it reduce the amount of repeats of the new frame, so show 4 times instead of 5. The latter would be the correct way.

**Comment by daddy-cool** [comment]
I can't see any frames taking longer than "8ms" to present even during problematic frametimes like this:
![image](https://user-images.githubusercontent.com/5902578/183248558-1f28b5a6-01b0-4fa3-a836-4463a7323dbb.png)
It might take longer than 8.33 on the spikes but MPC VR might still show 8 when below 8.5? not sure

Present just fluctuates between 0 and 8 rapidly in the screenshot above and if I pause/resume a few times I can get it near perfectly stable (present will fluctuate between 1 and 2 for example)

MPC VR doesn't show any dropped or skipped frames either way. I'm not seeing any "black" frames or similar so I assume I see frame repeats instead of dropped frames but not sure.

**Comment by clsid2** [comment]
Have you tried with audio bitstreaming disabled?

**Comment by daddy-cool** [comment]
Yes, no change.

**Comment by Aleksoid1978** [comment]
In this situation, you can only help by sponsoring developers on such a TV with 120Hz )
