### ISSUE TITLE
32bit dll won't register (0.6.2.1952_git2022.08.18-30ada65)

### ISSUE THREAD

**Issue by radpopl** [Aleksoid1978/VideoRenderer#61]
32bit dll won't register (MpcVideoRenderer-0.6.2.1952_git2022.08.18-30ada65)
Old version MpcVideoRenderer-0.6.1.1931 working ok.

![image](https://user-images.githubusercontent.com/11005341/186659649-3acaf9d9-b48c-4bd2-bf41-d31cd7118745.png)

![image](https://user-images.githubusercontent.com/11005341/186659711-2f7e9c94-1557-4732-a339-a63c927f79d2.png)

**Comment by clsid2** [comment]
You are using the wrong path.

Use the supplied .cmd file to register it.

**Comment by clsid2** [comment]
We can't read the Polish error message.

**Comment by radpopl** [comment]
Unable to load the dll module.
Make sure that the binary is stored in the specified path or debug it to see if there are problems with the binary or dependent DLLs.
The specified module could not be found.

**Comment by radpopl** [comment]
> Try putting it in the SysWoW64 folder instead.

Working! Thanks.
