### ISSUE TITLE
Selected video renderer has failed to load

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#62]
Mpc hc latest 1.9.23 x64
Mpcvr latest 0.6.3.1956

The selected video renderer has failed to load. Player will fallback to basic video renderer. Subtitle performance will be affected. Do you want to switch to different video renderer? (EVR-CP/VMR9).

The message was something like that.

Then I closed the player and opened the video again. After that I can not reproduce the same. Everything is fine.

It happened only once. I have never seen this before.

**Comment by v0lt** [comment]
> It happened only once. I have never seen this before.

I don't see a problem here.
For proper operation, MPC VR must be registered in the system.
The post you mentioned was written by MPC-HC. There is no MPC-HC support here.

**Comment by bibsp** [comment]
MPC-VR was already registered. Played many videos before that.
I opened a youtube link and got that error. When the player offered to switch renderer then I clicked on cancel.
Then closed the player. Did nothing. Just opened the same link again. It was fine then.

Anyway leave it for now. It just happened once.
