### ISSUE TITLE
For soft solution

### ISSUE THREAD

**Issue by mzyhs** [Aleksoid1978/VideoRenderer#65]
I chose soft solution in MPC-HC, how do I set HDR for the best experience (my monitor does not support HDR and only has 8 bit), and are there any other settings that would improve my viewing experience? (The three algorithms have already been mentioned as the highest)

**Comment by mzyhs** [comment]
the MPC-HC and MPCVR are the latest.

**Comment by clsid2** [comment]
There are no settings to improve HDR quality.

**Comment by mzyhs** [comment]
![mpc设置](https://user-images.githubusercontent.com/89095610/191137664-f4222dc4-230a-4730-b20a-d8d331292107.png)
Thank you for your answer, is my settings right?

**Comment by mzyhs** [comment]
I chose a soft solution (not using hard solution), my display is 3200 × 2000, 90Hz, 8 -bit
