### ISSUE TITLE
Display AR won't change after frame size change

### ISSUE THREAD

**Issue by chainikdn** [Aleksoid1978/VideoRenderer#66]
Using ver. 0.6.3.1956 in MPC-HC, Avisynth Filter + SVP (but you can easily reproduce with the simple AVS resize script).
When changing frame size on-the-fly (in a Avisynth script) the numbers in OSD (the "scaling" line) change correctly, but the actual image aspect ratio doesn't change until manually resize the player window.

**Comment by Aleksoid1978** [comment]
Upload sample script.

**Comment by chainikdn** [comment]
`AvsFilterSource().Crop(0,200,0,200)`

**Comment by Aleksoid1978** [comment]
Avisynth Filter - what's is this ?
Can you try without SVP)i don't use SVP and can't check with it).

**Comment by chainikdn** [comment]
https://github.com/CrendKing/avisynth_filter
https://drive.google.com/file/d/1Y37sZ0Avi50fwUjWC3Q3tEicWm7e44J5/view?usp=sharing

**Comment by Aleksoid1978** [comment]
Avisynth бывает 64 разрядный ?

> `AvsFilterSource().Crop(0,200,0,200)`

Script with this text is not loaded, show error in player.

**Comment by chainikdn** [comment]
> Avisynth бывает 64 разрядный ?

o_O конечно 
https://github.com/AviSynth/AviSynthPlus

**Comment by Aleksoid1978** [comment]
Нет бы сразу по русски писать :)

**Comment by chainikdn** [comment]
https://drive.google.com/file/d/13JDY9czzwwVpVr8cvxeyUFzad6UM7pFY/view?usp=sharing

**Comment by Aleksoid1978** [comment]
Вот можно попробовать еще фильтр - https://github.com/v0lt/ScriptSourceFilter
Так же проверить с другими видео-рендерерами - madVR/EVR/EVR-CP.
Я думаю что фильтр "не корректно" обрабатывает изменение размера, он должен произвести кое-какие действия чтобы сообщить об этом следующему фильтру.

**Comment by chainikdn** [comment]
и evr и madvr корректно переживают такое изменение размера кадра "на лету", что с ffdshow, что с "Avisynth filter"

**Comment by Aleksoid1978** [comment]
Ок, гляну, но мне нужен рабочий скрипт.
Можно так сделать - к примеру длительность секунд 10 , любое разрешение но на пятой секунде разрешение меняется ?

**Comment by chainikdn** [comment]
скрипт - любой тривиальный меняющий размер кадра, что там может быть неправильно в "Crop(0,200,0,200)" - я не знаю. 
"show error in player" - какая ошибка?

**Comment by Aleksoid1978** [comment]
Короче я хз, установил(зарегал) avisynth_filter_64.ax
Но при открыти AVS скриптов он не цепляется. Ну ок - добавил во внешние фильтры, предпочесть, открываю скрипт - нифига, не цепляется.
Проверяю в MPC-BE х64, если что.

А на скрипт с содержимым
[code]
AvsFilterSource().Crop(0,200,0,200)
[/code]
ругается сам AviSynth, выдавая в плеере видео с текстом ошибки.
![error](https://user-images.githubusercontent.com/11625603/193027068-fac5b60e-6812-4204-9b04-db29ea413b52.png)

**Comment by Aleksoid1978** [comment]
Все разобрался. Я то думал он скрипты открывает :)
Все работает, вот скрин - изображение такое сразу же после открытия видео 1920х1080.
![work](https://user-images.githubusercontent.com/11625603/193028771-20b52aed-36f1-46cb-93e8-a166d2a0dfec.png)

**Comment by chainikdn** [comment]
я понимаю что "после открытия" - отлично
речь про "на лету" - открыть, а затем поменять скрипт в процессе воспроизведения

**Comment by Aleksoid1978** [comment]
Если во время проигрывания изменить и перегрузить скрипт - то да, подтверждаю. Гляну.

**Comment by Aleksoid1978** [comment]
Исправлено.

**Comment by chainikdn** [comment]
Спасибо. А с ffdshow это поможет? (выше было видео с чуть другим проявлением этой же проблемы с ffdshow raw filter)
Там даже цифры размера кадра в статистике не меняются.
И можно зарелизить? :)

**Comment by chainikdn** [comment]
Теперь падает когда кадр увеличивается. Самое простое если запустить с Crop(0,200,0,200), а в процессе поменять на (0,0,0,0).

**Comment by Aleksoid1978** [comment]
На каком видео проверял - в смысле какое начальное разрешение ?
Я проверил на 1920х1080 - все отлично, ширина уменьшилась.

**Comment by chainikdn** [comment]
ну лично у меня с 1920*1080 его рубит если по 64 отрезать
Crop(64,0,-64,0)
если целое -> отрезать, то экран идет полосами
если отрезанное -> целое, то падет
![mpc](https://user-images.githubusercontent.com/9394230/193400489-5b352f19-606e-4700-b341-58410c97fed5.png)

**Comment by Aleksoid1978** [comment]
Покажи настройки VR.

**Comment by chainikdn** [comment]
![mpc-settings](https://user-images.githubusercontent.com/9394230/193443228-67087c63-ccde-4d16-90f9-c9cfdb396aa6.png)

**Comment by Aleksoid1978** [comment]
Вот проверяй.
[MpcVideoRenderer-0.6.4.1960_git2022.09.30-a1616a9.zip](https://github.com/Aleksoid1978/VideoRenderer/files/9693917/MpcVideoRenderer-0.6.4.1960_git2022.09.30-a1616a9.zip)

**Comment by chainikdn** [comment]
Вот так хорошо.
Еще бы с ffdshow починить, и было бы еще более хорошо :)
Там даже в выходном пине из ffdshow размер кадра не меняется. При том что с EVR (и c madVR) - меняется.

**Comment by Aleksoid1978** [comment]
Вот честно - не хочу и не буду ставить ffdshow. Все - вопрос закрыт.
