### ISSUE TITLE
Access settings?

### ISSUE THREAD

**Issue by Kein** [Aleksoid1978/VideoRenderer#67]
May be I'm slow in the head, but I cant seems to find a way to configure renderer. Using MPC-HC 1.9.23

**Comment by Aleksoid1978** [comment]
In MPC-BE you can access VR options in player Options -> Video -> select MPC VR -> Properties.
In MPC-HC - only when playback via Filters menu.

Or via cmd -> "rundll32.exe <full_path_to_file>\MpcVideoRenderer64.ax,OpenConfiguration"

**Comment by Kein** [comment]
MPC-HC from [clsid2](https://github.com/clsid2) added an ability to configure external renderers:
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/623756/ee9d8e60-d36c-4ce0-abd0-c7228f2aa97a)
