### ISSUE TITLE
Motion interpolation

### ISSUE THREAD

**Issue by borowsky2** [Aleksoid1978/VideoRenderer#69]
Hello
Would you be able to add motion interpolation into this video renderer? In similar fashion its done within DmitriRenderer (http://www.dmitrirender.ru/)
I really wish for something like this to be opensource. 
For non-accelerated generic implementation you could lookup at ffmpeg - minterpolation filter and buttersmooth project.
With DmitriRenderer I was able to get best smoothness (way ahead of SVP and amd fluidmotion) so far 2560x1440@120fps and 4k at 60fps (interpolated from 23-30fps) when using just old RX480
Im willing to pay/donate for your time if you can make this done and just lacking time.

**Comment by Aleksoid1978** [comment]
Not planned and not interest.
But - patch are welcome :)

**Comment by catshitz** [comment]
> 您好， 您可以在此视频渲染器中添加运动插值吗？[它以类似的方式在 DmitriRenderer ( http://www.dmitrirender.ru/](http://www.dmitrirender.ru/) )中完成， 我真的希望像这样的东西是开源的。 对于非加速通用实现，您可以查看 ffmpeg - 最小插值过滤器和 buttersmooth 项目。 使用 DmitriRenderer，我能够获得最好的平滑度（远远领先于 SVP 和 amd fluidmotion） 2560x1440@120fps 和 4k 60fps（从 23-30fps 插值）当只使用旧的 RX480 我愿意为你的时间付出/捐赠，如果 你可以做到这一点，只是缺乏时间。

Same here, wonder if it works with svp, therefore, DmitriRender is always the best solution if there's a choice for both DR and NV SuperRes.
