### ISSUE TITLE
A green line appears at the bottom when inputting with D3D11 Decoder

### ISSUE THREAD

**Issue by 2ndR** [Aleksoid1978/VideoRenderer#7]
Occurs in combination with D3D11 Decoder and D3D11 Shader Video Processor

LAV Video Decoder Hardware Decoder to use None
![a](https://user-images.githubusercontent.com/60872236/78120956-ba934300-7445-11ea-88f4-74b2c18a5b9e.png)

LAV Video Decoder Hardware Decoder to use D3D11
![b](https://user-images.githubusercontent.com/60872236/78120982-c3841480-7445-11ea-949f-a1419359e5ca.png)

MPC-BE 1.5.5.5148
MPCVideoRenderer v0.4.3.1215
LAVFilters-0.74.1-34
Radeon Pro Software Enterprise 20.Q1.1
Windows10 1909

Source
jellyfish-90-mbps-hd-hevc-10bit

**Comment by Aleksoid1978** [comment]
Where is "green line at the bottom" ? I don't see on pictures.

**Comment by v0lt** [comment]
There is no green line in the screenshots. No one could confirm. I close it.
