### ISSUE TITLE
关于笔记本电脑Range默认16-235，无法更改为0-255的问题

### ISSUE THREAD

**Issue by RBHakureiReimu** [Aleksoid1978/VideoRenderer#70]
本人有两台笔记本，两台设备的显卡分别为nVidia的2070MQ和英特尔的核显，当我在这两台设备上使用mpcvr的时候，无论我使用哪台设备，MPCHC或MPCBE，LAV或者MPCBE内置解码器，包括我在显卡控制面板开启了0-255的前提下，mpcvr都只能输出16-235，请问我该如何解决这个问题？
![屏幕截图(1)](https://user-images.githubusercontent.com/45761551/203238707-324f445c-6ee7-487f-b151-2e2803e461c5.png)

**Comment by Masaiki** [comment]
槽点有点多了
YUV 编码的视频多数都是 limited range 的，这里的 range 指的是输入视频的 range 和你指定显卡怎么输出无关
而显卡丢给显示器的数据流是 RGB 编码的，RGB 一般都是 full range 的，你修改的是这里
另外在 GitHub 上提问，还是尽量用英文

**Comment by RBHakureiReimu** [comment]
英文这个我主要是怕机翻有歧义，但是色彩对比madvr，mpcvr的黑很明显是灰色的啊，madvr就是纯黑

**Comment by Masaiki** [comment]
> 英文这个我主要是怕机翻有歧义，但是色彩对比madvr，mpcvr的黑很明显是灰色的啊，madvr就是纯黑

理由也挺离谱的……

你可以试试取消 DXVA2 and D3D11 video processor 里的所有勾选

**Comment by RBHakureiReimu** [comment]
全取消了已经。。。

**Comment by Aleksoid1978** [comment]
English or Russian.

**Comment by RBHakureiReimu** [comment]
Sorry for my poor English and Russian, I'll use machine translation if it's okay.@Aleksoid1978

**Comment by RBHakureiReimu** [comment]
But under the premise of the same video, mpcvr is compared with madvr, and the black of mpcvr is obviously grayer

**Comment by Aleksoid1978** [comment]
1 - Try uncheck all options in Use for: - currently you use D3D11 Video Processor, it use you current drivers settings.
2 - In you video driver Intel/Nvidia set 0 - 255 full range.

**Comment by RBHakureiReimu** [comment]
Thank you very much for your suggestion, but the author's suggestion did not solve my problem, and the control panel of my notebook graphics card can only change the video setting to 0-255, but not the monitor setting to 0-255

**Comment by RBHakureiReimu** [comment]
Thank you for your help

**Comment by shikkoku** [comment]
Is this not because your video source is originally 16-235?

难道这个不是因为你的视频源本来就是16-235吗。你放个png图片进去播放器试试。
