### ISSUE TITLE
HDR Flip Non Video Area is grey

### ISSUE THREAD

**Issue by vdrfan** [Aleksoid1978/VideoRenderer#71]
with Flip and HDR enabled - non video Area is not 100 Percent Black.
you only can see the difference in attached image with OLED and HDR enabled.

when you Pick Color (at Top/Bottom of Image) then you will see RGB (2,4,1) instead of (0,0,0).
This does not happen when using swap discard.

![hdr-grey](https://user-images.githubusercontent.com/13224045/203829268-efdddba9-853e-4f19-bc33-3f0d7622bd40.jpg)

**Comment by Aleksoid1978** [comment]
I don't know, maybe driver's issue.

**Comment by vdrfan** [comment]
you are right - it is a driver issue, with newer AMD driver there is no grey-problem with MPCVR.

other qeuestion - maybe you know that problem.
Setup: Radeon Ryzen 3400G - with Vega Graphics.
with most AMD drivers i have problems with some 720p h264 Videos (50p video stuttering and showing only 15-30 frames/sec).
the stuttering is with EVR, MAD, and MPCVR - and it is only with Hardware Decoding.
some Drivers work correct with these 720p Videos - but these drivers have the grey bug ...

thanks for your work, regards, onur

**Comment by clsid2** [comment]
Stutter issue sounds like same as this one:
https://github.com/Nevcairiel/LAVFilters/issues/496

I suggest reporting it to AMD.
