### ISSUE TITLE
Is it correct?

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#73]
https://user-images.githubusercontent.com/98865389/208228819-bc580e8d-9633-4dfb-94c8-19d74b50b2d8.mp4

Video scaled down from 1920x800->1366x569
Why is it using upscaling?
Or am I missing something?

Same result with Direct3D 11 checked.

**Comment by Aleksoid1978** [comment]
Maybe you need to be a little more careful?
See the option - **Use the "Upscaling" method to reducing the frame to 50%** :)
