### ISSUE TITLE
Green screen at empty spaces when play HDR videos

### ISSUE THREAD

**Issue by poonnawit** [Aleksoid1978/VideoRenderer#74]
I'm a MPC-HC user. It happens only when play every HDR videos.
If I play 16:9 video and toggle to Fullscreen, there still no green because my monitor has 16:9 (1920x1080) same as the video.
But the green screen will appear at the empty space of the player (It should be black) when the video not a 16:9.
Also, in window mode when try to resize window that video does not fill the player space.

![Screenshot (7)](https://user-images.githubusercontent.com/29587383/210097112-79c8e92a-9ce8-4a98-9e29-ade44fcd7c02.png)
Default size after open video

![Screenshot (4)](https://user-images.githubusercontent.com/29587383/210097099-059b1e01-b188-4c82-ae2f-70d9e5c3de23.png)
When resize window width

![Screenshot (6)](https://user-images.githubusercontent.com/29587383/210097086-3206c523-47cc-4022-84af-3b6322399e8c.png)
non-16:9 Video with full screen

Video still play smoothly and no problem with video.
But the screen has some over-brightness sometimes and become normal brightness when toggle full screen a few times. (Only in HDR videos)

Windows 10 22H2
CPU: Intel Core i5-4570
GPU: AMD Radeon RX 6600 XT (22.11.2)
Monitor: BenQ EX2510S (1920x1080) (HDR10 Support)

**Comment by clsid2** [comment]
Press Ctrl+J to show the renderer debug overlay. Make a screenshot of that as well.

Test if changing the hardware decoder setting in LAV Video Decoder has any effect on this problem.

**Comment by Aleksoid1978** [comment]
Test in MPC-BE.
Test without HW decoding.
Show screen with statistics(Ctrl+J).

**Comment by poonnawit** [comment]
I think I have found the answer.
When try to uncheck "Use for resizing" the green screen have disappeared.
Maybe scaling is the problem. I guess.
![Screenshot (13)](https://user-images.githubusercontent.com/29587383/210129933-4bdbb269-9ea1-4723-a8c5-5d31c8ecb7fa.png)

![Screenshot (14)](https://user-images.githubusercontent.com/29587383/210129939-5149b646-5c91-4aa7-8b75-addc51eaeb8f.png)

![Screenshot (15)](https://user-images.githubusercontent.com/29587383/210129940-3a641873-3197-4f27-a265-1133d113cb73.png)

![Screenshot (16)](https://user-images.githubusercontent.com/29587383/210129942-bc259b40-3484-4850-a4ca-abe70d55b1ae.png)

![Screenshot (17)](https://user-images.githubusercontent.com/29587383/210129946-21ec08a5-e3b7-405f-be76-76d8a5055bb1.png)

![Screenshot (18)](https://user-images.githubusercontent.com/29587383/210129948-88ce118b-aa0f-4439-a915-21f44b324b66.png)

**Comment by Aleksoid1978** [comment]
Look's like driver issue.

**Comment by poonnawit** [comment]
I tried switch to use madVR and there is no green screen. But when I resize the window. It's look like a bit more delay than MPC VR. Windows only auto switch to HDR mode when full screen. Maybe this try has some clue.
![Screenshot (19)](https://user-images.githubusercontent.com/29587383/210148534-cfcbc155-e0ad-4147-a135-0100435ef86d.png)

**Comment by Aleksoid1978** [comment]
madVR use Direct3D9 internal and Direct3D11 only for output.
As i said - it's some driver issue.

**Comment by Aleksoid1978** [comment]
Check test build.
But I warn you - sometimes it may not produce a picture on HDR at all, in which case we simply reopen the file (maybe even several times).
[MpcVideoRenderer-0.6.4.1966_git2023.01.04-e90179d.zip](https://github.com/Aleksoid1978/VideoRenderer/files/10370491/MpcVideoRenderer-0.6.4.1966_git2023.01.04-e90179d.zip)

**Comment by poonnawit** [comment]
No changes.
And still produce pictures as well. No need to reopen.
I have reported this issue to AMD. If next drivers have arrived, I will update the issue on there. Thank you.

![Screenshot (20)](https://user-images.githubusercontent.com/29587383/211302773-4d842ac7-8ffd-44c1-be08-4f711d1e4e30.png)

**Comment by poonnawit** [comment]
Update: The issue has been fixed on Adrenalin 23.2.1 (WHQL) driver. No more green space.
