### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by JasioNiezdara** [Aleksoid1978/VideoRenderer#75]
Hello.
I love your renderer. A lot of features while not being resource-intensive.

However I am missing one feature that I really like in madVR - advanced screenshot options.

With madVR, I can set it so that all screenshots are saved as 3840x2160 using the best scaling algorithm, no matter what the source resolution is.
Also, madVR performs tone-mapping for screenshots while watching in HDR.
And I can also choose whether I want subtitles to be visible in the screenshot, which is sometimes useful.

Any chance of adding features like this in the future?

Keep up the good work!

**Comment by Aleksoid1978** [comment]
No - the renderer gives screenshots according to the frame size, if necessary it applies HDR -> SDR conversion.

Regarding the display of subtitles - the player does this, for example MPC-BE has such an option.

**Comment by JasioNiezdara** [comment]
What do you mean by "if necessary it applies HDR -> SDR conversion"?

I was watching an HDR movie yesterday and I captured a couple of screenshots, but they are washed out (no tone-mapping).

**Comment by Aleksoid1978** [comment]
Yes - it's situation confirm.
I'll see what can be done and if it can be fixed.

**Comment by v0lt** [comment]
Disable the "Passthrough to HDR" option and take a screenshot.

**Comment by JasioNiezdara** [comment]
> You can take a screenshot of the frame in its original size (Alt+I or F5) or a screenshot of the frame as it is displayed (Shift+F5) (with subtitles, statistics and OSD). This can be done in the MPC-BE player.

Interesting. I have been using MPC-HC for years, I did not know MPC-BE even existed. ;)

I am checking it out. The screenshot option you mentioned seems to work nicely.
But I am having a different issue at the moment - I cannot get ReClock to work properly with the MPC Video Renderer in MPC-BE. ReClock shows "no video stream detected".
It does work with EVR CP, even though it says the video stream is interlaced.

I need ReClock for perfect 24p playback. I have no issues in MPC-HC, no matter which renderer I use.
