### ISSUE TITLE
The settings for changing the upscaling algorithm have no effect.

### ISSUE THREAD

**Issue by sn260591** [Aleksoid1978/VideoRenderer#78]
Cheked with MPC-BE 1.6.5.3 x64 and MPC-HC x64 2.0.0.0.

**Comment by Aleksoid1978** [comment]
Show a screenshot of the settings in both cases.
Also - during playback, press Ctrl + J and take a screenshot of the player window, the same in both cases.

**Comment by sn260591** [comment]
![1](https://user-images.githubusercontent.com/10724977/218163672-d090c97d-773c-44aa-b11b-e52444ee940c.png)
![2](https://user-images.githubusercontent.com/10724977/218163674-9022c888-44c1-4632-8648-fa248036317b.png)
![0](https://user-images.githubusercontent.com/10724977/218164611-171a00e8-410b-4dc4-bd15-6fc33aef8709.png)

**Comment by clsid2** [comment]
The shaders are not used because you are using the video processor for scaling.

**Comment by sn260591** [comment]
Indeed, did not pay due attention to this option. Disabling it solves the problem.
