### ISSUE TITLE
RTX Video Super Resolution Support

### ISSUE THREAD

**Issue by Hackjjang** [Aleksoid1978/VideoRenderer#79]
https://github.com/emoose/VideoRenderer/releases/tag/rtx-1.0

There's an RTX Super Resolution patch out for GeForce RTX users, and I'd love to see that come out here as well. Intel did the same thing with Google Chrome, so I'd love to see a patch for Intel Arc users as well.

I'm an AMD Radeon user, so I don't expect immediate support, but...
Nvidia GeForce and Intel Arc users can use it, so I hope it will be applied, and I hope AMD Radeon will support it at some point.

**Comment by Aleksoid1978** [comment]
https://github.com/Aleksoid1978/VideoRenderer/issues/77
