### ISSUE TITLE
In the OSD, the Matrix Coef and Color Primaries fields are swapped. It should be otherwise.

### ISSUE THREAD

**Issue by radpopl** [Aleksoid1978/VideoRenderer#80]
In the OSD, the Matrix Coef and Color Primaries fields values are swapped. It should be otherwise.

![image](https://user-images.githubusercontent.com/11005341/224851824-b490785d-a73d-4df7-8f48-79cdbde503ba.png)

**Comment by v0lt** [comment]
You are wrong.
MediaInfo has nothing to do with it at all.
MPC Video Renderer works with the DXVA2_ExtendedFormat structure it receives from the previous filter.

[DXVA2_ExtendedFormat structure](https://learn.microsoft.com/en-us/windows/win32/api/dxva2api/ns-dxva2api-dxva2_extendedformat)
--[DXVA2_VideoTransferMatrix enumeration](https://learn.microsoft.com/en-us/windows/win32/api/dxva2api/ne-dxva2api-dxva2_videotransfermatrix)
----DXVA2_VideoTransferMatrix_BT709 -> "BT.709"
--[DXVA2_VideoPrimaries enumeration](https://learn.microsoft.com/en-us/windows/win32/api/dxva2api/ne-dxva2api-dxva2_videoprimaries)
----DXVA2_VideoPrimaries_BT470_2_SysBG -> "BT.470-4 System B,G"

**Comment by radpopl** [comment]
So the Matrix field value will match the Color Primaries field value from MediaInfo and DXVA2_VideoTransferMatrix?
And the value of the Primaries field will correspond to the Matrix coefficients field from MediaInfo and DXVA2_VideoPrimaries?

**Comment by v0lt** [comment]
No. Transfermatrix and Primaries are different things.
If you want to figure out why Microsoft called some things differently than Mediainfo, then you can see the standards that are mentioned in the MS documentation.

Here is a good example
> **Dxva2_videotransfermatrix_bt601**
> Value: 2
> ITU-R BT.601 Transfer Matrix. ALSO USED for SMPTE 170 and ITU-R BT.470-2 System b, g.

The matrix is one, but mentioned in different standards.

**Comment by v0lt** [comment]
> So to sum up:

To summarize, you need to compare several test files that differ in one parameter.
I will not do this, because. player and renderer works correctly.
