### ISSUE TITLE
Select render device

### ISSUE THREAD

**Issue by borowsky2** [Aleksoid1978/VideoRenderer#83]
Would it be possible to enforce using selected render device?
Im having two GPUs connected with two different displays
One of GPU have dedicated fluid motion asci and some nice hardware accelerated post-processing features while second have none.
With your video renderer I can start video clip at first display and then move it onto second display... but as soon as next clip begins it results in blackscreen - because renderer device gets changed 
With EVR-CP I can enforce using first video adapter and everything works well all the time.
![select renderer](https://user-images.githubusercontent.com/118736091/228671832-8c3ff279-5c1c-4875-a3cc-222a728f5747.PNG)

**Comment by Aleksoid1978** [comment]
No - there will be no "select device".
The renderer itself chooses the device through which the output goes (which is connected to your monitor / screen).

**Comment by clsid2** [comment]
Windows 10/11 settings > Display > Advanced

There you can add applications and specify which GPU they should use by default. That might work.

**Comment by borowsky2** [comment]
@clsid2 
Thanks for tip
Unfortunately it doesn't change anything for this video renderer.
After changing display (when starting next video file) graph. adapter still switches onto integrated gpu 
![gpu2](https://user-images.githubusercontent.com/118736091/229640494-806ef746-f355-44b3-8075-0d0f982198a6.PNG)

**Comment by borowsky2** [comment]
Actually inside BlueskyFRC filter settings panel there is check button - Enable Zero-copy Mode
After unchecking it... it works!
Its still IGPU as graphics adapter but now ... it copy-back processed frames onto igpu (I guess)
Which is different approach from EVR-CP solution but still works with little overhead costs
