### ISSUE TITLE
Screenshots taken during hdr playback are not tonemapped

### ISSUE THREAD

**Issue by HailAlistair** [Aleksoid1978/VideoRenderer#84]
Summary: hey, I would love to use this rendered instead of MadVR, but HDR screenshots are broken (they are not tonemapped).

Screenshot taken during playback in HDR (thoroughness to the screen) have very washed-out colors. 
The screenshots should be tonemapped, without requiring the user to disable the HDR passtrough. (some people like to grab screenshots while watching the video. Having to fiddle with settings every time is unreasonable.)

Thank you for your consideration.

**Comment by Aleksoid1978** [comment]
It's limitation.

**Comment by HailAlistair** [comment]
Thank you for the consideration.
May I ask why this is not planned to be fixed?

Just by chance, I have just encountered another user complaining about this exact issue, right now on reddit/htpc. So I guess that It can't be such an obscure complaint. 
https://www.reddit.com/r/htpc/comments/12dfkpo/screengrabs_using_mpcbe_from_4k_hdr_video/

**Comment by Nick-Biedlingmaier** [comment]
Seems like the devs are too busy to listen to you or respond, but they can easily click a button to ignore you. Pretty lame if you ask me.
