### ISSUE TITLE
Black screen on NV12 with higher texture format

### ISSUE THREAD

**Issue by Fawaytish** [Aleksoid1978/VideoRenderer#85]
I have problem when using Direct3D 11 with texture format set to 16-bit floating point or 10-bit integer. The screen is blank, audio and subtitles work. It happens only on NV12 format, does not happen on P010. When I uncheck NV12 or turn off Direct3D 11, it works normally.

GPU: AMD Radeon RX 6600

**Comment by Aleksoid1978** [comment]
Driver's issue.
Set Auto for texture format. Renderer will be select 8bit for nv12 or 10bit for p010.
