### ISSUE TITLE
I see a white line at the bottom of the screen when using RTX Video Super Resolution 

### ISSUE THREAD

**Issue by Noz0mizore** [Aleksoid1978/VideoRenderer#88]
Same problem when using the renderer for MPC-BE 1.6.7, PodPlayer 
This is an issue with MPC Video Renderer 0.6.7.2013 x64, but the same bug has been observed in previous versions as well. 

If you see a white line in the lower part of the video, it seems to be related to the resolution of the video, not the area where the video is output.

In the example, the resolution is FHD, but the aspect ratio is 1.85:1, which creates a letterbox, and the white line is visible in the area below the letterbox. 

2.35:1
![20230518_195620](https://github.com/Aleksoid1978/VideoRenderer/assets/132704033/cc598305-b51a-425b-965f-33187a604e03)
1.85:1
![20230518_195317](https://github.com/Aleksoid1978/VideoRenderer/assets/132704033/b3e5a7e7-8603-4c9e-afd6-15d12a2fec62)

**Comment by Klaus1189** [comment]
Testfile?
What Decoder?
Which GPU?

**Comment by Aleksoid1978** [comment]
If it's happened only when "RTX Video Super Resolution" enabled - bug in driver. Video renderer only can enable/disable this features.
