### ISSUE TITLE
Fails to load shaders, but it works with other video renderers

### ISSUE THREAD

**Issue by malvinael07** [Aleksoid1978/VideoRenderer#89]
![2023-06-10_03-23](https://github.com/Aleksoid1978/VideoRenderer/assets/57519461/b659c559-9de4-4b94-84aa-d1773002f496)
Can't get my shaders to work with the latest official Renderer release. They work with MadVR and EVR-CP, they never load with MPC-VR. 

MPC-BE x64 1.6.7
Windows 10
MPC-VR 0.6.7.2013

Shader I'm trying to use: https://krakenfiles.com/view/Tn2LKQL93T/file.html
Virus Total: https://www.virustotal.com/gui/file/b88ab277a69fe8ff057eba86b23736609cbb91c9a16e78964a8206d33504e23f

**Comment by malvinael07** [comment]
Seems to be working after a setting reset. Closing.

**Comment by v0lt** [comment]
For DX9 mode you should use ps_2_0 or ps_3_0 shaders.
Example: https://github.com/Aleksoid1978/MPC-BE/blob/master/distrib/Shaders/Contour.hlsl

For DX11 mode you should use ps_4_0 shaders.
Example: https://github.com/Aleksoid1978/MPC-BE/blob/master/distrib/Shaders11/Contour.hlsl

You can switch to DX9 mode or rewrite the shader for DX11.
