### ISSUE TITLE
GetCurrentImage returns image in SAR

### ISSUE THREAD

**Issue by adipose** [Aleksoid1978/VideoRenderer#9]
In contrast to madvr, GetCurrentImage returns image in SAR.  As a result code in GetDIB() of mpc-be and mpc-hc returns an image in the wrong aspect ratio.

This is not "wrong" or "right," I suppose.  But since mpcvr seems to emulate madvr api somewhat, result is ~identical code with different results.

returns image in SAR:
---
```cpp
STDMETHODIMP CMPCVRAllocatorPresenter::GetDIB(BYTE* lpDib, DWORD* size)
{
    HRESULT hr = E_NOTIMPL;
    if (CComQIPtr<IBasicVideo> pBV = m_pMPCVR) {
        hr = pBV->GetCurrentImage((long*)size, (long*)lpDib);
    }
    return hr;
}
```
returns image in DAR
---
```cpp
STDMETHODIMP CmadVRAllocatorPresenter::GetDIB(BYTE* lpDib, DWORD* size)
{
    HRESULT hr = E_NOTIMPL;
    if (CComQIPtr<IBasicVideo> pBV = m_pMVR) {
        hr = pBV->GetCurrentImage((long*)size, (long*)lpDib);
    }
    return hr;
}
```

**Comment by Aleksoid1978** [comment]
Fixed - now GetCurrentImage return image using DAR.

**Comment by v0lt** [comment]
It is not right. IBasicVideo::GetCurrentImage should return the original image without changing the frame size.

**Comment by adipose** [comment]
@v0lt , thanks for explaining.  So madvr is wrong?

Also, if this is known and deliberate, why does mpc-be produce SAR screenshots from MPCVR, but contains patches to use DAR for other video renderers?

In mpc-hc we can adjust after GetCurrentImage.  But, since madvr did it this way, I thought perhaps MPCVR should as well.  But to be safe, my patch hides the functionality in GetBin rather than overriding GetCurrentImage.

**Comment by v0lt** [comment]
The renderer is not required to make IBasicVideo::GetCurrentImage frame size adjustments, but some renderers do this.

As far as I remember, VMR-7/9 does not do frame size correction when calling IBasicVideo::GetCurrentImage. Resizing the frame can be done in the player. 

I need the ability to get the original frame. I used IBasicVideo::GetCurrentImage for this, but I can’t after the last changes.
_______________
A few specifications:
[IBasicVideo::GetCurrentImage](https://docs.microsoft.com/en-us/windows/win32/api/control/nf-control-ibasicvideo-getcurrentimage)

> The GetCurrentImage method retrieves the current image **waiting** at the renderer.

It used the system VMR-7 and VMR-9.

And in contrast
[IMFVideoDisplayControl::GetCurrentImage](https://docs.microsoft.com/ru-ru/windows/win32/api/evr/nf-evr-imfvideodisplaycontrol-getcurrentimage)

> Gets a copy of the current image being **displayed** by the video renderer.

It uses the system EVR and produces the displayed frame (the size as it is visible on the display).

**Comment by adipose** [comment]
This makes sense.  If you look at my PR, I did not break GetCurrentImage() (I don't think!).

https://github.com/Aleksoid1978/VideoRenderer/pull/10

I added a GetBin option to pull the data.

Maybe another solution would be an option that could be turned on and off.  It could be activated right before calling GetCurrentImage and disabled after.

**Comment by adipose** [comment]
@Aleksoid1978, so is the DAR fix staying as is? I don't want to get in the middle, but I am unsure after @v0lt has said it is wrong.

**Comment by Aleksoid1978** [comment]
Yes - staying as is.
