### ISSUE TITLE
HDR tone mapping

### ISSUE THREAD

**Issue by bibsp** [Aleksoid1978/VideoRenderer#90]
VLC vs MPCVR
![Screenshot (45)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/c65c39af-fcc1-4bf7-9922-83672204b252)
![Screenshot (49)](https://github.com/Aleksoid1978/VideoRenderer/assets/98865389/b42793c1-c279-47e5-ad21-7696383d75e5)
 Video: https://www.youtube.com/watch?v=1La4QzGeaaQ [1080p vp9 2 + opus downloaded by yt-dlp].

**Comment by v0lt** [comment]
Write a reason or your issue will be closed.

**Comment by bibsp** [comment]
Clouds are slightly over exposed in mpcvr.

I personally don't use madvr. Just to double check I tried madvr. Madvr is also similar to vlc.
