### ISSUE TITLE
Option to make tonemapped HDR to SDR brighter

### ISSUE THREAD

**Issue by geextahslex** [Aleksoid1978/VideoRenderer#91]
Hi,
I like to look of the tonemapping, the colors, saturation but the picture is very "dark"
Currently I am using VLC with the "Reinhard" algorithm

VLC:
![vlc 2](https://github.com/Aleksoid1978/VideoRenderer/assets/139760266/4b75770f-5143-4ee3-8b2b-6bdf5517f14a)
MPC Video Renderer:
![MPC HC video renderer](https://github.com/Aleksoid1978/VideoRenderer/assets/139760266/27742a68-d403-4a38-82d6-d69db1f408f0)
VLC:
![vlc w](https://github.com/Aleksoid1978/VideoRenderer/assets/139760266/696a3bd3-51e5-4fec-b440-1241d816f88a)
MPC Video Renderer:
![The Witcher S03E01 GERMAN DL 2160p DV HDR WEB H265-TSCC mkv_snapshot_00 06 56 657](https://github.com/Aleksoid1978/VideoRenderer/assets/139760266/fea88b81-2e6f-442c-b445-b88be6b531f1)

Currently I'm forced to use VLC for HDR content, but it would be awesome to have everything work in MPC.

**Comment by Aleksoid1978** [comment]
Not planned.

**Comment by clsid2** [comment]
Why not investigate some alternative algorithms? You could give users a choice.

Maybe this is useful:
https://github.com/Zackin5/Filmic-Tonemapping-ReShade/blob/master/Reinhard.fx
https://imdoingitwrong.wordpress.com/2010/08/19/why-reinhard-desaturates-my-blacks-3/

**Comment by Aleksoid1978** [comment]
Patch are welcome.
I'm not interest.

**Comment by geextahslex** [comment]
I just switched to mpv, problem solved
