### ISSUE TITLE
DoVi

### ISSUE THREAD

**Issue by clsid2** [Aleksoid1978/VideoRenderer#92]
Hi guys, nice work on adding DoVi support.

Here are some good sample files:
https://www.demolandia.net/4k-video-test/dolby-vision.html
https://www.demolandia.net/downloads.html?id=8865543
https://www.demolandia.net/downloads.html?id=43567783

Been testing it a bit in the past days. Seems to be working nicely already in DX11 mode. With DX9 the colors are a bit wrong.

**Comment by Aleksoid1978** [comment]
DX9 is not ready yet.

**Comment by v0lt** [comment]
Partial support for Dolby Vision added in commit 9940f82.
MMR is not supported in DX9 mode.
