### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by tormento** [Aleksoid1978/VideoRenderer#93]
Would be possible to add Vulkan support?

**Comment by Aleksoid1978** [comment]
No - on windows it is simply not necessary, from the word "absolutely".

**Comment by v0lt** [comment]
> Would be possible to add Vulkan support?

I don't know. But you can make [a fork](https://github.com/Aleksoid1978/VideoRenderer/forks) and try it.

**Comment by tormento** [comment]
@v0lt I know Fortran, specialized in finite elements analysis. Unfortunately not of any use in this case.

;)
