### ISSUE TITLE
greenish hue in hdr

### ISSUE THREAD

**Issue by SESNut** [Aleksoid1978/VideoRenderer#98]
when playing back an hdr video the color is slightly green. Playing the same video with madvr does not have this green color and the color in madvr is identical to vlc and the built in windows media player.

![Screenshot 2023-10-22 044331](https://github.com/Aleksoid1978/VideoRenderer/assets/27609765/a88b7f27-7ee5-4067-8c4f-7b93672db1cb)
media player on the left and mpc video renderer on the right

**Comment by Aleksoid1978** [comment]
Different algorithm, that's all.

**Comment by SESNut** [comment]
youre not talking about hdr to sdr tonemapping right? Just the hdr being passed through to the display?

**Comment by Aleksoid1978** [comment]
Yes, i am talking about hdr to sdr algorithm.

**Comment by SESNut** [comment]
I am using an hdr display so the tonemapping shouldn't even matter

**Comment by Aleksoid1978** [comment]
Enable statistics in MPC-VR and make screenshot with it, then upload here.
It realy using HDR Passthrough - MPC VR nothing do with video data.

**Comment by SESNut** [comment]
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/27609765/221b2d56-90b1-4a26-b74d-4782922432a2)

**Comment by Aleksoid1978** [comment]
All is good, hdr enable.

**Comment by Aleksoid1978** [comment]
In this case, I can’t suggest anything and don’t know the reason for the difference in color. MPC VR displays data as is + HDR metadata is sent via API.
I can recommend this - in the MPC VR settings, clear all the checkboxes in the "DXVA2 and D3D11 video processor" section and check.

**Comment by SESNut** [comment]
its the P010/P016  setting that is causing the green hue

**Comment by Aleksoid1978** [comment]
Fine.
This means that either something in the video driver in the API is not implemented correctly, or something else is connected with it.

**Comment by clsid2** [comment]
Please mention your current NVIDIA driver version.

Also try a few older/newer driver versions and let us know if that makes any difference.
