### ISSUE TITLE
Dolby Vision converted to SDR even with a HDR display

### ISSUE THREAD

**Issue by zbydown** [Aleksoid1978/VideoRenderer#99]
![image](https://github.com/Aleksoid1978/VideoRenderer/assets/8272206/35c64fd0-d2b4-4b7c-b0f3-24c521e9b536)

HDR10 content can be displayed in HDR using a HDR display, but dolby vision profile 5 downgraded to SDR

**Comment by Aleksoid1978** [comment]
Turn on HDR mode in Windows - then DV will be output as HDR.
There is no automatic switching of HDR mode in the system for DV.

**Comment by zbydown** [comment]
> Turn on HDR mode in Windows - then DV will be output as HDR. There is no automatic switching of HDR mode in the system for DV.

 Windows HDR mode is on, as I said before, there's no issue with HDR10 video, only with dv content

**Comment by Aleksoid1978** [comment]
On you screen - **HDR10: off**
Enable HDR mode in system, disable Auto display HDR On/Off in MPC VR.

**Comment by clsid2** [comment]
I really think there should be an additional **Auto display HDR On** (so without Off) option that never turns Windows HDR off, only turns it on when needed.

**Comment by zbydown** [comment]
> On you screen - **HDR10: off** Enable HDR mode in system, disable **Auto display HDR On/Off** in MPC VR.

After disabling "Auto display HDR On/Off", problem solved
Windows HDR is always forced to turn off when I play dv content if I enable this option. But no problem for HDR10 content

**Comment by Aleksoid1978** [comment]
> > On you screen - **HDR10: off** Enable HDR mode in system, disable **Auto display HDR On/Off** in MPC VR.
> 
> After disabling "Auto display HDR On/Off", problem solved Windows HDR is always forced to turn off when I start playing dv content if I enable this option. But no problem for HDR10 content

That's right - DV it's not HDR.
